// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2012/chartStyle';
const __ns1 = 'http://schemas.openxmlformats.org/drawingml/2006/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTChartStyle(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTChartStyle' }, init); }
export function createCTColorStyle(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyle' }, init); }
export function createCTColorStyleVariation(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation' }, init); }
export function createCTFontReference(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTFontReference' }, init); }
export function createCTMarkerLayout(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTMarkerLayout' }, init); }
export function createCTStyleColor(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor' }, init); }
export function createCTStyleEntry(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleEntry' }, init); }
export function createCTStyleReference(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleReference' }, init); }
export function createChartStyleElement(value) { return __element(__ns0, 'chartStyle', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTChartStyle'); }
export function createColorStyleElement(value) { return __element(__ns0, 'colorStyle', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyle'); }
export function createCTColorStyleVariationAlpha(value) { return __element(__ns1, 'alpha', value, 'org_docx4j_dml.CTPositiveFixedPercentage'); }
export function createCTStyleColorAlpha(value) { return __element(__ns1, 'alpha', value, 'org_docx4j_dml.CTPositiveFixedPercentage'); }
export function createCTColorStyleVariationAlphaMod(value) { return __element(__ns1, 'alphaMod', value, 'org_docx4j_dml.CTPositivePercentage'); }
export function createCTStyleColorAlphaMod(value) { return __element(__ns1, 'alphaMod', value, 'org_docx4j_dml.CTPositivePercentage'); }
export function createCTColorStyleVariationAlphaOff(value) { return __element(__ns1, 'alphaOff', value, 'org_docx4j_dml.CTFixedPercentage'); }
export function createCTStyleColorAlphaOff(value) { return __element(__ns1, 'alphaOff', value, 'org_docx4j_dml.CTFixedPercentage'); }
export function createCTColorStyleVariationBlue(value) { return __element(__ns1, 'blue', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorBlue(value) { return __element(__ns1, 'blue', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationBlueMod(value) { return __element(__ns1, 'blueMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorBlueMod(value) { return __element(__ns1, 'blueMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationBlueOff(value) { return __element(__ns1, 'blueOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorBlueOff(value) { return __element(__ns1, 'blueOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationComp(value) { return __element(__ns1, 'comp', value, 'org_docx4j_dml.CTComplementTransform'); }
export function createCTStyleColorComp(value) { return __element(__ns1, 'comp', value, 'org_docx4j_dml.CTComplementTransform'); }
export function createCTColorStyleVariationGamma(value) { return __element(__ns1, 'gamma', value, 'org_docx4j_dml.CTGammaTransform'); }
export function createCTStyleColorGamma(value) { return __element(__ns1, 'gamma', value, 'org_docx4j_dml.CTGammaTransform'); }
export function createCTColorStyleVariationGray(value) { return __element(__ns1, 'gray', value, 'org_docx4j_dml.CTGrayscaleTransform'); }
export function createCTStyleColorGray(value) { return __element(__ns1, 'gray', value, 'org_docx4j_dml.CTGrayscaleTransform'); }
export function createCTColorStyleVariationGreen(value) { return __element(__ns1, 'green', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorGreen(value) { return __element(__ns1, 'green', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationGreenMod(value) { return __element(__ns1, 'greenMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorGreenMod(value) { return __element(__ns1, 'greenMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationGreenOff(value) { return __element(__ns1, 'greenOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorGreenOff(value) { return __element(__ns1, 'greenOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationHue(value) { return __element(__ns1, 'hue', value, 'org_docx4j_dml.CTPositiveFixedAngle'); }
export function createCTStyleColorHue(value) { return __element(__ns1, 'hue', value, 'org_docx4j_dml.CTPositiveFixedAngle'); }
export function createCTColorStyleVariationHueMod(value) { return __element(__ns1, 'hueMod', value, 'org_docx4j_dml.CTPositivePercentage'); }
export function createCTStyleColorHueMod(value) { return __element(__ns1, 'hueMod', value, 'org_docx4j_dml.CTPositivePercentage'); }
export function createCTColorStyleVariationHueOff(value) { return __element(__ns1, 'hueOff', value, 'org_docx4j_dml.CTAngle'); }
export function createCTStyleColorHueOff(value) { return __element(__ns1, 'hueOff', value, 'org_docx4j_dml.CTAngle'); }
export function createCTColorStyleVariationInv(value) { return __element(__ns1, 'inv', value, 'org_docx4j_dml.CTInverseTransform'); }
export function createCTStyleColorInv(value) { return __element(__ns1, 'inv', value, 'org_docx4j_dml.CTInverseTransform'); }
export function createCTColorStyleVariationInvGamma(value) { return __element(__ns1, 'invGamma', value, 'org_docx4j_dml.CTInverseGammaTransform'); }
export function createCTStyleColorInvGamma(value) { return __element(__ns1, 'invGamma', value, 'org_docx4j_dml.CTInverseGammaTransform'); }
export function createCTColorStyleVariationLum(value) { return __element(__ns1, 'lum', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorLum(value) { return __element(__ns1, 'lum', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationLumMod(value) { return __element(__ns1, 'lumMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorLumMod(value) { return __element(__ns1, 'lumMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationLumOff(value) { return __element(__ns1, 'lumOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorLumOff(value) { return __element(__ns1, 'lumOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationRed(value) { return __element(__ns1, 'red', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorRed(value) { return __element(__ns1, 'red', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationRedMod(value) { return __element(__ns1, 'redMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorRedMod(value) { return __element(__ns1, 'redMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationRedOff(value) { return __element(__ns1, 'redOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorRedOff(value) { return __element(__ns1, 'redOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationSat(value) { return __element(__ns1, 'sat', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorSat(value) { return __element(__ns1, 'sat', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationSatMod(value) { return __element(__ns1, 'satMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorSatMod(value) { return __element(__ns1, 'satMod', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationSatOff(value) { return __element(__ns1, 'satOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTStyleColorSatOff(value) { return __element(__ns1, 'satOff', value, 'org_docx4j_dml.CTPercentage'); }
export function createCTColorStyleVariationShade(value) { return __element(__ns1, 'shade', value, 'org_docx4j_dml.CTPositiveFixedPercentage'); }
export function createCTStyleColorShade(value) { return __element(__ns1, 'shade', value, 'org_docx4j_dml.CTPositiveFixedPercentage'); }
export function createCTColorStyleVariationTint(value) { return __element(__ns1, 'tint', value, 'org_docx4j_dml.CTPositiveFixedPercentage'); }
export function createCTStyleColorTint(value) { return __element(__ns1, 'tint', value, 'org_docx4j_dml.CTPositiveFixedPercentage'); }
