// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x201611_diagram.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';

