// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main]. Do not edit.
import type * as M from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.js';

/** docx4j ObjectFactory.createCTCalculatedTimeColumn(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTCalculatedTimeColumn with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCalculatedTimeColumn(init?: Partial<Omit<M.CTCalculatedTimeColumn, 'TYPE_NAME' | 'PARENT'>>): M.CTCalculatedTimeColumn;
/** docx4j ObjectFactory.createCTModelTimeGrouping(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTModelTimeGrouping with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTModelTimeGrouping(init?: Partial<Omit<M.CTModelTimeGrouping, 'TYPE_NAME' | 'PARENT'>>): M.CTModelTimeGrouping;
/** docx4j ObjectFactory.createCTModelTimeGroupings(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTModelTimeGroupings with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTModelTimeGroupings(init?: Partial<Omit<M.CTModelTimeGroupings, 'TYPE_NAME' | 'PARENT'>>): M.CTModelTimeGroupings;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2014/11/main}modelTimeGroupings (docx4j ObjectFactory.createModelTimeGroupings(value)). */
export function createModelTimeGroupingsElement(value: M.CTModelTimeGroupings): M.TypedNamedValue<M.CTModelTimeGroupings>;
