// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_vml_wordprocessingDrawing]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'urn:schemas-microsoft-com:office:word';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function anchorlock(value) { return __element(__ns0, 'anchorlock', value, 'org_docx4j_vml_wordprocessingDrawing.CTAnchorLock'); }
export function borderbottom(value) { return __element(__ns0, 'borderbottom', value, 'org_docx4j_vml_wordprocessingDrawing.CTBorder'); }
export function borderleft(value) { return __element(__ns0, 'borderleft', value, 'org_docx4j_vml_wordprocessingDrawing.CTBorder'); }
export function borderright(value) { return __element(__ns0, 'borderright', value, 'org_docx4j_vml_wordprocessingDrawing.CTBorder'); }
export function bordertop(value) { return __element(__ns0, 'bordertop', value, 'org_docx4j_vml_wordprocessingDrawing.CTBorder'); }
export function wrap(value) { return __element(__ns0, 'wrap', value, 'org_docx4j_vml_wordprocessingDrawing.CTWrap'); }
