// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_w15symex]. Do not edit.
import type * as M from './org_docx4j_w15symex.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_w15symex.js';

/** docx4j ObjectFactory.createCTSymEx(): a org_docx4j_w15symex.CTSymEx with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSymEx(init?: Partial<Omit<M.CTSymEx, 'TYPE_NAME' | 'PARENT'>>): M.CTSymEx;
/** The global element {http://schemas.microsoft.com/office/word/2015/wordml/symex}symEx (docx4j ObjectFactory.createSymEx(value)). */
export function createSymExElement(value: M.CTSymEx): M.TypedNamedValue<M.CTSymEx>;
