// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x201612_diagram]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2016/12/diagram';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createLstStyleElement(value) { return __element(__ns0, 'lstStyle', value, 'org_docx4j_dml.CTTextListStyle'); }
export function createSpPrElement(value) { return __element(__ns0, 'spPr', value, 'org_docx4j_dml.CTShapeProperties'); }
