// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/spreadsheetml/2014/11/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function modelTimeGroupings(value) { return __element(__ns0, 'modelTimeGroupings', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTModelTimeGroupings'); }
