// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/powerpoint/2013/main/command';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTChangesInfo(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTChangesInfo' }, init); }
export function createCTCommentAuthorChanges(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentAuthorChanges' }, init); }
export function createCTCommentAuthorMoniker(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentAuthorMoniker' }, init); }
export function createCTCommentAuthorMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentAuthorMonikerList' }, init); }
export function createCTCommentChanges(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentChanges' }, init); }
export function createCTCommentMoniker(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentMoniker' }, init); }
export function createCTCommentMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentMonikerList' }, init); }
export function createCTDocumentChanges(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentChanges' }, init); }
export function createCTDocumentChangesList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentChangesList' }, init); }
export function createCTDocumentMoniker(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentMoniker' }, init); }
export function createCTDocumentMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentMonikerList' }, init); }
export function createCTMainMasterChanges(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTMainMasterChanges' }, init); }
export function createCTMainMasterMoniker(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTMainMasterMoniker' }, init); }
export function createCTMainMasterMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTMainMasterMonikerList' }, init); }
export function createCTSlideBaseMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideBaseMonikerList' }, init); }
export function createCTSlideChanges(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideChanges' }, init); }
export function createCTSlideLayoutChanges(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideLayoutChanges' }, init); }
export function createCTSlideLayoutMoniker(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideLayoutMoniker' }, init); }
export function createCTSlideLayoutMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideLayoutMonikerList' }, init); }
export function createCTSlideMoniker(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideMoniker' }, init); }
export function createCTSlideMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideMonikerList' }, init); }
export function createChgInfoElement(value) { return __element(__ns0, 'chgInfo', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTChangesInfo'); }
export function createCmAuthorMkLstElement(value) { return __element(__ns0, 'cmAuthorMkLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentAuthorMonikerList'); }
export function createCmMkLstElement(value) { return __element(__ns0, 'cmMkLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTCommentMonikerList'); }
export function createDocMkLstElement(value) { return __element(__ns0, 'docMkLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTDocumentMonikerList'); }
export function createSldBaseMkLstElement(value) { return __element(__ns0, 'sldBaseMkLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideBaseMonikerList'); }
export function createSldLayoutMkLstElement(value) { return __element(__ns0, 'sldLayoutMkLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideLayoutMonikerList'); }
export function createSldMasterMkLstElement(value) { return __element(__ns0, 'sldMasterMkLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTMainMasterMonikerList'); }
export function createSldMkLstElement(value) { return __element(__ns0, 'sldMkLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.CTSlideMonikerList'); }
