// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_dml_wordprocessingDrawing]. Do not edit.
import type * as M from './org_docx4j_dml_wordprocessingDrawing.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_dml_wordprocessingDrawing.js';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing.js';

/** The element {http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing}anchor. */
export function anchor(value: M.Anchor): M.TypedNamedValue<M.Anchor>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing}inline. */
export function inline(value: M.Inline): M.TypedNamedValue<M.Inline>;
