// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main]. Do not edit.
import type * as M from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.js';
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml.js';
import type * as Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.js';

/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}cacheHierarchy. */
export function cacheHierarchy(value: M.CTCacheHierarchy): M.TypedNamedValue<M.CTCacheHierarchy>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}cachedUniqueNames. */
export function cachedUniqueNames(value: M.CTCachedUniqueNames): M.TypedNamedValue<M.CTCachedUniqueNames>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}calculatedMember. */
export function calculatedMember(value: M.CTCalculatedMember): M.TypedNamedValue<M.CTCalculatedMember>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}connection. */
export function connection(value: M.CTConnection): M.TypedNamedValue<M.CTConnection>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}dataField. */
export function dataField(value: M.CTDataField): M.TypedNamedValue<M.CTDataField>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}dataModel. */
export function dataModel(value: M.CTDataModel): M.TypedNamedValue<M.CTDataModel>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}dxfs. */
export function dxfs(value: Dep_org_xlsx4j_sml.CTDxfs): M.TypedNamedValue<Dep_org_xlsx4j_sml.CTDxfs>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}pivotCacheIdVersion. */
export function pivotCacheIdVersion(value: M.CTPivotCacheIdVersion): M.TypedNamedValue<M.CTPivotCacheIdVersion>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}pivotCaches. */
export function pivotCaches(value: Dep_org_xlsx4j_sml.CTPivotCaches): M.TypedNamedValue<Dep_org_xlsx4j_sml.CTPivotCaches>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}pivotFilter. */
export function pivotFilter(value: M.CTPivotFilter): M.TypedNamedValue<M.CTPivotFilter>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}pivotTableData. */
export function pivotTableData(value: M.CTPivotTableData): M.TypedNamedValue<M.CTPivotTableData>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}pivotTableReferences. */
export function pivotTableReferences(value: M.CTPivotTableReferences): M.TypedNamedValue<M.CTPivotTableReferences>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}pivotTableUISettings. */
export function pivotTableUISettings(value: M.CTPivotTableUISettings): M.TypedNamedValue<M.CTPivotTableUISettings>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}queryTable. */
export function queryTable(value: M.CTQueryTable): M.TypedNamedValue<M.CTQueryTable>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}slicerCacheHideItemsWithNoData. */
export function slicerCacheHideItemsWithNoData(value: M.CTSlicerCacheHideNoData): M.TypedNamedValue<M.CTSlicerCacheHideNoData>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}slicerCachePivotTables. */
export function slicerCachePivotTables(value: Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCachePivotTables): M.TypedNamedValue<Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCachePivotTables>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}slicerCaches. */
export function slicerCaches(value: Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCaches): M.TypedNamedValue<Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCaches>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}survey. */
export function survey(value: M.CTSurvey): M.TypedNamedValue<M.CTSurvey>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}tableSlicerCache. */
export function tableSlicerCache(value: M.CTTableSlicerCache): M.TypedNamedValue<M.CTTableSlicerCache>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}timelineCacheDefinition. */
export function timelineCacheDefinition(value: M.CTTimelineCacheDefinition): M.TypedNamedValue<M.CTTimelineCacheDefinition>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}timelineCachePivotCaches. */
export function timelineCachePivotCaches(value: Dep_org_xlsx4j_sml.CTPivotCaches): M.TypedNamedValue<Dep_org_xlsx4j_sml.CTPivotCaches>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}timelineCacheRefs. */
export function timelineCacheRefs(value: M.CTTimelineCacheRefs): M.TypedNamedValue<M.CTTimelineCacheRefs>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}timelinePivotCacheDefinition. */
export function timelinePivotCacheDefinition(value: M.CTTimelinePivotCacheDefinition): M.TypedNamedValue<M.CTTimelinePivotCacheDefinition>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}timelineRefs. */
export function timelineRefs(value: M.CTTimelineRefs): M.TypedNamedValue<M.CTTimelineRefs>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}timelineStyles. */
export function timelineStyles(value: M.CTTimelineStyles): M.TypedNamedValue<M.CTTimelineStyles>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}timelines. */
export function timelines(value: M.CTTimelines): M.TypedNamedValue<M.CTTimelines>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}webExtensions. */
export function webExtensions(value: M.CTWebExtensions): M.TypedNamedValue<M.CTWebExtensions>;
/** The element {http://schemas.microsoft.com/office/spreadsheetml/2010/11/main}workbookPr. */
export function workbookPr(value: M.CTWorkbookPr): M.TypedNamedValue<M.CTWorkbookPr>;
