// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_dml_lockedCanvas]. Do not edit.
import type * as M from './org_docx4j_dml_lockedCanvas.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_dml_lockedCanvas.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';

/** The global element {http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas}lockedCanvas (docx4j ObjectFactory.createLockedCanvas(value)). */
export function createLockedCanvasElement(value: Dep_org_docx4j_dml.CTGvmlGroupShape): M.TypedNamedValue<Dep_org_docx4j_dml.CTGvmlGroupShape>;
