// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_w15symex]. Do not edit.
import type * as M from './org_docx4j_w15symex.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_w15symex.js';

/** The element {http://schemas.microsoft.com/office/word/2015/wordml/symex}symEx. */
export function symEx(value: M.CTSymEx): M.TypedNamedValue<M.CTSymEx>;
