// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2017/model3d';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTAmbientLight(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTAmbientLight' }, init); }
export function createCTDirectionalLight(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTDirectionalLight' }, init); }
export function createCTModel3D(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3D' }, init); }
export function createCTModel3DCamera(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3DCamera' }, init); }
export function createCTModel3DRaster(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3DRaster' }, init); }
export function createCTModel3DTransform(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3DTransform' }, init); }
export function createCTObjectViewport(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTObjectViewport' }, init); }
export function createCTOrthographicProjection(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTOrthographicProjection' }, init); }
export function createCTPerspectiveProjection(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTPerspectiveProjection' }, init); }
export function createCTPointLight(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTPointLight' }, init); }
export function createCTPositiveRatio(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTPositiveRatio' }, init); }
export function createCTRotate3D(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTRotate3D' }, init); }
export function createCTScale3D(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTScale3D' }, init); }
export function createCTSpotLight(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTSpotLight' }, init); }
export function createCTUnknownLight(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTUnknownLight' }, init); }
export function createCTWindowViewport(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTWindowViewport' }, init); }
export function createModel3DElement(value) { return __element(__ns0, 'model3D', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.CTModel3D'); }
