// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_w15]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/word/2012/wordml';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTCommentEx(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15.CTCommentEx' }, init); }
export function createCTCommentsEx(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15.CTCommentsEx' }, init); }
export function createCTGuid(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15.CTGuid' }, init); }
export function createCTPeople(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15.CTPeople' }, init); }
export function createCTPerson(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15.CTPerson' }, init); }
export function createCTPresenceInfo(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15.CTPresenceInfo' }, init); }
export function createCTSdtAppearance(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15.CTSdtAppearance' }, init); }
export function createCTSdtRepeatedSection(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15.CTSdtRepeatedSection' }, init); }
export function createAppearanceElement(value) { return __element(__ns0, 'appearance', value, 'org_docx4j_w15.CTSdtAppearance'); }
export function createChartTrackingRefBasedElement(value) { return __element(__ns0, 'chartTrackingRefBased', value, 'org_docx4j_wml.BooleanDefaultTrue'); }
export function createCollapsedElement(value) { return __element(__ns0, 'collapsed', value, 'org_docx4j_wml.BooleanDefaultTrue'); }
export function createColorElement(value) { return __element(__ns0, 'color', value, 'org_docx4j_wml.CTColor'); }
export function createCommentsExElement(value) { return __element(__ns0, 'commentsEx', value, 'org_docx4j_w15.CTCommentsEx'); }
export function createDataBindingElement(value) { return __element(__ns0, 'dataBinding', value, 'org_docx4j_wml.CTDataBinding'); }
export function createDocIdElement(value) { return __element(__ns0, 'docId', value, 'org_docx4j_w15.CTGuid'); }
export function createFootnoteColumnsElement(value) { return __element(__ns0, 'footnoteColumns', value, 'org_docx4j_wml.CTDecimalNumber'); }
export function createPeopleElement(value) { return __element(__ns0, 'people', value, 'org_docx4j_w15.CTPeople'); }
export function createRepeatingSectionElement(value) { return __element(__ns0, 'repeatingSection', value, 'org_docx4j_w15.CTSdtRepeatedSection'); }
export function createRepeatingSectionItemElement(value) { return __element(__ns0, 'repeatingSectionItem', value, 'org_docx4j_wml.CTEmpty'); }
export function createWebExtensionCreatedElement(value) { return __element(__ns0, 'webExtensionCreated', value, 'org_docx4j_wml.BooleanDefaultTrue'); }
export function createWebExtensionLinkedElement(value) { return __element(__ns0, 'webExtensionLinked', value, 'org_docx4j_wml.BooleanDefaultTrue'); }
