// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/spreadsheetml/2009/9/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function cacheField(value) { return __element(__ns0, 'cacheField', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCacheField'); }
export function cacheHierarchy(value) { return __element(__ns0, 'cacheHierarchy', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCacheHierarchy'); }
export function calculatedMember(value) { return __element(__ns0, 'calculatedMember', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCalculatedMember'); }
export function conditionalFormattings(value) { return __element(__ns0, 'conditionalFormattings', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTConditionalFormattings'); }
export function connection(value) { return __element(__ns0, 'connection', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTConnection'); }
export function customFilters(value) { return __element(__ns0, 'customFilters', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCustomFilters'); }
export function dataField(value) { return __element(__ns0, 'dataField', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDataField'); }
export function dataValidations(value) { return __element(__ns0, 'dataValidations', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDataValidations'); }
export function datastoreItem(value) { return __element(__ns0, 'datastoreItem', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDatastoreItem'); }
export function dxfs(value) { return __element(__ns0, 'dxfs', value, 'org_xlsx4j_sml.CTDxfs'); }
export function filter(value) { return __element(__ns0, 'filter', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTFilter'); }
export function formControlPr(value) { return __element(__ns0, 'formControlPr', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTFormControlPr'); }
export function iconFilter(value) { return __element(__ns0, 'iconFilter', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTIconFilter'); }
export function id(value) { return __element(__ns0, 'id', value); }
export function ignoredErrors(value) { return __element(__ns0, 'ignoredErrors', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTIgnoredErrors'); }
export function oleItem(value) { return __element(__ns0, 'oleItem', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOleItem'); }
export function pivotCacheDefinition(value) { return __element(__ns0, 'pivotCacheDefinition', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotCacheDefinition'); }
export function pivotCaches(value) { return __element(__ns0, 'pivotCaches', value, 'org_xlsx4j_sml.CTPivotCaches'); }
export function pivotField(value) { return __element(__ns0, 'pivotField', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotField'); }
export function pivotHierarchy(value) { return __element(__ns0, 'pivotHierarchy', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotHierarchy'); }
export function pivotTableDefinition(value) { return __element(__ns0, 'pivotTableDefinition', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotTableDefinition'); }
export function protectedRanges(value) { return __element(__ns0, 'protectedRanges', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTProtectedRanges'); }
export function slicerCacheDefinition(value) { return __element(__ns0, 'slicerCacheDefinition', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCacheDefinition'); }
export function slicerCaches(value) { return __element(__ns0, 'slicerCaches', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCaches'); }
export function slicerList(value) { return __element(__ns0, 'slicerList', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerRefs'); }
export function slicerStyles(value) { return __element(__ns0, 'slicerStyles', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerStyles'); }
export function slicers(value) { return __element(__ns0, 'slicers', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicers'); }
export function sortCondition(value) { return __element(__ns0, 'sortCondition', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSortCondition'); }
export function sourceConnection(value) { return __element(__ns0, 'sourceConnection', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSourceConnection'); }
export function sparklineGroups(value) { return __element(__ns0, 'sparklineGroups', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSparklineGroups'); }
export function table(value) { return __element(__ns0, 'table', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTable'); }
export function workbookPr(value) { return __element(__ns0, 'workbookPr', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTWorkbookPr'); }
