// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_xlsx4j_sml]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.openxmlformats.org/spreadsheetml/2006/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function MapInfo(value) { return __element(__ns0, 'MapInfo', value, 'org_xlsx4j_sml.CTMapInfo'); }
export function b(value) { return __element(__ns0, 'b', value, 'org_xlsx4j_sml.CTBooleanProperty'); }
export function calcChain(value) { return __element(__ns0, 'calcChain', value, 'org_xlsx4j_sml.CTCalcChain'); }
export function charset(value) { return __element(__ns0, 'charset', value, 'org_xlsx4j_sml.CTIntProperty'); }
export function chartsheet(value) { return __element(__ns0, 'chartsheet', value, 'org_xlsx4j_sml.CTChartsheet'); }
export function color(value) { return __element(__ns0, 'color', value, 'org_xlsx4j_sml.CTColor'); }
export function comments(value) { return __element(__ns0, 'comments', value, 'org_xlsx4j_sml.CTComments'); }
export function condense(value) { return __element(__ns0, 'condense', value, 'org_xlsx4j_sml.CTBooleanProperty'); }
export function connections(value) { return __element(__ns0, 'connections', value, 'org_xlsx4j_sml.CTConnections'); }
export function dialogsheet(value) { return __element(__ns0, 'dialogsheet', value, 'org_xlsx4j_sml.Dialogsheet'); }
export function extend(value) { return __element(__ns0, 'extend', value, 'org_xlsx4j_sml.CTBooleanProperty'); }
export function externalLink(value) { return __element(__ns0, 'externalLink', value, 'org_xlsx4j_sml.CTExternalLink'); }
export function family(value) { return __element(__ns0, 'family', value); }
export function headers(value) { return __element(__ns0, 'headers', value, 'org_xlsx4j_sml.CTRevisionHeaders'); }
export function i(value) { return __element(__ns0, 'i', value, 'org_xlsx4j_sml.CTBooleanProperty'); }
export function metadata(value) { return __element(__ns0, 'metadata', value, 'org_xlsx4j_sml.CTMetadata'); }
export function name(value) { return __element(__ns0, 'name', value, 'org_xlsx4j_sml.CTFontName'); }
export function outline(value) { return __element(__ns0, 'outline', value, 'org_xlsx4j_sml.CTBooleanProperty'); }
export function pivotCacheDefinition(value) { return __element(__ns0, 'pivotCacheDefinition', value, 'org_xlsx4j_sml.CTPivotCacheDefinition'); }
export function pivotCacheRecords(value) { return __element(__ns0, 'pivotCacheRecords', value, 'org_xlsx4j_sml.CTPivotCacheRecords'); }
export function pivotTableDefinition(value) { return __element(__ns0, 'pivotTableDefinition', value, 'org_xlsx4j_sml.CTPivotTableDefinition'); }
export function queryTable(value) { return __element(__ns0, 'queryTable', value, 'org_xlsx4j_sml.CTQueryTable'); }
export function rFont(value) { return __element(__ns0, 'rFont', value, 'org_xlsx4j_sml.CTFontName'); }
export function revisions(value) { return __element(__ns0, 'revisions', value, 'org_xlsx4j_sml.CTRevisions'); }
export function scheme(value) { return __element(__ns0, 'scheme', value, 'org_xlsx4j_sml.CTFontScheme'); }
export function shadow(value) { return __element(__ns0, 'shadow', value, 'org_xlsx4j_sml.CTBooleanProperty'); }
export function singleXmlCells(value) { return __element(__ns0, 'singleXmlCells', value, 'org_xlsx4j_sml.CTSingleXmlCells'); }
export function sst(value) { return __element(__ns0, 'sst', value, 'org_xlsx4j_sml.CTSst'); }
export function strike(value) { return __element(__ns0, 'strike', value, 'org_xlsx4j_sml.CTBooleanProperty'); }
export function styleSheet(value) { return __element(__ns0, 'styleSheet', value, 'org_xlsx4j_sml.CTStylesheet'); }
export function sz(value) { return __element(__ns0, 'sz', value, 'org_xlsx4j_sml.CTFontSize'); }
export function table(value) { return __element(__ns0, 'table', value, 'org_xlsx4j_sml.CTTable'); }
export function u(value) { return __element(__ns0, 'u', value, 'org_xlsx4j_sml.CTUnderlineProperty'); }
export function users(value) { return __element(__ns0, 'users', value, 'org_xlsx4j_sml.CTUsers'); }
export function vertAlign(value) { return __element(__ns0, 'vertAlign', value, 'org_xlsx4j_sml.CTVerticalAlignFontProperty'); }
export function volTypes(value) { return __element(__ns0, 'volTypes', value, 'org_xlsx4j_sml.CTVolTypes'); }
export function workbook(value) { return __element(__ns0, 'workbook', value, 'org_xlsx4j_sml.Workbook'); }
export function worksheet(value) { return __element(__ns0, 'worksheet', value, 'org_xlsx4j_sml.Worksheet'); }
