// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_org_w3_x1998_math_mathML]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://www.w3.org/1998/Math/MathML';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function abs(value) { return __element(__ns0, 'abs', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function and(value) { return __element(__ns0, 'and', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function apply(value) { return __element(__ns0, 'apply', value, 'org_docx4j_org_w3_x1998_math_mathML.ApplyType'); }
export function arccos(value) { return __element(__ns0, 'arccos', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function arcsin(value) { return __element(__ns0, 'arcsin', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function arctan(value) { return __element(__ns0, 'arctan', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function ceiling(value) { return __element(__ns0, 'ceiling', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function ci(value) { return __element(__ns0, 'ci', value, 'org_docx4j_org_w3_x1998_math_mathML.CiType'); }
export function cn(value) { return __element(__ns0, 'cn', value, 'org_docx4j_org_w3_x1998_math_mathML.CnType'); }
export function cos(value) { return __element(__ns0, 'cos', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function degree(value) { return __element(__ns0, 'degree', value, 'org_docx4j_org_w3_x1998_math_mathML.QualifierType'); }
export function divide(value) { return __element(__ns0, 'divide', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function eq(value) { return __element(__ns0, 'eq', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function exp(value) { return __element(__ns0, 'exp', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function exponentiale(value) { return __element(__ns0, 'exponentiale', value, 'org_docx4j_org_w3_x1998_math_mathML.ConstantType'); }
function _false(value) { return __element(__ns0, 'false', value, 'org_docx4j_org_w3_x1998_math_mathML.ConstantType'); }
export { _false as false };
export function floor(value) { return __element(__ns0, 'floor', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function geq(value) { return __element(__ns0, 'geq', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function gt(value) { return __element(__ns0, 'gt', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function leq(value) { return __element(__ns0, 'leq', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function ln(value) { return __element(__ns0, 'ln', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function log(value) { return __element(__ns0, 'log', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function logbase(value) { return __element(__ns0, 'logbase', value, 'org_docx4j_org_w3_x1998_math_mathML.QualifierType'); }
export function lt(value) { return __element(__ns0, 'lt', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function math(value) { return __element(__ns0, 'math', value, 'org_docx4j_org_w3_x1998_math_mathML.MathType'); }
export function max(value) { return __element(__ns0, 'max', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function min(value) { return __element(__ns0, 'min', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function minus(value) { return __element(__ns0, 'minus', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function neq(value) { return __element(__ns0, 'neq', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function not(value) { return __element(__ns0, 'not', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function or(value) { return __element(__ns0, 'or', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function pi(value) { return __element(__ns0, 'pi', value, 'org_docx4j_org_w3_x1998_math_mathML.ConstantType'); }
export function plus(value) { return __element(__ns0, 'plus', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function power(value) { return __element(__ns0, 'power', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function product(value) { return __element(__ns0, 'product', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function quotient(value) { return __element(__ns0, 'quotient', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function rem(value) { return __element(__ns0, 'rem', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function root(value) { return __element(__ns0, 'root', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function sep(value) { return __element(__ns0, 'sep', value, 'org_docx4j_org_w3_x1998_math_mathML.SepType'); }
export function sin(value) { return __element(__ns0, 'sin', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function sum(value) { return __element(__ns0, 'sum', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function tan(value) { return __element(__ns0, 'tan', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
export function times(value) { return __element(__ns0, 'times', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
function _true(value) { return __element(__ns0, 'true', value, 'org_docx4j_org_w3_x1998_math_mathML.ConstantType'); }
export { _true as true };
export function xor(value) { return __element(__ns0, 'xor', value, 'org_docx4j_org_w3_x1998_math_mathML.OperatorType'); }
