// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_xlsx4j_sml]. Do not edit.
import type * as M from './org_xlsx4j_sml.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_xlsx4j_sml.js';
import type * as Dep_org_xlsx4j_schemas_microsoft_com_office_excel_2006_main from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.js';
import type * as Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.js';
import type * as Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.js';
import type * as Dep_org_docx4j_mce from './org_docx4j_mce.js';
import type * as Dep_org_docx4j_sharedtypes from './org_docx4j_sharedtypes.js';
import type * as Dep_org_docx4j_dml_spreadsheetdrawing from './org_docx4j_dml_spreadsheetdrawing.js';
import type * as Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_revision from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_revision.js';

/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}MapInfo. */
export function MapInfo(value: M.CTMapInfo): M.TypedNamedValue<M.CTMapInfo>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}b. */
export function b(value: M.CTBooleanProperty): M.TypedNamedValue<M.CTBooleanProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}calcChain. */
export function calcChain(value: M.CTCalcChain): M.TypedNamedValue<M.CTCalcChain>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}charset. */
export function charset(value: M.CTIntProperty): M.TypedNamedValue<M.CTIntProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}chartsheet. */
export function chartsheet(value: M.CTChartsheet): M.TypedNamedValue<M.CTChartsheet>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}color. */
export function color(value: M.CTColor): M.TypedNamedValue<M.CTColor>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}comments. */
export function comments(value: M.CTComments): M.TypedNamedValue<M.CTComments>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}condense. */
export function condense(value: M.CTBooleanProperty): M.TypedNamedValue<M.CTBooleanProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}connections. */
export function connections(value: M.CTConnections): M.TypedNamedValue<M.CTConnections>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}dialogsheet. */
export function dialogsheet(value: M.Dialogsheet): M.TypedNamedValue<M.Dialogsheet>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}extend. */
export function extend(value: M.CTBooleanProperty): M.TypedNamedValue<M.CTBooleanProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}externalLink. */
export function externalLink(value: M.CTExternalLink): M.TypedNamedValue<M.CTExternalLink>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}family (2 types by scope: TYPE_NAME is left to the caller; see the scoped create* wrappers). */
export function family(value: M.CTFontFamily | M.CTIntProperty): M.TypedNamedValue<M.CTFontFamily | M.CTIntProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}headers. */
export function headers(value: M.CTRevisionHeaders): M.TypedNamedValue<M.CTRevisionHeaders>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}i. */
export function i(value: M.CTBooleanProperty): M.TypedNamedValue<M.CTBooleanProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}metadata. */
export function metadata(value: M.CTMetadata): M.TypedNamedValue<M.CTMetadata>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}name. */
export function name(value: M.CTFontName): M.TypedNamedValue<M.CTFontName>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}outline. */
export function outline(value: M.CTBooleanProperty): M.TypedNamedValue<M.CTBooleanProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}pivotCacheDefinition. */
export function pivotCacheDefinition(value: M.CTPivotCacheDefinition): M.TypedNamedValue<M.CTPivotCacheDefinition>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}pivotCacheRecords. */
export function pivotCacheRecords(value: M.CTPivotCacheRecords): M.TypedNamedValue<M.CTPivotCacheRecords>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}pivotTableDefinition. */
export function pivotTableDefinition(value: M.CTPivotTableDefinition): M.TypedNamedValue<M.CTPivotTableDefinition>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}queryTable. */
export function queryTable(value: M.CTQueryTable): M.TypedNamedValue<M.CTQueryTable>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}rFont. */
export function rFont(value: M.CTFontName): M.TypedNamedValue<M.CTFontName>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}revisions. */
export function revisions(value: M.CTRevisions): M.TypedNamedValue<M.CTRevisions>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}scheme. */
export function scheme(value: M.CTFontScheme): M.TypedNamedValue<M.CTFontScheme>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}shadow. */
export function shadow(value: M.CTBooleanProperty): M.TypedNamedValue<M.CTBooleanProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}singleXmlCells. */
export function singleXmlCells(value: M.CTSingleXmlCells): M.TypedNamedValue<M.CTSingleXmlCells>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}sst. */
export function sst(value: M.CTSst): M.TypedNamedValue<M.CTSst>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}strike. */
export function strike(value: M.CTBooleanProperty): M.TypedNamedValue<M.CTBooleanProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}styleSheet. */
export function styleSheet(value: M.CTStylesheet): M.TypedNamedValue<M.CTStylesheet>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}sz. */
export function sz(value: M.CTFontSize): M.TypedNamedValue<M.CTFontSize>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}table. */
export function table(value: M.CTTable): M.TypedNamedValue<M.CTTable>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}u. */
export function u(value: M.CTUnderlineProperty): M.TypedNamedValue<M.CTUnderlineProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}users. */
export function users(value: M.CTUsers): M.TypedNamedValue<M.CTUsers>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}vertAlign. */
export function vertAlign(value: M.CTVerticalAlignFontProperty): M.TypedNamedValue<M.CTVerticalAlignFontProperty>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}volTypes. */
export function volTypes(value: M.CTVolTypes): M.TypedNamedValue<M.CTVolTypes>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}workbook. */
export function workbook(value: M.Workbook): M.TypedNamedValue<M.Workbook>;
/** The element {http://schemas.openxmlformats.org/spreadsheetml/2006/main}worksheet. */
export function worksheet(value: M.Worksheet): M.TypedNamedValue<M.Worksheet>;
