// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_summaryzoom]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/powerpoint/2016/summaryzoom';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTFixedLayout(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_summaryzoom.CTFixedLayout' }, init); }
export function createCTGridLayout(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_summaryzoom.CTGridLayout' }, init); }
export function createCTSummaryZoom(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_summaryzoom.CTSummaryZoom' }, init); }
export function createCTSummaryZoomObject(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_summaryzoom.CTSummaryZoomObject' }, init); }
export function createSummaryZmElement(value) { return __element(__ns0, 'summaryZm', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_summaryzoom.CTSummaryZoom'); }
