// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x201703_chart]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x201703_chart.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x201703_chart.js';

/** docx4j ObjectFactory.createCTBooleanFalse(): a org_docx4j_com_microsoft_schemas_office_drawing_x201703_chart.CTBooleanFalse with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBooleanFalse(init?: Partial<Omit<M.CTBooleanFalse, 'TYPE_NAME' | 'PARENT'>>): M.CTBooleanFalse;
/** docx4j ObjectFactory.createCTDataDisplayOptions16(): a org_docx4j_com_microsoft_schemas_office_drawing_x201703_chart.CTDataDisplayOptions16 with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDataDisplayOptions16(init?: Partial<Omit<M.CTDataDisplayOptions16, 'TYPE_NAME' | 'PARENT'>>): M.CTDataDisplayOptions16;
/** The global element {http://schemas.microsoft.com/office/drawing/2017/03/chart}dataDisplayOptions16 (docx4j ObjectFactory.createDataDisplayOptions16(value)). */
export function createDataDisplayOptions16Element(value: M.CTDataDisplayOptions16): M.TypedNamedValue<M.CTDataDisplayOptions16>;
