// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main]. Do not edit.
import type * as M from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2012_main.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml.js';

/** The element {http://schemas.microsoft.com/office/powerpoint/2012/main}chartTrackingRefBased. */
export function chartTrackingRefBased(value: M.CTChartTrackingRefBased): M.TypedNamedValue<M.CTChartTrackingRefBased>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2012/main}notesGuideLst. */
export function notesGuideLst(value: M.CTExtendedGuideList): M.TypedNamedValue<M.CTExtendedGuideList>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2012/main}presenceInfo. */
export function presenceInfo(value: M.CTPresenceInfo): M.TypedNamedValue<M.CTPresenceInfo>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2012/main}prstTrans. */
export function prstTrans(value: M.CTPresetTransition): M.TypedNamedValue<M.CTPresetTransition>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2012/main}sldGuideLst. */
export function sldGuideLst(value: M.CTExtendedGuideList): M.TypedNamedValue<M.CTExtendedGuideList>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2012/main}threadingInfo. */
export function threadingInfo(value: M.CTCommentThreading): M.TypedNamedValue<M.CTCommentThreading>;
