// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2013/main/command';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTChangesData(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTChangesData' }, init); }
export function createCTConnectorChanges(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorChanges' }, init); }
export function createCTConnectorMoniker(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorMoniker' }, init); }
export function createCTConnectorMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorMonikerList' }, init); }
export function createCTGraphicFrameChanges(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameChanges' }, init); }
export function createCTGraphicFrameMoniker(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameMoniker' }, init); }
export function createCTGraphicFrameMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameMonikerList' }, init); }
export function createCTGroupShapeChanges(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeChanges' }, init); }
export function createCTGroupShapeMoniker(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeMoniker' }, init); }
export function createCTGroupShapeMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeMonikerList' }, init); }
export function createCTInkChanges(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkChanges' }, init); }
export function createCTInkMoniker(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkMoniker' }, init); }
export function createCTInkMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkMonikerList' }, init); }
export function createCTPictureChanges(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureChanges' }, init); }
export function createCTPictureMoniker(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureMoniker' }, init); }
export function createCTPictureMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureMonikerList' }, init); }
export function createCTShapeChanges(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeChanges' }, init); }
export function createCTShapeMoniker(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeMoniker' }, init); }
export function createCTShapeMonikerList(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeMonikerList' }, init); }
export function createCxnSpMkLstElement(value) { return __element(__ns0, 'cxnSpMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorMonikerList'); }
export function createGraphicFrameMkLstElement(value) { return __element(__ns0, 'graphicFrameMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameMonikerList'); }
export function createGrpMkLstElement(value) { return __element(__ns0, 'grpMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeMonikerList'); }
export function createInkMkLstElement(value) { return __element(__ns0, 'inkMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkMonikerList'); }
export function createPicMkLstElement(value) { return __element(__ns0, 'picMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureMonikerList'); }
export function createSpMkLstElement(value) { return __element(__ns0, 'spMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeMonikerList'); }
