// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2018_calcfeatures] as an ES module. Do not edit.
export const org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2018_calcfeatures = {
  name: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2018_calcfeatures',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/spreadsheetml\/2018\/calcfeatures',
  typeInfos: [{
      localName: 'CTCalcFeature',
      typeName: 'CT_CalcFeature',
      propertyInfos: [{
          name: 'name',
          required: true,
          attributeName: {
            localPart: 'name'
          },
          type: 'attribute'
        }]
    }, {
      localName: 'CTCalcFeatures',
      typeName: 'CT_CalcFeatures',
      propertyInfos: [{
          name: 'feature',
          required: true,
          collection: true,
          typeInfo: '.CTCalcFeature'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTCalcFeatures',
      elementName: 'calcFeatures'
    }]
};
