// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2018_animation]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
