// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_vml_presentationDrawing]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'urn:schemas-microsoft-com:office:powerpoint';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTEmpty(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_vml_presentationDrawing.CTEmpty' }, init); }
export function createCTRel(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_vml_presentationDrawing.CTRel' }, init); }
export function createIscommentElement(value) { return __element(__ns0, 'iscomment', value, 'org_docx4j_vml_presentationDrawing.CTEmpty'); }
export function createTextdataElement(value) { return __element(__ns0, 'textdata', value, 'org_docx4j_vml_presentationDrawing.CTRel'); }
