// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_vml_officedrawing]. Do not edit.
import type * as M from './org_docx4j_vml_officedrawing.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_vml_officedrawing.js';
import type * as Dep_org_docx4j_vml from './org_docx4j_vml.js';

/** The element {urn:schemas-microsoft-com:office:office}OLEObject. */
export function OLEObject(value: M.CTOLEObject): M.TypedNamedValue<M.CTOLEObject>;
/** The element {urn:schemas-microsoft-com:office:office}bottom. */
export function bottom(value: M.CTStrokeChild): M.TypedNamedValue<M.CTStrokeChild>;
/** The element {urn:schemas-microsoft-com:office:office}callout. */
export function callout(value: M.CTCallout): M.TypedNamedValue<M.CTCallout>;
/** The element {urn:schemas-microsoft-com:office:office}clippath. */
export function clippath(value: M.CTClipPath): M.TypedNamedValue<M.CTClipPath>;
/** The element {urn:schemas-microsoft-com:office:office}column. */
export function column(value: M.CTStrokeChild): M.TypedNamedValue<M.CTStrokeChild>;
/** The element {urn:schemas-microsoft-com:office:office}complex. */
export function complex(value: M.CTComplex): M.TypedNamedValue<M.CTComplex>;
/** The element {urn:schemas-microsoft-com:office:office}diagram. */
export function diagram(value: M.CTDiagram): M.TypedNamedValue<M.CTDiagram>;
/** The element {urn:schemas-microsoft-com:office:office}extrusion. */
export function extrusion(value: M.CTExtrusion): M.TypedNamedValue<M.CTExtrusion>;
/** The element {urn:schemas-microsoft-com:office:office}fill. */
export function fill(value: M.CTFill): M.TypedNamedValue<M.CTFill>;
/** The element {urn:schemas-microsoft-com:office:office}ink. */
export function ink(value: M.CTInk): M.TypedNamedValue<M.CTInk>;
/** The element {urn:schemas-microsoft-com:office:office}left. */
export function left(value: M.CTStrokeChild): M.TypedNamedValue<M.CTStrokeChild>;
/** The element {urn:schemas-microsoft-com:office:office}lock. */
export function lock(value: M.CTLock): M.TypedNamedValue<M.CTLock>;
/** The element {urn:schemas-microsoft-com:office:office}right. */
export function right(value: M.CTStrokeChild): M.TypedNamedValue<M.CTStrokeChild>;
/** The element {urn:schemas-microsoft-com:office:office}shapedefaults. */
export function shapedefaults(value: M.CTShapeDefaults): M.TypedNamedValue<M.CTShapeDefaults>;
/** The element {urn:schemas-microsoft-com:office:office}shapelayout. */
export function shapelayout(value: M.CTShapeLayout): M.TypedNamedValue<M.CTShapeLayout>;
/** The element {urn:schemas-microsoft-com:office:office}signatureline. */
export function signatureline(value: M.CTSignatureLine): M.TypedNamedValue<M.CTSignatureLine>;
/** The element {urn:schemas-microsoft-com:office:office}skew. */
export function skew(value: M.CTSkew): M.TypedNamedValue<M.CTSkew>;
/** The element {urn:schemas-microsoft-com:office:office}top. */
export function top(value: M.CTStrokeChild): M.TypedNamedValue<M.CTStrokeChild>;
