// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2010_chartDrawing]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2010_chartDrawing.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2010_chartDrawing.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2010_main from './org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.js';

/** The element {http://schemas.microsoft.com/office/drawing/2010/chartDrawing}contentPart. */
export function contentPart(value: M.CTContentPart): M.TypedNamedValue<M.CTContentPart>;
