// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2018_hyperlinkcolor]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2018_hyperlinkcolor.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2018_hyperlinkcolor.js';

/** docx4j ObjectFactory.createCTHyperlinkColor(): a org_docx4j_com_microsoft_schemas_office_drawing_x2018_hyperlinkcolor.CTHyperlinkColor with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTHyperlinkColor(init?: Partial<Omit<M.CTHyperlinkColor, 'TYPE_NAME' | 'PARENT'>>): M.CTHyperlinkColor;
/** The global element {http://schemas.microsoft.com/office/drawing/2018/hyperlinkcolor}hlinkClr (docx4j ObjectFactory.createHlinkClr(value)). */
export function createHlinkClrElement(value: M.CTHyperlinkColor): M.TypedNamedValue<M.CTHyperlinkColor>;
