// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTCalculatedTimeColumn {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTCalculatedTimeColumn';
  readonly PARENT?: CTModelTimeGrouping;
  columnId: string;
  columnName: string;
  contentType: STModelTimeGroupingContentType;
  isSelected: boolean;
}

export interface CTModelTimeGrouping {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTModelTimeGrouping';
  readonly PARENT?: CTModelTimeGroupings;
  calculatedTimeColumn: CTCalculatedTimeColumn[];
  columnId: string;
  columnName: string;
  tableName: string;
}

export interface CTModelTimeGroupings {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTModelTimeGroupings';
  modelTimeGrouping: CTModelTimeGrouping[];
}

export type STModelTimeGroupingContentType = 'years' | 'quarters' | 'monthsindex' | 'months' | 'daysindex' | 'days' | 'hours' | 'minutes' | 'seconds';

export type ModelTimeGroupingsElement = TypedNamedValue<CTModelTimeGroupings>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = ModelTimeGroupingsElement;

/** The Jsonix mapping [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main] exported by the module's JavaScript file. */
export declare const org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main: JsonixMapping<RootElement>;
