// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_docProps_core]. Do not edit.
import type * as M from './org_docx4j_docProps_core.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_docProps_core.js';
import type * as Dep_org_docx4j_docProps_core_dc_elements from './org_docx4j_docProps_core_dc_elements.js';

/** docx4j ObjectFactory.createCoreProperties(): a org_docx4j_docProps_core.CoreProperties with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCoreProperties(init?: Partial<Omit<M.CoreProperties, 'TYPE_NAME' | 'PARENT'>>): M.CoreProperties;
/** The global element {http://schemas.openxmlformats.org/package/2006/metadata/core-properties}coreProperties (docx4j ObjectFactory.createCoreProperties(value)). */
export function createCorePropertiesElement(value: M.CoreProperties): M.TypedNamedValue<M.CoreProperties>;
