// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2014/chartex';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTAddress(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAddress' }, init); }
export function createCTAggregation(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAggregation' }, init); }
export function createCTAxis(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxis' }, init); }
export function createCTAxisId(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxisId' }, init); }
export function createCTAxisTitle(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxisTitle' }, init); }
export function createCTAxisUnits(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxisUnits' }, init); }
export function createCTAxisUnitsLabel(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTAxisUnitsLabel' }, init); }
export function createCTBinning(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTBinning' }, init); }
export function createCTCategoryAxisScaling(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTCategoryAxisScaling' }, init); }
export function createCTChart(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChart' }, init); }
export function createCTChartData(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChartData' }, init); }
export function createCTChartSpace(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChartSpace' }, init); }
export function createCTChartTitle(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChartTitle' }, init); }
export function createCTClear(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTClear' }, init); }
export function createCTCopyrights(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTCopyrights' }, init); }
export function createCTData(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTData' }, init); }
export function createCTDataId(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataId' }, init); }
export function createCTDataLabel(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataLabel' }, init); }
export function createCTDataLabelHidden(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataLabelHidden' }, init); }
export function createCTDataLabelVisibilities(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataLabelVisibilities' }, init); }
export function createCTDataLabels(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataLabels' }, init); }
export function createCTDataPoint(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTDataPoint' }, init); }
export function createCTExtension(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTExtension' }, init); }
export function createCTExtensionList(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTExtensionList' }, init); }
export function createCTExternalData(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTExternalData' }, init); }
export function createCTExtremeValueColorPosition(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTExtremeValueColorPosition' }, init); }
export function createCTFormatOverride(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormatOverride' }, init); }
export function createCTFormatOverrides(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormatOverrides' }, init); }
export function createCTFormula(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormula' }, init); }
export function createCTGeoCache(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoCache' }, init); }
export function createCTGeoChildEntities(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildEntities' }, init); }
export function createCTGeoChildEntitiesQuery(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildEntitiesQuery' }, init); }
export function createCTGeoChildEntitiesQueryResult(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildEntitiesQueryResult' }, init); }
export function createCTGeoChildEntitiesQueryResults(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildEntitiesQueryResults' }, init); }
export function createCTGeoChildTypes(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoChildTypes' }, init); }
export function createCTGeoData(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoData' }, init); }
export function createCTGeoDataEntityQuery(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataEntityQuery' }, init); }
export function createCTGeoDataEntityQueryResult(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataEntityQueryResult' }, init); }
export function createCTGeoDataEntityQueryResults(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataEntityQueryResults' }, init); }
export function createCTGeoDataPointQuery(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataPointQuery' }, init); }
export function createCTGeoDataPointToEntityQuery(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataPointToEntityQuery' }, init); }
export function createCTGeoDataPointToEntityQueryResult(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataPointToEntityQueryResult' }, init); }
export function createCTGeoDataPointToEntityQueryResults(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoDataPointToEntityQueryResults' }, init); }
export function createCTGeoEntity(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoEntity' }, init); }
export function createCTGeoHierarchyEntity(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoHierarchyEntity' }, init); }
export function createCTGeoLocation(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocation' }, init); }
export function createCTGeoLocationQuery(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocationQuery' }, init); }
export function createCTGeoLocationQueryResult(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocationQueryResult' }, init); }
export function createCTGeoLocationQueryResults(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocationQueryResults' }, init); }
export function createCTGeoLocations(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoLocations' }, init); }
export function createCTGeoParentEntitiesQuery(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoParentEntitiesQuery' }, init); }
export function createCTGeoParentEntitiesQueryResult(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoParentEntitiesQueryResult' }, init); }
export function createCTGeoParentEntitiesQueryResults(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoParentEntitiesQueryResults' }, init); }
export function createCTGeoParentEntity(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoParentEntity' }, init); }
export function createCTGeoPolygon(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoPolygon' }, init); }
export function createCTGeoPolygons(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeoPolygons' }, init); }
export function createCTGeography(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGeography' }, init); }
export function createCTGridlines(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTGridlines' }, init); }
export function createCTHeaderFooter(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTHeaderFooter' }, init); }
export function createCTLegend(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTLegend' }, init); }
export function createCTNumberColorPosition(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumberColorPosition' }, init); }
export function createCTNumberFormat(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumberFormat' }, init); }
export function createCTNumericDimension(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumericDimension' }, init); }
export function createCTNumericLevel(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumericLevel' }, init); }
export function createCTNumericValue(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumericValue' }, init); }
export function createCTPageMargins(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPageMargins' }, init); }
export function createCTPageSetup(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPageSetup' }, init); }
export function createCTParentLabelLayout(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTParentLabelLayout' }, init); }
export function createCTPercentageColorPosition(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPercentageColorPosition' }, init); }
export function createCTPlotArea(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPlotArea' }, init); }
export function createCTPlotAreaRegion(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPlotAreaRegion' }, init); }
export function createCTPlotSurface(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPlotSurface' }, init); }
export function createCTPrintSettings(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTPrintSettings' }, init); }
export function createCTRegionLabelLayout(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTRegionLabelLayout' }, init); }
export function createCTRelId(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTRelId' }, init); }
export function createCTSeries(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSeries' }, init); }
export function createCTSeriesElementVisibilities(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSeriesElementVisibilities' }, init); }
export function createCTSeriesLayoutProperties(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSeriesLayoutProperties' }, init); }
export function createCTStatistics(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStatistics' }, init); }
export function createCTStringDimension(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStringDimension' }, init); }
export function createCTStringLevel(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStringLevel' }, init); }
export function createCTStringValue(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStringValue' }, init); }
export function createCTSubtotalIndex(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSubtotalIndex' }, init); }
export function createCTSubtotals(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTSubtotals' }, init); }
export function createCTText(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTText' }, init); }
export function createCTTextData(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTTextData' }, init); }
export function createCTTickLabels(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTTickLabels' }, init); }
export function createCTTickMarks(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTTickMarks' }, init); }
export function createCTValueAxisScaling(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueAxisScaling' }, init); }
export function createCTValueColorEndPosition(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueColorEndPosition' }, init); }
export function createCTValueColorMiddlePosition(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueColorMiddlePosition' }, init); }
export function createCTValueColorPositions(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueColorPositions' }, init); }
export function createCTValueColors(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTValueColors' }, init); }
export function createChartElement(value) { return __element(__ns0, 'chart', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTRelId'); }
export function createChartSpaceElement(value) { return __element(__ns0, 'chartSpace', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTChartSpace'); }
export function createCTNumericDimensionF(value) { return __element(__ns0, 'f', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormula'); }
export function createCTStringDimensionF(value) { return __element(__ns0, 'f', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormula'); }
export function createCTTextDataF(value) { return __element(__ns0, 'f', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormula'); }
export function createCTNumericDimensionLvl(value) { return __element(__ns0, 'lvl', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTNumericLevel'); }
export function createCTStringDimensionLvl(value) { return __element(__ns0, 'lvl', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTStringLevel'); }
export function createCTNumericDimensionNf(value) { return __element(__ns0, 'nf', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormula'); }
export function createCTStringDimensionNf(value) { return __element(__ns0, 'nf', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.CTFormula'); }
export function createCTTextDataV(value) { return __element(__ns0, 'v', value); }
