// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/powerpoint/2015/10/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function revInfo(value) { return __element(__ns0, 'revInfo', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main.CTRevisionInfo'); }
