// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_w15]. Do not edit.
import type * as M from './org_docx4j_w15.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_w15.js';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml.js';

/** The element {http://schemas.microsoft.com/office/word/2012/wordml}appearance. */
export function appearance(value: M.CTSdtAppearance): M.TypedNamedValue<M.CTSdtAppearance>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}chartTrackingRefBased. */
export function chartTrackingRefBased(value: Dep_org_docx4j_wml.BooleanDefaultTrue): M.TypedNamedValue<Dep_org_docx4j_wml.BooleanDefaultTrue>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}collapsed. */
export function collapsed(value: Dep_org_docx4j_wml.BooleanDefaultTrue): M.TypedNamedValue<Dep_org_docx4j_wml.BooleanDefaultTrue>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}color. */
export function color(value: Dep_org_docx4j_wml.CTColor): M.TypedNamedValue<Dep_org_docx4j_wml.CTColor>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}commentsEx. */
export function commentsEx(value: M.CTCommentsEx): M.TypedNamedValue<M.CTCommentsEx>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}dataBinding. */
export function dataBinding(value: Dep_org_docx4j_wml.CTDataBinding): M.TypedNamedValue<Dep_org_docx4j_wml.CTDataBinding>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}docId. */
export function docId(value: M.CTGuid): M.TypedNamedValue<M.CTGuid>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}footnoteColumns. */
export function footnoteColumns(value: Dep_org_docx4j_wml.CTDecimalNumber): M.TypedNamedValue<Dep_org_docx4j_wml.CTDecimalNumber>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}people. */
export function people(value: M.CTPeople): M.TypedNamedValue<M.CTPeople>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}repeatingSection. */
export function repeatingSection(value: M.CTSdtRepeatedSection): M.TypedNamedValue<M.CTSdtRepeatedSection>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}repeatingSectionItem. */
export function repeatingSectionItem(value: Dep_org_docx4j_wml.CTEmpty): M.TypedNamedValue<Dep_org_docx4j_wml.CTEmpty>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}webExtensionCreated. */
export function webExtensionCreated(value: Dep_org_docx4j_wml.BooleanDefaultTrue): M.TypedNamedValue<Dep_org_docx4j_wml.BooleanDefaultTrue>;
/** The element {http://schemas.microsoft.com/office/word/2012/wordml}webExtensionLinked. */
export function webExtensionLinked(value: Dep_org_docx4j_wml.BooleanDefaultTrue): M.TypedNamedValue<Dep_org_docx4j_wml.BooleanDefaultTrue>;
