// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';

/** docx4j ObjectFactory.createCTChartStyle(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTChartStyle with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTChartStyle(init?: Partial<Omit<M.CTChartStyle, 'TYPE_NAME' | 'PARENT'>>): M.CTChartStyle;
/** docx4j ObjectFactory.createCTColorStyle(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyle with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTColorStyle(init?: Partial<Omit<M.CTColorStyle, 'TYPE_NAME' | 'PARENT'>>): M.CTColorStyle;
/** docx4j ObjectFactory.createCTColorStyleVariation(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTColorStyleVariation(init?: Partial<Omit<M.CTColorStyleVariation, 'TYPE_NAME' | 'PARENT'>>): M.CTColorStyleVariation;
/** docx4j ObjectFactory.createCTFontReference(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTFontReference with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFontReference(init?: Partial<Omit<M.CTFontReference, 'TYPE_NAME' | 'PARENT'>>): M.CTFontReference;
/** docx4j ObjectFactory.createCTMarkerLayout(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTMarkerLayout with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTMarkerLayout(init?: Partial<Omit<M.CTMarkerLayout, 'TYPE_NAME' | 'PARENT'>>): M.CTMarkerLayout;
/** docx4j ObjectFactory.createCTStyleColor(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTStyleColor(init?: Partial<Omit<M.CTStyleColor, 'TYPE_NAME' | 'PARENT'>>): M.CTStyleColor;
/** docx4j ObjectFactory.createCTStyleEntry(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleEntry with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTStyleEntry(init?: Partial<Omit<M.CTStyleEntry, 'TYPE_NAME' | 'PARENT'>>): M.CTStyleEntry;
/** docx4j ObjectFactory.createCTStyleReference(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleReference with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTStyleReference(init?: Partial<Omit<M.CTStyleReference, 'TYPE_NAME' | 'PARENT'>>): M.CTStyleReference;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chartStyle}chartStyle (docx4j ObjectFactory.createChartStyle(value)). */
export function createChartStyleElement(value: M.CTChartStyle): M.TypedNamedValue<M.CTChartStyle>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chartStyle}colorStyle (docx4j ObjectFactory.createColorStyle(value)). */
export function createColorStyleElement(value: M.CTColorStyle): M.TypedNamedValue<M.CTColorStyle>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}alpha in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationAlpha(value)). */
export function createCTColorStyleVariationAlpha(value: Dep_org_docx4j_dml.CTPositiveFixedPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositiveFixedPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}alpha in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorAlpha(value)). */
export function createCTStyleColorAlpha(value: Dep_org_docx4j_dml.CTPositiveFixedPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositiveFixedPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}alphaMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationAlphaMod(value)). */
export function createCTColorStyleVariationAlphaMod(value: Dep_org_docx4j_dml.CTPositivePercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositivePercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}alphaMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorAlphaMod(value)). */
export function createCTStyleColorAlphaMod(value: Dep_org_docx4j_dml.CTPositivePercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositivePercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}alphaOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationAlphaOff(value)). */
export function createCTColorStyleVariationAlphaOff(value: Dep_org_docx4j_dml.CTFixedPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTFixedPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}alphaOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorAlphaOff(value)). */
export function createCTStyleColorAlphaOff(value: Dep_org_docx4j_dml.CTFixedPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTFixedPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}blue in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationBlue(value)). */
export function createCTColorStyleVariationBlue(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}blue in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorBlue(value)). */
export function createCTStyleColorBlue(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}blueMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationBlueMod(value)). */
export function createCTColorStyleVariationBlueMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}blueMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorBlueMod(value)). */
export function createCTStyleColorBlueMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}blueOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationBlueOff(value)). */
export function createCTColorStyleVariationBlueOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}blueOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorBlueOff(value)). */
export function createCTStyleColorBlueOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}comp in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationComp(value)). */
export function createCTColorStyleVariationComp(value: Dep_org_docx4j_dml.CTComplementTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTComplementTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}comp in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorComp(value)). */
export function createCTStyleColorComp(value: Dep_org_docx4j_dml.CTComplementTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTComplementTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}gamma in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationGamma(value)). */
export function createCTColorStyleVariationGamma(value: Dep_org_docx4j_dml.CTGammaTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTGammaTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}gamma in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorGamma(value)). */
export function createCTStyleColorGamma(value: Dep_org_docx4j_dml.CTGammaTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTGammaTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}gray in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationGray(value)). */
export function createCTColorStyleVariationGray(value: Dep_org_docx4j_dml.CTGrayscaleTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTGrayscaleTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}gray in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorGray(value)). */
export function createCTStyleColorGray(value: Dep_org_docx4j_dml.CTGrayscaleTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTGrayscaleTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}green in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationGreen(value)). */
export function createCTColorStyleVariationGreen(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}green in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorGreen(value)). */
export function createCTStyleColorGreen(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}greenMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationGreenMod(value)). */
export function createCTColorStyleVariationGreenMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}greenMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorGreenMod(value)). */
export function createCTStyleColorGreenMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}greenOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationGreenOff(value)). */
export function createCTColorStyleVariationGreenOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}greenOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorGreenOff(value)). */
export function createCTStyleColorGreenOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}hue in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationHue(value)). */
export function createCTColorStyleVariationHue(value: Dep_org_docx4j_dml.CTPositiveFixedAngle): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositiveFixedAngle>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}hue in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorHue(value)). */
export function createCTStyleColorHue(value: Dep_org_docx4j_dml.CTPositiveFixedAngle): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositiveFixedAngle>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}hueMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationHueMod(value)). */
export function createCTColorStyleVariationHueMod(value: Dep_org_docx4j_dml.CTPositivePercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositivePercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}hueMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorHueMod(value)). */
export function createCTStyleColorHueMod(value: Dep_org_docx4j_dml.CTPositivePercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositivePercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}hueOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationHueOff(value)). */
export function createCTColorStyleVariationHueOff(value: Dep_org_docx4j_dml.CTAngle): M.TypedNamedValue<Dep_org_docx4j_dml.CTAngle>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}hueOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorHueOff(value)). */
export function createCTStyleColorHueOff(value: Dep_org_docx4j_dml.CTAngle): M.TypedNamedValue<Dep_org_docx4j_dml.CTAngle>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}inv in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationInv(value)). */
export function createCTColorStyleVariationInv(value: Dep_org_docx4j_dml.CTInverseTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTInverseTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}inv in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorInv(value)). */
export function createCTStyleColorInv(value: Dep_org_docx4j_dml.CTInverseTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTInverseTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}invGamma in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationInvGamma(value)). */
export function createCTColorStyleVariationInvGamma(value: Dep_org_docx4j_dml.CTInverseGammaTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTInverseGammaTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}invGamma in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorInvGamma(value)). */
export function createCTStyleColorInvGamma(value: Dep_org_docx4j_dml.CTInverseGammaTransform): M.TypedNamedValue<Dep_org_docx4j_dml.CTInverseGammaTransform>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}lum in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationLum(value)). */
export function createCTColorStyleVariationLum(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}lum in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorLum(value)). */
export function createCTStyleColorLum(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}lumMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationLumMod(value)). */
export function createCTColorStyleVariationLumMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}lumMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorLumMod(value)). */
export function createCTStyleColorLumMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}lumOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationLumOff(value)). */
export function createCTColorStyleVariationLumOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}lumOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorLumOff(value)). */
export function createCTStyleColorLumOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}red in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationRed(value)). */
export function createCTColorStyleVariationRed(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}red in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorRed(value)). */
export function createCTStyleColorRed(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}redMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationRedMod(value)). */
export function createCTColorStyleVariationRedMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}redMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorRedMod(value)). */
export function createCTStyleColorRedMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}redOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationRedOff(value)). */
export function createCTColorStyleVariationRedOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}redOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorRedOff(value)). */
export function createCTStyleColorRedOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}sat in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationSat(value)). */
export function createCTColorStyleVariationSat(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}sat in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorSat(value)). */
export function createCTStyleColorSat(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}satMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationSatMod(value)). */
export function createCTColorStyleVariationSatMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}satMod in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorSatMod(value)). */
export function createCTStyleColorSatMod(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}satOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationSatOff(value)). */
export function createCTColorStyleVariationSatOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}satOff in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorSatOff(value)). */
export function createCTStyleColorSatOff(value: Dep_org_docx4j_dml.CTPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}shade in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationShade(value)). */
export function createCTColorStyleVariationShade(value: Dep_org_docx4j_dml.CTPositiveFixedPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositiveFixedPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}shade in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorShade(value)). */
export function createCTStyleColorShade(value: Dep_org_docx4j_dml.CTPositiveFixedPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositiveFixedPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}tint in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTColorStyleVariation (docx4j ObjectFactory.createCTColorStyleVariationTint(value)). */
export function createCTColorStyleVariationTint(value: Dep_org_docx4j_dml.CTPositiveFixedPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositiveFixedPercentage>;
/** The element {http://schemas.openxmlformats.org/drawingml/2006/main}tint in the scope of org_docx4j_com_microsoft_schemas_office_drawing_x2012_chartStyle.CTStyleColor (docx4j ObjectFactory.createCTStyleColorTint(value)). */
export function createCTStyleColorTint(value: Dep_org_docx4j_dml.CTPositiveFixedPercentage): M.TypedNamedValue<Dep_org_docx4j_dml.CTPositiveFixedPercentage>;
