// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2012_main]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2012/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function backgroundPr(value) { return __element(__ns0, 'backgroundPr', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_main.CTBackgroundPr'); }
export function nonVisualGroupProps(value) { return __element(__ns0, 'nonVisualGroupProps', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_main.CTNonVisualGroupProps'); }
export function objectPr(value) { return __element(__ns0, 'objectPr', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_main.CTObjectPr'); }
export function signatureLine(value) { return __element(__ns0, 'signatureLine', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2012_main.CTSignatureLine'); }
