// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_w14]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/word/2010/wordml';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTBevel(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTBevel' }, init); }
export function createCTCamera(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTCamera' }, init); }
export function createCTColor(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTColor' }, init); }
export function createCTDefaultImageDpi(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTDefaultImageDpi' }, init); }
export function createCTFillTextEffect(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTFillTextEffect' }, init); }
export function createCTGlow(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTGlow' }, init); }
export function createCTGradientFillProperties(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTGradientFillProperties' }, init); }
export function createCTGradientStop(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTGradientStop' }, init); }
export function createCTGradientStopList(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTGradientStopList' }, init); }
export function createCTLigatures(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTLigatures' }, init); }
export function createCTLightRig(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTLightRig' }, init); }
export function createCTLineJoinMiterProperties(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTLineJoinMiterProperties' }, init); }
export function createCTLinearShadeProperties(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTLinearShadeProperties' }, init); }
export function createCTLongHexNumber(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTLongHexNumber' }, init); }
export function createCTNumForm(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTNumForm' }, init); }
export function createCTNumSpacing(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTNumSpacing' }, init); }
export function createCTOnOff(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTOnOff' }, init); }
export function createCTPathShadeProperties(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTPathShadeProperties' }, init); }
export function createCTPercentage(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTPercentage' }, init); }
export function createCTPositiveFixedPercentage(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTPositiveFixedPercentage' }, init); }
export function createCTPositivePercentage(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTPositivePercentage' }, init); }
export function createCTPresetLineDashProperties(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTPresetLineDashProperties' }, init); }
export function createCTProps3D(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTProps3D' }, init); }
export function createCTReflection(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTReflection' }, init); }
export function createCTRelativeRect(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTRelativeRect' }, init); }
export function createCTSRgbColor(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTSRgbColor' }, init); }
export function createCTScene3D(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTScene3D' }, init); }
export function createCTSchemeColor(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTSchemeColor' }, init); }
export function createCTSdtCheckbox(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTSdtCheckbox' }, init); }
export function createCTSdtCheckboxSymbol(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTSdtCheckboxSymbol' }, init); }
export function createCTShadow(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTShadow' }, init); }
export function createCTSolidColorFillProperties(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTSolidColorFillProperties' }, init); }
export function createCTSphereCoords(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTSphereCoords' }, init); }
export function createCTStyleSet(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTStyleSet' }, init); }
export function createCTStylisticSets(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTStylisticSets' }, init); }
export function createCTTextOutlineEffect(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTTextOutlineEffect' }, init); }
export function createCTWordContentPart(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTWordContentPart' }, init); }
export function createCTWordContentPartNonVisual(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w14.CTWordContentPartNonVisual' }, init); }
export function createCTSRgbColorAlpha(value) { return __element(__ns0, 'alpha', value, 'org_docx4j_w14.CTPositiveFixedPercentage'); }
export function createCTSchemeColorAlpha(value) { return __element(__ns0, 'alpha', value, 'org_docx4j_w14.CTPositiveFixedPercentage'); }
export function createCheckboxElement(value) { return __element(__ns0, 'checkbox', value, 'org_docx4j_w14.CTSdtCheckbox'); }
export function createConflictModeElement(value) { return __element(__ns0, 'conflictMode', value, 'org_docx4j_w14.CTOnOff'); }
export function createContentPartElement(value) { return __element(__ns0, 'contentPart', value, 'org_docx4j_w14.CTWordContentPart'); }
export function createCustomXmlConflictDelRangeEndElement(value) { return __element(__ns0, 'customXmlConflictDelRangeEnd', value, 'org_docx4j_wml.CTMarkup'); }
export function createCustomXmlConflictDelRangeStartElement(value) { return __element(__ns0, 'customXmlConflictDelRangeStart', value, 'org_docx4j_wml.CTTrackChange'); }
export function createCustomXmlConflictInsRangeEndElement(value) { return __element(__ns0, 'customXmlConflictInsRangeEnd', value, 'org_docx4j_wml.CTMarkup'); }
export function createCustomXmlConflictInsRangeStartElement(value) { return __element(__ns0, 'customXmlConflictInsRangeStart', value, 'org_docx4j_wml.CTTrackChange'); }
export function createDefaultImageDpiElement(value) { return __element(__ns0, 'defaultImageDpi', value, 'org_docx4j_w14.CTDefaultImageDpi'); }
export function createDiscardImageEditingDataElement(value) { return __element(__ns0, 'discardImageEditingData', value, 'org_docx4j_w14.CTOnOff'); }
export function createDocIdElement(value) { return __element(__ns0, 'docId', value, 'org_docx4j_w14.CTLongHexNumber'); }
export function createEntityPickerElement(value) { return __element(__ns0, 'entityPicker', value, 'org_docx4j_wml.CTEmpty'); }
export function createCTSRgbColorHueMod(value) { return __element(__ns0, 'hueMod', value, 'org_docx4j_w14.CTPositivePercentage'); }
export function createCTSchemeColorHueMod(value) { return __element(__ns0, 'hueMod', value, 'org_docx4j_w14.CTPositivePercentage'); }
export function createCTSRgbColorLum(value) { return __element(__ns0, 'lum', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSchemeColorLum(value) { return __element(__ns0, 'lum', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSRgbColorLumMod(value) { return __element(__ns0, 'lumMod', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSchemeColorLumMod(value) { return __element(__ns0, 'lumMod', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSRgbColorLumOff(value) { return __element(__ns0, 'lumOff', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSchemeColorLumOff(value) { return __element(__ns0, 'lumOff', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSRgbColorSat(value) { return __element(__ns0, 'sat', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSchemeColorSat(value) { return __element(__ns0, 'sat', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSRgbColorSatMod(value) { return __element(__ns0, 'satMod', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSchemeColorSatMod(value) { return __element(__ns0, 'satMod', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSRgbColorSatOff(value) { return __element(__ns0, 'satOff', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSchemeColorSatOff(value) { return __element(__ns0, 'satOff', value, 'org_docx4j_w14.CTPercentage'); }
export function createCTSRgbColorShade(value) { return __element(__ns0, 'shade', value, 'org_docx4j_w14.CTPositiveFixedPercentage'); }
export function createCTSchemeColorShade(value) { return __element(__ns0, 'shade', value, 'org_docx4j_w14.CTPositiveFixedPercentage'); }
export function createShadowElement(value) { return __element(__ns0, 'shadow', value, 'org_docx4j_w14.CTShadow'); }
export function createCTSRgbColorTint(value) { return __element(__ns0, 'tint', value, 'org_docx4j_w14.CTPositiveFixedPercentage'); }
export function createCTSchemeColorTint(value) { return __element(__ns0, 'tint', value, 'org_docx4j_w14.CTPositiveFixedPercentage'); }
