// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2011_x1_ac]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/spreadsheetml/2011/1/ac';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createListElement(value) { return __element(__ns0, 'list', value); }
