// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_customxml]. Do not edit.
import type * as M from './org_docx4j_customxml.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_customxml.js';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml.js';

/** docx4j ObjectFactory.createSchemaLibrary(): a org_docx4j_customxml.SchemaLibrary with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createSchemaLibrary(init?: Partial<Omit<M.SchemaLibrary, 'TYPE_NAME' | 'PARENT'>>): M.SchemaLibrary;
/** docx4j ObjectFactory.createSchemaLibrarySchema(): a org_docx4j_customxml.SchemaLibrary.Schema with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createSchemaLibrarySchema(init?: Partial<Omit<M.SchemaLibrary.Schema, 'TYPE_NAME' | 'PARENT'>>): M.SchemaLibrary.Schema;
/** The global element {http://schemas.openxmlformats.org/schemaLibrary/2006/main}schemaLibrary (docx4j ObjectFactory.createSchemaLibrary(value)). */
export function createSchemaLibraryElement(value: M.SchemaLibrary): M.TypedNamedValue<M.SchemaLibrary>;
