// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_docProps_variantTypes]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function array(value) { return __element(__ns0, 'array', value, 'org_docx4j_docProps_variantTypes.Array'); }
export function blob(value) { return __element(__ns0, 'blob', value); }
export function bool(value) { return __element(__ns0, 'bool', value); }
export function bstr(value) { return __element(__ns0, 'bstr', value); }
export function cf(value) { return __element(__ns0, 'cf', value, 'org_docx4j_docProps_variantTypes.Cf'); }
export function clsid(value) { return __element(__ns0, 'clsid', value); }
export function cy(value) { return __element(__ns0, 'cy', value); }
export function date(value) { return __element(__ns0, 'date', value); }
export function decimal(value) { return __element(__ns0, 'decimal', value); }
export function empty(value) { return __element(__ns0, 'empty', value, 'org_docx4j_docProps_variantTypes.Empty'); }
export function error(value) { return __element(__ns0, 'error', value); }
export function filetime(value) { return __element(__ns0, 'filetime', value); }
export function i1(value) { return __element(__ns0, 'i1', value); }
export function i2(value) { return __element(__ns0, 'i2', value); }
export function i4(value) { return __element(__ns0, 'i4', value); }
export function i8(value) { return __element(__ns0, 'i8', value); }
export function int(value) { return __element(__ns0, 'int', value); }
export function lpstr(value) { return __element(__ns0, 'lpstr', value); }
export function lpwstr(value) { return __element(__ns0, 'lpwstr', value); }
function _null(value) { return __element(__ns0, 'null', value, 'org_docx4j_docProps_variantTypes.Null'); }
export { _null as null };
export function oblob(value) { return __element(__ns0, 'oblob', value); }
export function ostorage(value) { return __element(__ns0, 'ostorage', value); }
export function ostream(value) { return __element(__ns0, 'ostream', value); }
export function r4(value) { return __element(__ns0, 'r4', value); }
export function r8(value) { return __element(__ns0, 'r8', value); }
export function storage(value) { return __element(__ns0, 'storage', value); }
export function stream(value) { return __element(__ns0, 'stream', value); }
export function ui1(value) { return __element(__ns0, 'ui1', value); }
export function ui2(value) { return __element(__ns0, 'ui2', value); }
export function ui4(value) { return __element(__ns0, 'ui4', value); }
export function ui8(value) { return __element(__ns0, 'ui8', value); }
export function uint(value) { return __element(__ns0, 'uint', value); }
export function variant(value) { return __element(__ns0, 'variant', value, 'org_docx4j_docProps_variantTypes.Variant'); }
export function vector(value) { return __element(__ns0, 'vector', value, 'org_docx4j_docProps_variantTypes.Vector'); }
export function vstream(value) { return __element(__ns0, 'vstream', value, 'org_docx4j_docProps_variantTypes.Vstream'); }
