// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_w16cex]. Do not edit.
import type * as M from './org_docx4j_w16cex.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_w16cex.js';
import type * as Dep_org_docx4j_w16 from './org_docx4j_w16.js';

/** docx4j ObjectFactory.createCTCommentExtensible(): a org_docx4j_w16cex.CTCommentExtensible with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCommentExtensible(init?: Partial<Omit<M.CTCommentExtensible, 'TYPE_NAME' | 'PARENT'>>): M.CTCommentExtensible;
/** docx4j ObjectFactory.createCTCommentsExtensible(): a org_docx4j_w16cex.CTCommentsExtensible with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCommentsExtensible(init?: Partial<Omit<M.CTCommentsExtensible, 'TYPE_NAME' | 'PARENT'>>): M.CTCommentsExtensible;
/** The global element {http://schemas.microsoft.com/office/word/2018/wordml/cex}commentsExtensible (docx4j ObjectFactory.createCommentsExtensible(value)). */
export function createCommentsExtensibleElement(value: M.CTCommentsExtensible): M.TypedNamedValue<M.CTCommentsExtensible>;
