// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_math]. Do not edit.
import type * as M from './org_docx4j_math.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_math.js';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml.js';
import type * as Dep_org_docx4j_sharedtypes from './org_docx4j_sharedtypes.js';
import type * as Dep_org_docx4j_w15symex from './org_docx4j_w15symex.js';
import type * as Dep_org_docx4j_mce from './org_docx4j_mce.js';

/** docx4j ObjectFactory.createCTAcc(): a org_docx4j_math.CTAcc with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTAcc(init?: Partial<Omit<M.CTAcc, 'TYPE_NAME' | 'PARENT'>>): M.CTAcc;
/** docx4j ObjectFactory.createCTAccPr(): a org_docx4j_math.CTAccPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTAccPr(init?: Partial<Omit<M.CTAccPr, 'TYPE_NAME' | 'PARENT'>>): M.CTAccPr;
/** docx4j ObjectFactory.createCTBar(): a org_docx4j_math.CTBar with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBar(init?: Partial<Omit<M.CTBar, 'TYPE_NAME' | 'PARENT'>>): M.CTBar;
/** docx4j ObjectFactory.createCTBarPr(): a org_docx4j_math.CTBarPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBarPr(init?: Partial<Omit<M.CTBarPr, 'TYPE_NAME' | 'PARENT'>>): M.CTBarPr;
/** docx4j ObjectFactory.createCTBorderBox(): a org_docx4j_math.CTBorderBox with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBorderBox(init?: Partial<Omit<M.CTBorderBox, 'TYPE_NAME' | 'PARENT'>>): M.CTBorderBox;
/** docx4j ObjectFactory.createCTBorderBoxPr(): a org_docx4j_math.CTBorderBoxPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBorderBoxPr(init?: Partial<Omit<M.CTBorderBoxPr, 'TYPE_NAME' | 'PARENT'>>): M.CTBorderBoxPr;
/** docx4j ObjectFactory.createCTBox(): a org_docx4j_math.CTBox with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBox(init?: Partial<Omit<M.CTBox, 'TYPE_NAME' | 'PARENT'>>): M.CTBox;
/** docx4j ObjectFactory.createCTBoxPr(): a org_docx4j_math.CTBoxPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBoxPr(init?: Partial<Omit<M.CTBoxPr, 'TYPE_NAME' | 'PARENT'>>): M.CTBoxPr;
/** docx4j ObjectFactory.createCTBreakBin(): a org_docx4j_math.CTBreakBin with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBreakBin(init?: Partial<Omit<M.CTBreakBin, 'TYPE_NAME' | 'PARENT'>>): M.CTBreakBin;
/** docx4j ObjectFactory.createCTBreakBinSub(): a org_docx4j_math.CTBreakBinSub with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBreakBinSub(init?: Partial<Omit<M.CTBreakBinSub, 'TYPE_NAME' | 'PARENT'>>): M.CTBreakBinSub;
/** docx4j ObjectFactory.createCTChar(): a org_docx4j_math.CTChar with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTChar(init?: Partial<Omit<M.CTChar, 'TYPE_NAME' | 'PARENT'>>): M.CTChar;
/** docx4j ObjectFactory.createCTCtrlPr(): a org_docx4j_math.CTCtrlPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCtrlPr(init?: Partial<Omit<M.CTCtrlPr, 'TYPE_NAME' | 'PARENT'>>): M.CTCtrlPr;
/** docx4j ObjectFactory.createCTD(): a org_docx4j_math.CTD with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTD(init?: Partial<Omit<M.CTD, 'TYPE_NAME' | 'PARENT'>>): M.CTD;
/** docx4j ObjectFactory.createCTDPr(): a org_docx4j_math.CTDPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDPr(init?: Partial<Omit<M.CTDPr, 'TYPE_NAME' | 'PARENT'>>): M.CTDPr;
/** docx4j ObjectFactory.createCTEqArr(): a org_docx4j_math.CTEqArr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTEqArr(init?: Partial<Omit<M.CTEqArr, 'TYPE_NAME' | 'PARENT'>>): M.CTEqArr;
/** docx4j ObjectFactory.createCTEqArrPr(): a org_docx4j_math.CTEqArrPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTEqArrPr(init?: Partial<Omit<M.CTEqArrPr, 'TYPE_NAME' | 'PARENT'>>): M.CTEqArrPr;
/** docx4j ObjectFactory.createCTF(): a org_docx4j_math.CTF with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTF(init?: Partial<Omit<M.CTF, 'TYPE_NAME' | 'PARENT'>>): M.CTF;
/** docx4j ObjectFactory.createCTFPr(): a org_docx4j_math.CTFPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFPr(init?: Partial<Omit<M.CTFPr, 'TYPE_NAME' | 'PARENT'>>): M.CTFPr;
/** docx4j ObjectFactory.createCTFType(): a org_docx4j_math.CTFType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFType(init?: Partial<Omit<M.CTFType, 'TYPE_NAME' | 'PARENT'>>): M.CTFType;
/** docx4j ObjectFactory.createCTFunc(): a org_docx4j_math.CTFunc with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFunc(init?: Partial<Omit<M.CTFunc, 'TYPE_NAME' | 'PARENT'>>): M.CTFunc;
/** docx4j ObjectFactory.createCTFuncPr(): a org_docx4j_math.CTFuncPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFuncPr(init?: Partial<Omit<M.CTFuncPr, 'TYPE_NAME' | 'PARENT'>>): M.CTFuncPr;
/** docx4j ObjectFactory.createCTGroupChr(): a org_docx4j_math.CTGroupChr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTGroupChr(init?: Partial<Omit<M.CTGroupChr, 'TYPE_NAME' | 'PARENT'>>): M.CTGroupChr;
/** docx4j ObjectFactory.createCTGroupChrPr(): a org_docx4j_math.CTGroupChrPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTGroupChrPr(init?: Partial<Omit<M.CTGroupChrPr, 'TYPE_NAME' | 'PARENT'>>): M.CTGroupChrPr;
/** docx4j ObjectFactory.createCTInteger2(): a org_docx4j_math.CTInteger2 with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTInteger2(init?: Partial<Omit<M.CTInteger2, 'TYPE_NAME' | 'PARENT'>>): M.CTInteger2;
/** docx4j ObjectFactory.createCTInteger255(): a org_docx4j_math.CTInteger255 with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTInteger255(init?: Partial<Omit<M.CTInteger255, 'TYPE_NAME' | 'PARENT'>>): M.CTInteger255;
/** docx4j ObjectFactory.createCTLimLoc(): a org_docx4j_math.CTLimLoc with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTLimLoc(init?: Partial<Omit<M.CTLimLoc, 'TYPE_NAME' | 'PARENT'>>): M.CTLimLoc;
/** docx4j ObjectFactory.createCTLimLow(): a org_docx4j_math.CTLimLow with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTLimLow(init?: Partial<Omit<M.CTLimLow, 'TYPE_NAME' | 'PARENT'>>): M.CTLimLow;
/** docx4j ObjectFactory.createCTLimLowPr(): a org_docx4j_math.CTLimLowPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTLimLowPr(init?: Partial<Omit<M.CTLimLowPr, 'TYPE_NAME' | 'PARENT'>>): M.CTLimLowPr;
/** docx4j ObjectFactory.createCTLimUpp(): a org_docx4j_math.CTLimUpp with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTLimUpp(init?: Partial<Omit<M.CTLimUpp, 'TYPE_NAME' | 'PARENT'>>): M.CTLimUpp;
/** docx4j ObjectFactory.createCTLimUppPr(): a org_docx4j_math.CTLimUppPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTLimUppPr(init?: Partial<Omit<M.CTLimUppPr, 'TYPE_NAME' | 'PARENT'>>): M.CTLimUppPr;
/** docx4j ObjectFactory.createCTM(): a org_docx4j_math.CTM with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTM(init?: Partial<Omit<M.CTM, 'TYPE_NAME' | 'PARENT'>>): M.CTM;
/** docx4j ObjectFactory.createCTMC(): a org_docx4j_math.CTMC with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTMC(init?: Partial<Omit<M.CTMC, 'TYPE_NAME' | 'PARENT'>>): M.CTMC;
/** docx4j ObjectFactory.createCTMCPr(): a org_docx4j_math.CTMCPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTMCPr(init?: Partial<Omit<M.CTMCPr, 'TYPE_NAME' | 'PARENT'>>): M.CTMCPr;
/** docx4j ObjectFactory.createCTMCS(): a org_docx4j_math.CTMCS with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTMCS(init?: Partial<Omit<M.CTMCS, 'TYPE_NAME' | 'PARENT'>>): M.CTMCS;
/** docx4j ObjectFactory.createCTMPr(): a org_docx4j_math.CTMPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTMPr(init?: Partial<Omit<M.CTMPr, 'TYPE_NAME' | 'PARENT'>>): M.CTMPr;
/** docx4j ObjectFactory.createCTMR(): a org_docx4j_math.CTMR with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTMR(init?: Partial<Omit<M.CTMR, 'TYPE_NAME' | 'PARENT'>>): M.CTMR;
/** docx4j ObjectFactory.createCTManualBreak(): a org_docx4j_math.CTManualBreak with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTManualBreak(init?: Partial<Omit<M.CTManualBreak, 'TYPE_NAME' | 'PARENT'>>): M.CTManualBreak;
/** docx4j ObjectFactory.createCTMathPr(): a org_docx4j_math.CTMathPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTMathPr(init?: Partial<Omit<M.CTMathPr, 'TYPE_NAME' | 'PARENT'>>): M.CTMathPr;
/** docx4j ObjectFactory.createCTNary(): a org_docx4j_math.CTNary with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTNary(init?: Partial<Omit<M.CTNary, 'TYPE_NAME' | 'PARENT'>>): M.CTNary;
/** docx4j ObjectFactory.createCTNaryPr(): a org_docx4j_math.CTNaryPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTNaryPr(init?: Partial<Omit<M.CTNaryPr, 'TYPE_NAME' | 'PARENT'>>): M.CTNaryPr;
/** docx4j ObjectFactory.createCTOMath(): a org_docx4j_math.CTOMath with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOMath(init?: Partial<Omit<M.CTOMath, 'TYPE_NAME' | 'PARENT'>>): M.CTOMath;
/** docx4j ObjectFactory.createCTOMathArg(): a org_docx4j_math.CTOMathArg with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOMathArg(init?: Partial<Omit<M.CTOMathArg, 'TYPE_NAME' | 'PARENT'>>): M.CTOMathArg;
/** docx4j ObjectFactory.createCTOMathArgPr(): a org_docx4j_math.CTOMathArgPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOMathArgPr(init?: Partial<Omit<M.CTOMathArgPr, 'TYPE_NAME' | 'PARENT'>>): M.CTOMathArgPr;
/** docx4j ObjectFactory.createCTOMathJc(): a org_docx4j_math.CTOMathJc with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOMathJc(init?: Partial<Omit<M.CTOMathJc, 'TYPE_NAME' | 'PARENT'>>): M.CTOMathJc;
/** docx4j ObjectFactory.createCTOMathPara(): a org_docx4j_math.CTOMathPara with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOMathPara(init?: Partial<Omit<M.CTOMathPara, 'TYPE_NAME' | 'PARENT'>>): M.CTOMathPara;
/** docx4j ObjectFactory.createCTOMathParaPr(): a org_docx4j_math.CTOMathParaPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOMathParaPr(init?: Partial<Omit<M.CTOMathParaPr, 'TYPE_NAME' | 'PARENT'>>): M.CTOMathParaPr;
/** docx4j ObjectFactory.createCTOnOff(): a org_docx4j_math.CTOnOff with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOnOff(init?: Partial<Omit<M.CTOnOff, 'TYPE_NAME' | 'PARENT'>>): M.CTOnOff;
/** docx4j ObjectFactory.createCTPhant(): a org_docx4j_math.CTPhant with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPhant(init?: Partial<Omit<M.CTPhant, 'TYPE_NAME' | 'PARENT'>>): M.CTPhant;
/** docx4j ObjectFactory.createCTPhantPr(): a org_docx4j_math.CTPhantPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPhantPr(init?: Partial<Omit<M.CTPhantPr, 'TYPE_NAME' | 'PARENT'>>): M.CTPhantPr;
/** docx4j ObjectFactory.createCTR(): a org_docx4j_math.CTR with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTR(init?: Partial<Omit<M.CTR, 'TYPE_NAME' | 'PARENT'>>): M.CTR;
/** docx4j ObjectFactory.createCTRPR(): a org_docx4j_math.CTRPR with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTRPR(init?: Partial<Omit<M.CTRPR, 'TYPE_NAME' | 'PARENT'>>): M.CTRPR;
/** docx4j ObjectFactory.createCTRad(): a org_docx4j_math.CTRad with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTRad(init?: Partial<Omit<M.CTRad, 'TYPE_NAME' | 'PARENT'>>): M.CTRad;
/** docx4j ObjectFactory.createCTRadPr(): a org_docx4j_math.CTRadPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTRadPr(init?: Partial<Omit<M.CTRadPr, 'TYPE_NAME' | 'PARENT'>>): M.CTRadPr;
/** docx4j ObjectFactory.createCTSPre(): a org_docx4j_math.CTSPre with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSPre(init?: Partial<Omit<M.CTSPre, 'TYPE_NAME' | 'PARENT'>>): M.CTSPre;
/** docx4j ObjectFactory.createCTSPrePr(): a org_docx4j_math.CTSPrePr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSPrePr(init?: Partial<Omit<M.CTSPrePr, 'TYPE_NAME' | 'PARENT'>>): M.CTSPrePr;
/** docx4j ObjectFactory.createCTSSub(): a org_docx4j_math.CTSSub with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSSub(init?: Partial<Omit<M.CTSSub, 'TYPE_NAME' | 'PARENT'>>): M.CTSSub;
/** docx4j ObjectFactory.createCTSSubPr(): a org_docx4j_math.CTSSubPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSSubPr(init?: Partial<Omit<M.CTSSubPr, 'TYPE_NAME' | 'PARENT'>>): M.CTSSubPr;
/** docx4j ObjectFactory.createCTSSubSup(): a org_docx4j_math.CTSSubSup with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSSubSup(init?: Partial<Omit<M.CTSSubSup, 'TYPE_NAME' | 'PARENT'>>): M.CTSSubSup;
/** docx4j ObjectFactory.createCTSSubSupPr(): a org_docx4j_math.CTSSubSupPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSSubSupPr(init?: Partial<Omit<M.CTSSubSupPr, 'TYPE_NAME' | 'PARENT'>>): M.CTSSubSupPr;
/** docx4j ObjectFactory.createCTSSup(): a org_docx4j_math.CTSSup with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSSup(init?: Partial<Omit<M.CTSSup, 'TYPE_NAME' | 'PARENT'>>): M.CTSSup;
/** docx4j ObjectFactory.createCTSSupPr(): a org_docx4j_math.CTSSupPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSSupPr(init?: Partial<Omit<M.CTSSupPr, 'TYPE_NAME' | 'PARENT'>>): M.CTSSupPr;
/** docx4j ObjectFactory.createCTScript(): a org_docx4j_math.CTScript with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTScript(init?: Partial<Omit<M.CTScript, 'TYPE_NAME' | 'PARENT'>>): M.CTScript;
/** docx4j ObjectFactory.createCTShp(): a org_docx4j_math.CTShp with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTShp(init?: Partial<Omit<M.CTShp, 'TYPE_NAME' | 'PARENT'>>): M.CTShp;
/** docx4j ObjectFactory.createCTSpacingRule(): a org_docx4j_math.CTSpacingRule with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSpacingRule(init?: Partial<Omit<M.CTSpacingRule, 'TYPE_NAME' | 'PARENT'>>): M.CTSpacingRule;
/** docx4j ObjectFactory.createCTString(): a org_docx4j_math.CTString with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTString(init?: Partial<Omit<M.CTString, 'TYPE_NAME' | 'PARENT'>>): M.CTString;
/** docx4j ObjectFactory.createCTStyle(): a org_docx4j_math.CTStyle with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTStyle(init?: Partial<Omit<M.CTStyle, 'TYPE_NAME' | 'PARENT'>>): M.CTStyle;
/** docx4j ObjectFactory.createCTText(): a org_docx4j_math.CTText with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTText(init?: Partial<Omit<M.CTText, 'TYPE_NAME' | 'PARENT'>>): M.CTText;
/** docx4j ObjectFactory.createCTTopBot(): a org_docx4j_math.CTTopBot with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTopBot(init?: Partial<Omit<M.CTTopBot, 'TYPE_NAME' | 'PARENT'>>): M.CTTopBot;
/** docx4j ObjectFactory.createCTTwipsMeasure(): a org_docx4j_math.CTTwipsMeasure with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTwipsMeasure(init?: Partial<Omit<M.CTTwipsMeasure, 'TYPE_NAME' | 'PARENT'>>): M.CTTwipsMeasure;
/** docx4j ObjectFactory.createCTUnSignedInteger(): a org_docx4j_math.CTUnSignedInteger with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTUnSignedInteger(init?: Partial<Omit<M.CTUnSignedInteger, 'TYPE_NAME' | 'PARENT'>>): M.CTUnSignedInteger;
/** docx4j ObjectFactory.createCTXAlign(): a org_docx4j_math.CTXAlign with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTXAlign(init?: Partial<Omit<M.CTXAlign, 'TYPE_NAME' | 'PARENT'>>): M.CTXAlign;
/** docx4j ObjectFactory.createCTYAlign(): a org_docx4j_math.CTYAlign with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTYAlign(init?: Partial<Omit<M.CTYAlign, 'TYPE_NAME' | 'PARENT'>>): M.CTYAlign;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}acc in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathAcc(value)). */
export function createCTOMathAcc(value: M.CTAcc): M.TypedNamedValue<M.CTAcc>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}acc in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgAcc(value)). */
export function createCTOMathArgAcc(value: M.CTAcc): M.TypedNamedValue<M.CTAcc>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}bar in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathBar(value)). */
export function createCTOMathBar(value: M.CTBar): M.TypedNamedValue<M.CTBar>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}bar in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgBar(value)). */
export function createCTOMathArgBar(value: M.CTBar): M.TypedNamedValue<M.CTBar>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}borderBox in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathBorderBox(value)). */
export function createCTOMathBorderBox(value: M.CTBorderBox): M.TypedNamedValue<M.CTBorderBox>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}borderBox in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgBorderBox(value)). */
export function createCTOMathArgBorderBox(value: M.CTBorderBox): M.TypedNamedValue<M.CTBorderBox>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}box in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathBox(value)). */
export function createCTOMathBox(value: M.CTBox): M.TypedNamedValue<M.CTBox>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}box in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgBox(value)). */
export function createCTOMathArgBox(value: M.CTBox): M.TypedNamedValue<M.CTBox>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}d in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathD(value)). */
export function createCTOMathD(value: M.CTD): M.TypedNamedValue<M.CTD>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}d in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgD(value)). */
export function createCTOMathArgD(value: M.CTD): M.TypedNamedValue<M.CTD>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}eqArr in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathEqArr(value)). */
export function createCTOMathEqArr(value: M.CTEqArr): M.TypedNamedValue<M.CTEqArr>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}eqArr in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgEqArr(value)). */
export function createCTOMathArgEqArr(value: M.CTEqArr): M.TypedNamedValue<M.CTEqArr>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}f in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathF(value)). */
export function createCTOMathF(value: M.CTF): M.TypedNamedValue<M.CTF>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}f in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgF(value)). */
export function createCTOMathArgF(value: M.CTF): M.TypedNamedValue<M.CTF>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}func in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathFunc(value)). */
export function createCTOMathFunc(value: M.CTFunc): M.TypedNamedValue<M.CTFunc>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}func in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgFunc(value)). */
export function createCTOMathArgFunc(value: M.CTFunc): M.TypedNamedValue<M.CTFunc>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}groupChr in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathGroupChr(value)). */
export function createCTOMathGroupChr(value: M.CTGroupChr): M.TypedNamedValue<M.CTGroupChr>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}groupChr in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgGroupChr(value)). */
export function createCTOMathArgGroupChr(value: M.CTGroupChr): M.TypedNamedValue<M.CTGroupChr>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}limLow in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathLimLow(value)). */
export function createCTOMathLimLow(value: M.CTLimLow): M.TypedNamedValue<M.CTLimLow>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}limLow in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgLimLow(value)). */
export function createCTOMathArgLimLow(value: M.CTLimLow): M.TypedNamedValue<M.CTLimLow>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}limUpp in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathLimUpp(value)). */
export function createCTOMathLimUpp(value: M.CTLimUpp): M.TypedNamedValue<M.CTLimUpp>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}limUpp in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgLimUpp(value)). */
export function createCTOMathArgLimUpp(value: M.CTLimUpp): M.TypedNamedValue<M.CTLimUpp>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}m in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathM(value)). */
export function createCTOMathM(value: M.CTM): M.TypedNamedValue<M.CTM>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}m in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgM(value)). */
export function createCTOMathArgM(value: M.CTM): M.TypedNamedValue<M.CTM>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/math}mathPr (docx4j ObjectFactory.createMathPr(value)). */
export function createMathPrElement(value: M.CTMathPr): M.TypedNamedValue<M.CTMathPr>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}nary in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathNary(value)). */
export function createCTOMathNary(value: M.CTNary): M.TypedNamedValue<M.CTNary>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}nary in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgNary(value)). */
export function createCTOMathArgNary(value: M.CTNary): M.TypedNamedValue<M.CTNary>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/math}oMath (docx4j ObjectFactory.createOMath(value)). */
export function createOMathElement(value: M.CTOMath): M.TypedNamedValue<M.CTOMath>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/math}oMathPara (docx4j ObjectFactory.createOMathPara(value)). */
export function createOMathParaElement(value: M.CTOMathPara): M.TypedNamedValue<M.CTOMathPara>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}phant in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathPhant(value)). */
export function createCTOMathPhant(value: M.CTPhant): M.TypedNamedValue<M.CTPhant>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}phant in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgPhant(value)). */
export function createCTOMathArgPhant(value: M.CTPhant): M.TypedNamedValue<M.CTPhant>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}r in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathR(value)). */
export function createCTOMathR(value: M.CTR): M.TypedNamedValue<M.CTR>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}r in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgR(value)). */
export function createCTOMathArgR(value: M.CTR): M.TypedNamedValue<M.CTR>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}rPr in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRRPrMath(value)). */
export function createCTRRPrMath(value: M.CTRPR): M.TypedNamedValue<M.CTRPR>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}rad in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathRad(value)). */
export function createCTOMathRad(value: M.CTRad): M.TypedNamedValue<M.CTRad>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}rad in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgRad(value)). */
export function createCTOMathArgRad(value: M.CTRad): M.TypedNamedValue<M.CTRad>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}sPre in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathSPre(value)). */
export function createCTOMathSPre(value: M.CTSPre): M.TypedNamedValue<M.CTSPre>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}sPre in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgSPre(value)). */
export function createCTOMathArgSPre(value: M.CTSPre): M.TypedNamedValue<M.CTSPre>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}sSub in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathSSub(value)). */
export function createCTOMathSSub(value: M.CTSSub): M.TypedNamedValue<M.CTSSub>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}sSub in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgSSub(value)). */
export function createCTOMathArgSSub(value: M.CTSSub): M.TypedNamedValue<M.CTSSub>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}sSubSup in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathSSubSup(value)). */
export function createCTOMathSSubSup(value: M.CTSSubSup): M.TypedNamedValue<M.CTSSubSup>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}sSubSup in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgSSubSup(value)). */
export function createCTOMathArgSSubSup(value: M.CTSSubSup): M.TypedNamedValue<M.CTSSubSup>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}sSup in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathSSup(value)). */
export function createCTOMathSSup(value: M.CTSSup): M.TypedNamedValue<M.CTSSup>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}sSup in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgSSup(value)). */
export function createCTOMathArgSSup(value: M.CTSSup): M.TypedNamedValue<M.CTSSup>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/math}t in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRTMath(value)). */
export function createCTRTMath(value: M.CTText): M.TypedNamedValue<M.CTText>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}annotationRef in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRAnnotationRef(value)). */
export function createCTRAnnotationRef(value: Dep_org_docx4j_wml.R.AnnotationRef): M.TypedNamedValue<Dep_org_docx4j_wml.R.AnnotationRef>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bookmarkEnd in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathBookmarkEnd(value)). */
export function createCTOMathBookmarkEnd(value: Dep_org_docx4j_wml.CTMarkupRange): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkupRange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bookmarkEnd in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgBookmarkEnd(value)). */
export function createCTOMathArgBookmarkEnd(value: Dep_org_docx4j_wml.CTMarkupRange): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkupRange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bookmarkStart in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathBookmarkStart(value)). */
export function createCTOMathBookmarkStart(value: Dep_org_docx4j_wml.CTBookmark): M.TypedNamedValue<Dep_org_docx4j_wml.CTBookmark>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}bookmarkStart in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgBookmarkStart(value)). */
export function createCTOMathArgBookmarkStart(value: Dep_org_docx4j_wml.CTBookmark): M.TypedNamedValue<Dep_org_docx4j_wml.CTBookmark>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}commentReference in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRCommentReference(value)). */
export function createCTRCommentReference(value: Dep_org_docx4j_wml.R.CommentReference): M.TypedNamedValue<Dep_org_docx4j_wml.R.CommentReference>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}continuationSeparator in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRContinuationSeparator(value)). */
export function createCTRContinuationSeparator(value: Dep_org_docx4j_wml.R.ContinuationSeparator): M.TypedNamedValue<Dep_org_docx4j_wml.R.ContinuationSeparator>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}cr in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRCr(value)). */
export function createCTRCr(value: Dep_org_docx4j_wml.R.Cr): M.TypedNamedValue<Dep_org_docx4j_wml.R.Cr>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlDelRangeEnd in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathCustomXmlDelRangeEnd(value)). */
export function createCTOMathCustomXmlDelRangeEnd(value: Dep_org_docx4j_wml.CTMarkup): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlDelRangeEnd in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgCustomXmlDelRangeEnd(value)). */
export function createCTOMathArgCustomXmlDelRangeEnd(value: Dep_org_docx4j_wml.CTMarkup): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlDelRangeStart in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathCustomXmlDelRangeStart(value)). */
export function createCTOMathCustomXmlDelRangeStart(value: Dep_org_docx4j_wml.CTTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlDelRangeStart in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgCustomXmlDelRangeStart(value)). */
export function createCTOMathArgCustomXmlDelRangeStart(value: Dep_org_docx4j_wml.CTTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlInsRangeEnd in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathCustomXmlInsRangeEnd(value)). */
export function createCTOMathCustomXmlInsRangeEnd(value: Dep_org_docx4j_wml.CTMarkup): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlInsRangeEnd in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgCustomXmlInsRangeEnd(value)). */
export function createCTOMathArgCustomXmlInsRangeEnd(value: Dep_org_docx4j_wml.CTMarkup): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlInsRangeStart in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathCustomXmlInsRangeStart(value)). */
export function createCTOMathCustomXmlInsRangeStart(value: Dep_org_docx4j_wml.CTTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlInsRangeStart in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgCustomXmlInsRangeStart(value)). */
export function createCTOMathArgCustomXmlInsRangeStart(value: Dep_org_docx4j_wml.CTTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlMoveFromRangeEnd in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathCustomXmlMoveFromRangeEnd(value)). */
export function createCTOMathCustomXmlMoveFromRangeEnd(value: Dep_org_docx4j_wml.CTMarkup): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlMoveFromRangeEnd in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgCustomXmlMoveFromRangeEnd(value)). */
export function createCTOMathArgCustomXmlMoveFromRangeEnd(value: Dep_org_docx4j_wml.CTMarkup): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlMoveFromRangeStart in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathCustomXmlMoveFromRangeStart(value)). */
export function createCTOMathCustomXmlMoveFromRangeStart(value: Dep_org_docx4j_wml.CTTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlMoveFromRangeStart in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgCustomXmlMoveFromRangeStart(value)). */
export function createCTOMathArgCustomXmlMoveFromRangeStart(value: Dep_org_docx4j_wml.CTTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlMoveToRangeEnd in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathCustomXmlMoveToRangeEnd(value)). */
export function createCTOMathCustomXmlMoveToRangeEnd(value: Dep_org_docx4j_wml.CTMarkup): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlMoveToRangeEnd in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgCustomXmlMoveToRangeEnd(value)). */
export function createCTOMathArgCustomXmlMoveToRangeEnd(value: Dep_org_docx4j_wml.CTMarkup): M.TypedNamedValue<Dep_org_docx4j_wml.CTMarkup>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlMoveToRangeStart in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathCustomXmlMoveToRangeStart(value)). */
export function createCTOMathCustomXmlMoveToRangeStart(value: Dep_org_docx4j_wml.CTTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}customXmlMoveToRangeStart in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgCustomXmlMoveToRangeStart(value)). */
export function createCTOMathArgCustomXmlMoveToRangeStart(value: Dep_org_docx4j_wml.CTTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}dayLong in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRDayLong(value)). */
export function createCTRDayLong(value: Dep_org_docx4j_wml.R.DayLong): M.TypedNamedValue<Dep_org_docx4j_wml.R.DayLong>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}dayShort in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRDayShort(value)). */
export function createCTRDayShort(value: Dep_org_docx4j_wml.R.DayShort): M.TypedNamedValue<Dep_org_docx4j_wml.R.DayShort>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}del in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRDel(value)). */
export function createCTRDel(value: Dep_org_docx4j_wml.CTMathRunTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTMathRunTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}delInstrText in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRDelInstrText(value)). */
export function createCTRDelInstrText(value: Dep_org_docx4j_wml.Text): M.TypedNamedValue<Dep_org_docx4j_wml.Text>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}drawing in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRDrawing(value)). */
export function createCTRDrawing(value: Dep_org_docx4j_wml.Drawing): M.TypedNamedValue<Dep_org_docx4j_wml.Drawing>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}endnoteRef in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTREndnoteRef(value)). */
export function createCTREndnoteRef(value: Dep_org_docx4j_wml.R.EndnoteRef): M.TypedNamedValue<Dep_org_docx4j_wml.R.EndnoteRef>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}endnoteReference in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTREndnoteReference(value)). */
export function createCTREndnoteReference(value: Dep_org_docx4j_wml.CTFtnEdnRef): M.TypedNamedValue<Dep_org_docx4j_wml.CTFtnEdnRef>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}fldChar in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRFldChar(value)). */
export function createCTRFldChar(value: Dep_org_docx4j_wml.FldChar): M.TypedNamedValue<Dep_org_docx4j_wml.FldChar>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}footnoteRef in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRFootnoteRef(value)). */
export function createCTRFootnoteRef(value: Dep_org_docx4j_wml.R.FootnoteRef): M.TypedNamedValue<Dep_org_docx4j_wml.R.FootnoteRef>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}footnoteReference in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRFootnoteReference(value)). */
export function createCTRFootnoteReference(value: Dep_org_docx4j_wml.CTFtnEdnRef): M.TypedNamedValue<Dep_org_docx4j_wml.CTFtnEdnRef>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}ins in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRIns(value)). */
export function createCTRIns(value: Dep_org_docx4j_wml.CTMathRunTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.CTMathRunTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}instrText in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRInstrText(value)). */
export function createCTRInstrText(value: Dep_org_docx4j_wml.Text): M.TypedNamedValue<Dep_org_docx4j_wml.Text>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}lastRenderedPageBreak in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRLastRenderedPageBreak(value)). */
export function createCTRLastRenderedPageBreak(value: Dep_org_docx4j_wml.R.LastRenderedPageBreak): M.TypedNamedValue<Dep_org_docx4j_wml.R.LastRenderedPageBreak>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}monthLong in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRMonthLong(value)). */
export function createCTRMonthLong(value: Dep_org_docx4j_wml.R.MonthLong): M.TypedNamedValue<Dep_org_docx4j_wml.R.MonthLong>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}monthShort in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRMonthShort(value)). */
export function createCTRMonthShort(value: Dep_org_docx4j_wml.R.MonthShort): M.TypedNamedValue<Dep_org_docx4j_wml.R.MonthShort>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveFrom in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathMoveFrom(value)). */
export function createCTOMathMoveFrom(value: Dep_org_docx4j_wml.RunTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.RunTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveFrom in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgMoveFrom(value)). */
export function createCTOMathArgMoveFrom(value: Dep_org_docx4j_wml.RunTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.RunTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveFromRangeEnd in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathMoveFromRangeEnd(value)). */
export function createCTOMathMoveFromRangeEnd(value: Dep_org_docx4j_wml.CTMoveFromRangeEnd): M.TypedNamedValue<Dep_org_docx4j_wml.CTMoveFromRangeEnd>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveFromRangeEnd in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgMoveFromRangeEnd(value)). */
export function createCTOMathArgMoveFromRangeEnd(value: Dep_org_docx4j_wml.CTMoveFromRangeEnd): M.TypedNamedValue<Dep_org_docx4j_wml.CTMoveFromRangeEnd>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveFromRangeStart in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathMoveFromRangeStart(value)). */
export function createCTOMathMoveFromRangeStart(value: Dep_org_docx4j_wml.CTMoveBookmark): M.TypedNamedValue<Dep_org_docx4j_wml.CTMoveBookmark>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveFromRangeStart in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgMoveFromRangeStart(value)). */
export function createCTOMathArgMoveFromRangeStart(value: Dep_org_docx4j_wml.CTMoveBookmark): M.TypedNamedValue<Dep_org_docx4j_wml.CTMoveBookmark>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveTo in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathMoveTo(value)). */
export function createCTOMathMoveTo(value: Dep_org_docx4j_wml.RunTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.RunTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveTo in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgMoveTo(value)). */
export function createCTOMathArgMoveTo(value: Dep_org_docx4j_wml.RunTrackChange): M.TypedNamedValue<Dep_org_docx4j_wml.RunTrackChange>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveToRangeEnd in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathMoveToRangeEnd(value)). */
export function createCTOMathMoveToRangeEnd(value: Dep_org_docx4j_wml.CTMoveToRangeEnd): M.TypedNamedValue<Dep_org_docx4j_wml.CTMoveToRangeEnd>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveToRangeEnd in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgMoveToRangeEnd(value)). */
export function createCTOMathArgMoveToRangeEnd(value: Dep_org_docx4j_wml.CTMoveToRangeEnd): M.TypedNamedValue<Dep_org_docx4j_wml.CTMoveToRangeEnd>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveToRangeStart in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathMoveToRangeStart(value)). */
export function createCTOMathMoveToRangeStart(value: Dep_org_docx4j_wml.CTMoveBookmark): M.TypedNamedValue<Dep_org_docx4j_wml.CTMoveBookmark>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}moveToRangeStart in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgMoveToRangeStart(value)). */
export function createCTOMathArgMoveToRangeStart(value: Dep_org_docx4j_wml.CTMoveBookmark): M.TypedNamedValue<Dep_org_docx4j_wml.CTMoveBookmark>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}noBreakHyphen in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRNoBreakHyphen(value)). */
export function createCTRNoBreakHyphen(value: Dep_org_docx4j_wml.R.NoBreakHyphen): M.TypedNamedValue<Dep_org_docx4j_wml.R.NoBreakHyphen>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}object in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRObject(value)). */
export function createCTRObject(value: Dep_org_docx4j_wml.CTObject): M.TypedNamedValue<Dep_org_docx4j_wml.CTObject>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}permEnd in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathPermEnd(value)). */
export function createCTOMathPermEnd(value: Dep_org_docx4j_wml.CTPerm): M.TypedNamedValue<Dep_org_docx4j_wml.CTPerm>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}permEnd in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgPermEnd(value)). */
export function createCTOMathArgPermEnd(value: Dep_org_docx4j_wml.CTPerm): M.TypedNamedValue<Dep_org_docx4j_wml.CTPerm>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}permStart in the scope of org_docx4j_math.CTOMath (docx4j ObjectFactory.createCTOMathPermStart(value)). */
export function createCTOMathPermStart(value: Dep_org_docx4j_wml.RangePermissionStart): M.TypedNamedValue<Dep_org_docx4j_wml.RangePermissionStart>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}permStart in the scope of org_docx4j_math.CTOMathArg (docx4j ObjectFactory.createCTOMathArgPermStart(value)). */
export function createCTOMathArgPermStart(value: Dep_org_docx4j_wml.RangePermissionStart): M.TypedNamedValue<Dep_org_docx4j_wml.RangePermissionStart>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}pgNum in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRPgNum(value)). */
export function createCTRPgNum(value: Dep_org_docx4j_wml.R.PgNum): M.TypedNamedValue<Dep_org_docx4j_wml.R.PgNum>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}pict in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRPict(value)). */
export function createCTRPict(value: Dep_org_docx4j_wml.Pict): M.TypedNamedValue<Dep_org_docx4j_wml.Pict>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}ptab in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRPtab(value)). */
export function createCTRPtab(value: Dep_org_docx4j_wml.R.Ptab): M.TypedNamedValue<Dep_org_docx4j_wml.R.Ptab>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}rPr in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRRPr(value)). */
export function createCTRRPr(value: Dep_org_docx4j_wml.RPr): M.TypedNamedValue<Dep_org_docx4j_wml.RPr>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}ruby in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRRuby(value)). */
export function createCTRRuby(value: Dep_org_docx4j_wml.CTRuby): M.TypedNamedValue<Dep_org_docx4j_wml.CTRuby>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}separator in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRSeparator(value)). */
export function createCTRSeparator(value: Dep_org_docx4j_wml.R.Separator): M.TypedNamedValue<Dep_org_docx4j_wml.R.Separator>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}softHyphen in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRSoftHyphen(value)). */
export function createCTRSoftHyphen(value: Dep_org_docx4j_wml.R.SoftHyphen): M.TypedNamedValue<Dep_org_docx4j_wml.R.SoftHyphen>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}sym in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRSym(value)). */
export function createCTRSym(value: Dep_org_docx4j_wml.R.Sym): M.TypedNamedValue<Dep_org_docx4j_wml.R.Sym>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}t in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRT(value)). */
export function createCTRT(value: Dep_org_docx4j_wml.Text): M.TypedNamedValue<Dep_org_docx4j_wml.Text>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}tab in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRTab(value)). */
export function createCTRTab(value: Dep_org_docx4j_wml.R.Tab): M.TypedNamedValue<Dep_org_docx4j_wml.R.Tab>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}yearLong in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRYearLong(value)). */
export function createCTRYearLong(value: Dep_org_docx4j_wml.R.YearLong): M.TypedNamedValue<Dep_org_docx4j_wml.R.YearLong>;
/** The element {http://schemas.openxmlformats.org/wordprocessingml/2006/main}yearShort in the scope of org_docx4j_math.CTR (docx4j ObjectFactory.createCTRYearShort(value)). */
export function createCTRYearShort(value: Dep_org_docx4j_wml.R.YearShort): M.TypedNamedValue<Dep_org_docx4j_wml.R.YearShort>;
