// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2010_main]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_docx4j_w14 from './org_docx4j_w14.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2010_chartDrawing from './org_docx4j_com_microsoft_schemas_office_drawing_x2010_chartDrawing.js';
import type * as Dep_org_xlsx4j_schemas_microsoft_com_office_excel_x2010_spreadsheetDrawing from './org_xlsx4j_schemas_microsoft_com_office_excel_x2010_spreadsheetDrawing.js';
import type * as Dep_org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.js';

/** The element {http://schemas.microsoft.com/office/drawing/2010/main}cameraTool. */
export function cameraTool(value: M.CTCameraTool): M.TypedNamedValue<M.CTCameraTool>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}compatExt. */
export function compatExt(value: M.CTCompatExt): M.TypedNamedValue<M.CTCompatExt>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}contentPart. */
export function contentPart(value: M.CTGvmlContentPart): M.TypedNamedValue<M.CTGvmlContentPart>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}hiddenEffects. */
export function hiddenEffects(value: Dep_org_docx4j_dml.CTEffectProperties): M.TypedNamedValue<Dep_org_docx4j_dml.CTEffectProperties>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}hiddenFill. */
export function hiddenFill(value: Dep_org_docx4j_dml.CTFillProperties): M.TypedNamedValue<Dep_org_docx4j_dml.CTFillProperties>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}hiddenLine. */
export function hiddenLine(value: Dep_org_docx4j_dml.CTLineProperties): M.TypedNamedValue<Dep_org_docx4j_dml.CTLineProperties>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}hiddenScene3d. */
export function hiddenScene3d(value: Dep_org_docx4j_dml.CTScene3D): M.TypedNamedValue<Dep_org_docx4j_dml.CTScene3D>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}hiddenSp3d. */
export function hiddenSp3d(value: Dep_org_docx4j_dml.CTShape3D): M.TypedNamedValue<Dep_org_docx4j_dml.CTShape3D>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}imgProps. */
export function imgProps(value: M.CTPhoto): M.TypedNamedValue<M.CTPhoto>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}isCanvas. */
export function isCanvas(value: M.CTIsGvmlCanvas): M.TypedNamedValue<M.CTIsGvmlCanvas>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}m. */
export function m(value: M.CTTextMath): M.TypedNamedValue<M.CTTextMath>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}shadowObscured. */
export function shadowObscured(value: M.CTShadowObscured): M.TypedNamedValue<M.CTShadowObscured>;
/** The element {http://schemas.microsoft.com/office/drawing/2010/main}useLocalDpi. */
export function useLocalDpi(value: M.CTUseLocalDpi): M.TypedNamedValue<M.CTUseLocalDpi>;
