// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_docProps_core_dc_terms]. Do not edit.
import type * as M from './org_docx4j_docProps_core_dc_terms.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_docProps_core_dc_terms.js';
import type * as Dep_org_docx4j_docProps_core_dc_elements from './org_docx4j_docProps_core_dc_elements.js';
import type * as Dep_org_docx4j_docProps_core from './org_docx4j_docProps_core.js';

/** The element {http://purl.org/dc/terms/}abstract. */
declare function _abstract(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
export { _abstract as abstract };
/** The element {http://purl.org/dc/terms/}accessRights. */
export function accessRights(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}alternative. */
export function alternative(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}audience. */
export function audience(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}available. */
export function available(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}bibliographicCitation. */
export function bibliographicCitation(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}conformsTo. */
export function conformsTo(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}created. */
export function created(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}dateAccepted. */
export function dateAccepted(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}dateCopyrighted. */
export function dateCopyrighted(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}dateSubmitted. */
export function dateSubmitted(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}educationLevel. */
export function educationLevel(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}extent. */
export function extent(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}hasFormat. */
export function hasFormat(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}hasPart. */
export function hasPart(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}hasVersion. */
export function hasVersion(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}isFormatOf. */
export function isFormatOf(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}isPartOf. */
export function isPartOf(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}isReferencedBy. */
export function isReferencedBy(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}isReplacedBy. */
export function isReplacedBy(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}isRequiredBy. */
export function isRequiredBy(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}isVersionOf. */
export function isVersionOf(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}issued. */
export function issued(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}mediator. */
export function mediator(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}medium. */
export function medium(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}modified. */
export function modified(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}references. */
export function references(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}replaces. */
export function replaces(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}requires. */
export function requires(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}spatial. */
export function spatial(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}tableOfContents. */
export function tableOfContents(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}temporal. */
export function temporal(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
/** The element {http://purl.org/dc/terms/}valid. */
export function valid(value: Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral): M.TypedNamedValue<Dep_org_docx4j_docProps_core_dc_elements.SimpleLiteral>;
