// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.js';
import type * as Dep_org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';

/** The element {http://schemas.microsoft.com/office/drawing/2013/main/command}cxnSpMkLst. */
export function cxnSpMkLst(value: M.CTConnectorMonikerList): M.TypedNamedValue<M.CTConnectorMonikerList>;
/** The element {http://schemas.microsoft.com/office/drawing/2013/main/command}graphicFrameMkLst. */
export function graphicFrameMkLst(value: M.CTGraphicFrameMonikerList): M.TypedNamedValue<M.CTGraphicFrameMonikerList>;
/** The element {http://schemas.microsoft.com/office/drawing/2013/main/command}grpMkLst. */
export function grpMkLst(value: M.CTGroupShapeMonikerList): M.TypedNamedValue<M.CTGroupShapeMonikerList>;
/** The element {http://schemas.microsoft.com/office/drawing/2013/main/command}inkMkLst. */
export function inkMkLst(value: M.CTInkMonikerList): M.TypedNamedValue<M.CTInkMonikerList>;
/** The element {http://schemas.microsoft.com/office/drawing/2013/main/command}picMkLst. */
export function picMkLst(value: M.CTPictureMonikerList): M.TypedNamedValue<M.CTPictureMonikerList>;
/** The element {http://schemas.microsoft.com/office/drawing/2013/main/command}spMkLst. */
export function spMkLst(value: M.CTShapeMonikerList): M.TypedNamedValue<M.CTShapeMonikerList>;
