// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_xlsx4j_schemas_microsoft_com_office_excel_2006_main]. Do not edit.
import type * as M from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.js';
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml.js';

/** The element {http://schemas.microsoft.com/office/excel/2006/main}macrosheet. */
export function macrosheet(value: M.CTWorksheet): M.TypedNamedValue<M.CTWorksheet>;
