// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart_ac]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart_ac.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart_ac.js';
import type * as Dep_org_docx4j_dml_chart from './org_docx4j_dml_chart.js';

/** The global element {http://schemas.microsoft.com/office/drawing/2014/chart/ac}multiLvlStrLit (docx4j ObjectFactory.createMultiLvlStrLit(value)). */
export function createMultiLvlStrLitElement(value: Dep_org_docx4j_dml_chart.CTMultiLvlStrData): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTMultiLvlStrData>;
