// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_vml_root]. Do not edit.
import type * as M from './org_docx4j_vml_root.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_vml_root.js';

/** docx4j ObjectFactory.createXml(): a org_docx4j_vml_root.Xml with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createXml(init?: Partial<Omit<M.Xml, 'TYPE_NAME' | 'PARENT'>>): M.Xml;
/** The global element {urn:docx4j:vml:root}xml (docx4j ObjectFactory.createXml(value)). */
export function createXmlElement(value: M.Xml): M.TypedNamedValue<M.Xml>;
