// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2013/main/command';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function cxnSpMkLst(value) { return __element(__ns0, 'cxnSpMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTConnectorMonikerList'); }
export function graphicFrameMkLst(value) { return __element(__ns0, 'graphicFrameMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGraphicFrameMonikerList'); }
export function grpMkLst(value) { return __element(__ns0, 'grpMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTGroupShapeMonikerList'); }
export function inkMkLst(value) { return __element(__ns0, 'inkMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTInkMonikerList'); }
export function picMkLst(value) { return __element(__ns0, 'picMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTPictureMonikerList'); }
export function spMkLst(value) { return __element(__ns0, 'spMkLst', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.CTShapeMonikerList'); }
