// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_vml_wordprocessingDrawing]. Do not edit.
import type * as M from './org_docx4j_vml_wordprocessingDrawing.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_vml_wordprocessingDrawing.js';
import type * as Dep_org_docx4j_vml from './org_docx4j_vml.js';

/** docx4j ObjectFactory.createCTAnchorLock(): a org_docx4j_vml_wordprocessingDrawing.CTAnchorLock with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTAnchorLock(init?: Partial<Omit<M.CTAnchorLock, 'TYPE_NAME' | 'PARENT'>>): M.CTAnchorLock;
/** docx4j ObjectFactory.createCTBorder(): a org_docx4j_vml_wordprocessingDrawing.CTBorder with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTBorder(init?: Partial<Omit<M.CTBorder, 'TYPE_NAME' | 'PARENT'>>): M.CTBorder;
/** docx4j ObjectFactory.createCTWrap(): a org_docx4j_vml_wordprocessingDrawing.CTWrap with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTWrap(init?: Partial<Omit<M.CTWrap, 'TYPE_NAME' | 'PARENT'>>): M.CTWrap;
/** The global element {urn:schemas-microsoft-com:office:word}anchorlock (docx4j ObjectFactory.createAnchorlock(value)). */
export function createAnchorlockElement(value: M.CTAnchorLock): M.TypedNamedValue<M.CTAnchorLock>;
/** The global element {urn:schemas-microsoft-com:office:word}borderbottom (docx4j ObjectFactory.createBorderbottom(value)). */
export function createBorderbottomElement(value: M.CTBorder): M.TypedNamedValue<M.CTBorder>;
/** The global element {urn:schemas-microsoft-com:office:word}borderleft (docx4j ObjectFactory.createBorderleft(value)). */
export function createBorderleftElement(value: M.CTBorder): M.TypedNamedValue<M.CTBorder>;
/** The global element {urn:schemas-microsoft-com:office:word}borderright (docx4j ObjectFactory.createBorderright(value)). */
export function createBorderrightElement(value: M.CTBorder): M.TypedNamedValue<M.CTBorder>;
/** The global element {urn:schemas-microsoft-com:office:word}bordertop (docx4j ObjectFactory.createBordertop(value)). */
export function createBordertopElement(value: M.CTBorder): M.TypedNamedValue<M.CTBorder>;
/** The global element {urn:schemas-microsoft-com:office:word}wrap (docx4j ObjectFactory.createWrap(value)). */
export function createWrapElement(value: M.CTWrap): M.TypedNamedValue<M.CTWrap>;
