// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_docProps_variantTypes]. Do not edit.
import type * as M from './org_docx4j_docProps_variantTypes.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_docProps_variantTypes.js';
import type * as Dep_org_docx4j_docProps_custom from './org_docx4j_docProps_custom.js';
import type * as Dep_org_docx4j_docProps_extended from './org_docx4j_docProps_extended.js';

/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}array. */
export function array(value: M.Array): M.TypedNamedValue<M.Array>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}blob. */
export function blob(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}bool. */
export function bool(value: boolean): M.TypedNamedValue<boolean>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}bstr. */
export function bstr(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}cf. */
export function cf(value: M.Cf): M.TypedNamedValue<M.Cf>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}clsid. */
export function clsid(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}cy. */
export function cy(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}date. */
export function date(value: XmlCalendar): M.TypedNamedValue<XmlCalendar>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}decimal. */
export function decimal(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}empty. */
export function empty(value: M.Empty): M.TypedNamedValue<M.Empty>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}error. */
export function error(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}filetime. */
export function filetime(value: XmlCalendar): M.TypedNamedValue<XmlCalendar>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}i1. */
export function i1(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}i2. */
export function i2(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}i4. */
export function i4(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}i8. */
export function i8(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}int. */
export function int(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}lpstr. */
export function lpstr(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}lpwstr. */
export function lpwstr(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}null. */
declare function _null(value: M.Null): M.TypedNamedValue<M.Null>;
export { _null as null };
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}oblob. */
export function oblob(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ostorage. */
export function ostorage(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ostream. */
export function ostream(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}r4. */
export function r4(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}r8. */
export function r8(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}storage. */
export function storage(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}stream. */
export function stream(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ui1. */
export function ui1(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ui2. */
export function ui2(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ui4. */
export function ui4(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ui8. */
export function ui8(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}uint. */
export function uint(value: number): M.TypedNamedValue<number>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}variant. */
export function variant(value: M.Variant): M.TypedNamedValue<M.Variant>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}vector. */
export function vector(value: M.Vector): M.TypedNamedValue<M.Vector>;
/** The element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}vstream. */
export function vstream(value: M.Vstream): M.TypedNamedValue<M.Vstream>;
