// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_w16cid]. Do not edit.
import type * as M from './org_docx4j_w16cid.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_w16cid.js';

/** docx4j ObjectFactory.createCTCommentId(): a org_docx4j_w16cid.CTCommentId with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCommentId(init?: Partial<Omit<M.CTCommentId, 'TYPE_NAME' | 'PARENT'>>): M.CTCommentId;
/** docx4j ObjectFactory.createCTCommentsIds(): a org_docx4j_w16cid.CTCommentsIds with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCommentsIds(init?: Partial<Omit<M.CTCommentsIds, 'TYPE_NAME' | 'PARENT'>>): M.CTCommentsIds;
/** The global element {http://schemas.microsoft.com/office/word/2016/wordml/cid}commentsIds (docx4j ObjectFactory.createCommentsIds(value)). */
export function createCommentsIdsElement(value: M.CTCommentsIds): M.TypedNamedValue<M.CTCommentsIds>;
