// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_dml_diagram2008]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2008/diagram';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTDataModelExtBlock(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_dml_diagram2008.CTDataModelExtBlock' }, init); }
export function createCTDrawing(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_dml_diagram2008.CTDrawing' }, init); }
export function createCTGroupShape(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_dml_diagram2008.CTGroupShape' }, init); }
export function createCTGroupShapeNonVisual(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_dml_diagram2008.CTGroupShapeNonVisual' }, init); }
export function createCTShape(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_dml_diagram2008.CTShape' }, init); }
export function createCTShapeNonVisual(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_dml_diagram2008.CTShapeNonVisual' }, init); }
export function createDataModelExtElement(value) { return __element(__ns0, 'dataModelExt', value, 'org_docx4j_dml_diagram2008.CTDataModelExtBlock'); }
export function createDrawingElement(value) { return __element(__ns0, 'drawing', value, 'org_docx4j_dml_diagram2008.CTDrawing'); }
