// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x201611_main]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x201611_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x201611_main.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d from './org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.js';

/** docx4j ObjectFactory.createCTPictureAttributionSourceURL(): a org_docx4j_com_microsoft_schemas_office_drawing_x201611_main.CTPictureAttributionSourceURL with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPictureAttributionSourceURL(init?: Partial<Omit<M.CTPictureAttributionSourceURL, 'TYPE_NAME' | 'PARENT'>>): M.CTPictureAttributionSourceURL;
/** The global element {http://schemas.microsoft.com/office/drawing/2016/11/main}picAttrSrcUrl (docx4j ObjectFactory.createPicAttrSrcUrl(value)). */
export function createPicAttrSrcUrlElement(value: M.CTPictureAttributionSourceURL): M.TypedNamedValue<M.CTPictureAttributionSourceURL>;
