// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_word_x2012_wordprocessingDrawing]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTWebVideoPr(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_word_x2012_wordprocessingDrawing.CTWebVideoPr' }, init); }
export function createWebVideoPrElement(value) { return __element(__ns0, 'webVideoPr', value, 'org_docx4j_com_microsoft_schemas_office_word_x2012_wordprocessingDrawing.CTWebVideoPr'); }
