// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_xlsx4j_schemas_microsoft_com_office_excel_2006_main]. Do not edit.
import type * as M from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.js';
import type * as Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.js';
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml.js';

/** docx4j ObjectFactory.createCTRef(): a org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.CTRef with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTRef(init?: Partial<Omit<M.CTRef, 'TYPE_NAME' | 'PARENT'>>): M.CTRef;
/** docx4j ObjectFactory.createCTSqref(): a org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.CTSqref with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSqref(init?: Partial<Omit<M.CTSqref, 'TYPE_NAME' | 'PARENT'>>): M.CTSqref;
/** docx4j ObjectFactory.createCTWorksheet(): a org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.CTWorksheet with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTWorksheet(init?: Partial<Omit<M.CTWorksheet, 'TYPE_NAME' | 'PARENT'>>): M.CTWorksheet;
/** The global element {http://schemas.microsoft.com/office/excel/2006/main}f (docx4j ObjectFactory.createF(value)). */
export function createFElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.microsoft.com/office/excel/2006/main}macrosheet (docx4j ObjectFactory.createMacrosheet(value)). */
export function createMacrosheetElement(value: M.CTWorksheet): M.TypedNamedValue<M.CTWorksheet>;
/** The global element {http://schemas.microsoft.com/office/excel/2006/main}ref (docx4j ObjectFactory.createRef(value)). */
export function createRefElement(value: M.CTRef): M.TypedNamedValue<M.CTRef>;
/** The global element {http://schemas.microsoft.com/office/excel/2006/main}sqref (docx4j ObjectFactory.createSqref(value)). */
export function createSqrefElement(value: M.CTSqref): M.TypedNamedValue<M.CTSqref>;
