// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_revision] as an ES module. Do not edit.
export const org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_revision = {
  name: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_revision',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/spreadsheetml\/2014\/revision',
  typeInfos: [{
      localName: 'CTRevisionPtr',
      typeName: 'CT_RevisionPtr',
      propertyInfos: [{
          name: 'documentId',
          required: true,
          attributeName: {
            localPart: 'documentId'
          },
          type: 'attribute'
        }, {
          name: 'revIDLastSave',
          required: true,
          typeInfo: 'UnsignedLong',
          attributeName: {
            localPart: 'revIDLastSave'
          },
          type: 'attribute'
        }, {
          name: 'uidLastSave',
          typeInfo: 'Token',
          attributeName: {
            localPart: 'uidLastSave',
            namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/spreadsheetml\/2016\/revision10'
          },
          type: 'attribute'
        }, {
          name: 'coauthVersionLast',
          typeInfo: 'UnsignedInt',
          defaultValue: 0,
          attributeName: {
            localPart: 'coauthVersionLast',
            namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/spreadsheetml\/2016\/revision6'
          },
          type: 'attribute'
        }, {
          name: 'coauthVersionMax',
          typeInfo: 'UnsignedInt',
          defaultValue: 0,
          attributeName: {
            localPart: 'coauthVersionMax',
            namespaceURI: 'http:\/\/schemas.microsoft.com\/office\/spreadsheetml\/2016\/revision6'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTRevisionPtr',
      elementName: 'revisionPtr'
    }]
};
