// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_webextensions_taskpanes_2010_11]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_webextensions_taskpanes_2010_11.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_webextensions_taskpanes_2010_11.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_webextensions_webextension_2010_11 from './org_docx4j_com_microsoft_schemas_office_webextensions_webextension_2010_11.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';

/** The element {http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11}taskpanes. */
export function taskpanes(value: M.CTOsfTaskpanes): M.TypedNamedValue<M.CTOsfTaskpanes>;
