// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_thememl_x2012_main]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_thememl_x2012_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_thememl_x2012_main.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';

/** The element {http://schemas.microsoft.com/office/thememl/2012/main}themeFamily. */
export function themeFamily(value: M.CTThemeFamily): M.TypedNamedValue<M.CTThemeFamily>;
