// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_ac]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTAbsolutePath(init) { return Object.assign({ TYPE_NAME: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_ac.CTAbsolutePath' }, init); }
export function createAbsPathElement(value) { return __element(__ns0, 'absPath', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_ac.CTAbsolutePath'); }
