// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/powerpoint/2014/inkAction';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function actions(value) { return __element(__ns0, 'actions', value, 'org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction.CTActions'); }
