// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_webextensions_taskpanes_2010_11]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTOsfTaskpane(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_webextensions_taskpanes_2010_11.CTOsfTaskpane' }, init); }
export function createCTOsfTaskpanes(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_webextensions_taskpanes_2010_11.CTOsfTaskpanes' }, init); }
export function createTaskpanesElement(value) { return __element(__ns0, 'taskpanes', value, 'org_docx4j_com_microsoft_schemas_office_webextensions_taskpanes_2010_11.CTOsfTaskpanes'); }
