// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x201703_main]. Do not edit.
import type * as M from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x201703_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x201703_main.js';

/** docx4j ObjectFactory.createCTTrack(): a org_pptx4j_com_microsoft_schemas_office_powerpoint_x201703_main.CTTrack with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTrack(init?: Partial<Omit<M.CTTrack, 'TYPE_NAME' | 'PARENT'>>): M.CTTrack;
/** docx4j ObjectFactory.createCTTrackList(): a org_pptx4j_com_microsoft_schemas_office_powerpoint_x201703_main.CTTrackList with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTrackList(init?: Partial<Omit<M.CTTrackList, 'TYPE_NAME' | 'PARENT'>>): M.CTTrackList;
/** docx4j ObjectFactory.createCTTracksInfo(): a org_pptx4j_com_microsoft_schemas_office_powerpoint_x201703_main.CTTracksInfo with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTracksInfo(init?: Partial<Omit<M.CTTracksInfo, 'TYPE_NAME' | 'PARENT'>>): M.CTTracksInfo;
/** The global element {http://schemas.microsoft.com/office/powerpoint/2017/3/main}tracksInfo (docx4j ObjectFactory.createTracksInfo(value)). */
export function createTracksInfoElement(value: M.CTTracksInfo): M.TypedNamedValue<M.CTTracksInfo>;
