// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_w16cex]. Do not edit.
import type * as M from './org_docx4j_w16cex.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_w16cex.js';
import type * as Dep_org_docx4j_w16 from './org_docx4j_w16.js';

/** The element {http://schemas.microsoft.com/office/word/2018/wordml/cex}commentsExtensible. */
export function commentsExtensible(value: M.CTCommentsExtensible): M.TypedNamedValue<M.CTCommentsExtensible>;
