// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x201611_main]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x201611_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x201611_main.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d from './org_docx4j_com_microsoft_schemas_office_drawing_x2017_model3d.js';

/** The element {http://schemas.microsoft.com/office/drawing/2016/11/main}picAttrSrcUrl. */
export function picAttrSrcUrl(value: M.CTPictureAttributionSourceURL): M.TypedNamedValue<M.CTPictureAttributionSourceURL>;
