// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_docProps_custom]. Do not edit.
import type * as M from './org_docx4j_docProps_custom.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_docProps_custom.js';
import type * as Dep_org_docx4j_docProps_variantTypes from './org_docx4j_docProps_variantTypes.js';

/** docx4j ObjectFactory.createProperties(): a org_docx4j_docProps_custom.Properties with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createProperties(init?: Partial<Omit<M.Properties, 'TYPE_NAME' | 'PARENT'>>): M.Properties;
/** docx4j ObjectFactory.createPropertiesProperty(): a org_docx4j_docProps_custom.Properties.Property with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createPropertiesProperty(init?: Partial<Omit<M.Properties.Property, 'TYPE_NAME' | 'PARENT'>>): M.Properties.Property;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/custom-properties}Properties (docx4j ObjectFactory.createProperties(value)). */
export function createPropertiesElement(value: M.Properties): M.TypedNamedValue<M.Properties>;
