// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_w15symex]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/word/2015/wordml/symex';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTSymEx(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_w15symex.CTSymEx' }, init); }
export function createSymExElement(value) { return __element(__ns0, 'symEx', value, 'org_docx4j_w15symex.CTSymEx'); }
