// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2014_chart.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_docx4j_dml_chart from './org_docx4j_dml_chart.js';

/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}bubble3D. */
export function bubble3D(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}categoryFilterExceptions. */
export function categoryFilterExceptions(value: M.CTCategoryFilterExceptions): M.TypedNamedValue<M.CTCategoryFilterExceptions>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}dLbl. */
export function dLbl(value: Dep_org_docx4j_dml_chart.CTDLbl): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTDLbl>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}datapointuniqueidmap. */
export function datapointuniqueidmap(value: M.CTChartDataPointUniqueIDMap): M.TypedNamedValue<M.CTChartDataPointUniqueIDMap>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}explosion. */
export function explosion(value: Dep_org_docx4j_dml_chart.CTUnsignedInt): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTUnsignedInt>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}invertIfNegative. */
export function invertIfNegative(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}marker. */
export function marker(value: Dep_org_docx4j_dml_chart.CTMarker): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTMarker>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}pivotOptions16. */
export function pivotOptions16(value: M.CTPivotOptions16): M.TypedNamedValue<M.CTPivotOptions16>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chart}spPr. */
export function spPr(value: Dep_org_docx4j_dml.CTShapeProperties): M.TypedNamedValue<Dep_org_docx4j_dml.CTShapeProperties>;
