// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command]. Do not edit.
import type * as M from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2013_main_command.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command from './org_docx4j_com_microsoft_schemas_office_drawing_x2013_main_command.js';
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml.js';

/** The element {http://schemas.microsoft.com/office/powerpoint/2013/main/command}chgInfo. */
export function chgInfo(value: M.CTChangesInfo): M.TypedNamedValue<M.CTChangesInfo>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2013/main/command}cmAuthorMkLst. */
export function cmAuthorMkLst(value: M.CTCommentAuthorMonikerList): M.TypedNamedValue<M.CTCommentAuthorMonikerList>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2013/main/command}cmMkLst. */
export function cmMkLst(value: M.CTCommentMonikerList): M.TypedNamedValue<M.CTCommentMonikerList>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2013/main/command}docMkLst. */
export function docMkLst(value: M.CTDocumentMonikerList): M.TypedNamedValue<M.CTDocumentMonikerList>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2013/main/command}sldBaseMkLst. */
export function sldBaseMkLst(value: M.CTSlideBaseMonikerList): M.TypedNamedValue<M.CTSlideBaseMonikerList>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2013/main/command}sldLayoutMkLst. */
export function sldLayoutMkLst(value: M.CTSlideLayoutMonikerList): M.TypedNamedValue<M.CTSlideLayoutMonikerList>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2013/main/command}sldMasterMkLst. */
export function sldMasterMkLst(value: M.CTMainMasterMonikerList): M.TypedNamedValue<M.CTMainMasterMonikerList>;
/** The element {http://schemas.microsoft.com/office/powerpoint/2013/main/command}sldMkLst. */
export function sldMkLst(value: M.CTSlideMonikerList): M.TypedNamedValue<M.CTSlideMonikerList>;
