// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_dml_chart_x2007]. Do not edit.
import type * as M from './org_docx4j_dml_chart_x2007.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_dml_chart_x2007.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';

/** The element {http://schemas.microsoft.com/office/drawing/2007/8/2/chart}invertSolidFillFmt. */
export function invertSolidFillFmt(value: M.CTInvertSolidFillFmt): M.TypedNamedValue<M.CTInvertSolidFillFmt>;
/** The element {http://schemas.microsoft.com/office/drawing/2007/8/2/chart}pivotOptions. */
export function pivotOptions(value: M.CTPivotOptions): M.TypedNamedValue<M.CTPivotOptions>;
/** The element {http://schemas.microsoft.com/office/drawing/2007/8/2/chart}style. */
export function style(value: M.CTStyle): M.TypedNamedValue<M.CTStyle>;
