// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2018_calcfeatures]. Do not edit.
import type * as M from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2018_calcfeatures.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2018_calcfeatures.js';

/** The element {http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures}calcFeatures. */
export function calcFeatures(value: M.CTCalcFeatures): M.TypedNamedValue<M.CTCalcFeatures>;
