// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_bibliography]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.openxmlformats.org/officeDocument/2006/bibliography';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTAuthorType(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_bibliography.CTAuthorType' }, init); }
export function createCTNameListType(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_bibliography.CTNameListType' }, init); }
export function createCTNameOrCorporateType(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_bibliography.CTNameOrCorporateType' }, init); }
export function createCTNameType(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_bibliography.CTNameType' }, init); }
export function createCTPersonType(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_bibliography.CTPersonType' }, init); }
export function createCTSourceType(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_bibliography.CTSourceType' }, init); }
export function createCTSources(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_bibliography.CTSources' }, init); }
export function createCTSourceTypeAbbreviatedCaseNumber(value) { return __element(__ns0, 'AbbreviatedCaseNumber', value); }
export function createCTSourceTypeAlbumTitle(value) { return __element(__ns0, 'AlbumTitle', value); }
export function createCTAuthorTypeArtist(value) { return __element(__ns0, 'Artist', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTAuthorTypeAuthor(value) { return __element(__ns0, 'Author', value, 'org_docx4j_bibliography.CTNameOrCorporateType'); }
export function createCTSourceTypeAuthor(value) { return __element(__ns0, 'Author', value, 'org_docx4j_bibliography.CTAuthorType'); }
export function createCTAuthorTypeBookAuthor(value) { return __element(__ns0, 'BookAuthor', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeBookTitle(value) { return __element(__ns0, 'BookTitle', value); }
export function createCTSourceTypeBroadcastTitle(value) { return __element(__ns0, 'BroadcastTitle', value); }
export function createCTSourceTypeBroadcaster(value) { return __element(__ns0, 'Broadcaster', value); }
export function createCTSourceTypeCaseNumber(value) { return __element(__ns0, 'CaseNumber', value); }
export function createCTSourceTypeChapterNumber(value) { return __element(__ns0, 'ChapterNumber', value); }
export function createCTSourceTypeCity(value) { return __element(__ns0, 'City', value); }
export function createCTSourceTypeComments(value) { return __element(__ns0, 'Comments', value); }
export function createCTAuthorTypeCompiler(value) { return __element(__ns0, 'Compiler', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTAuthorTypeComposer(value) { return __element(__ns0, 'Composer', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTAuthorTypeConductor(value) { return __element(__ns0, 'Conductor', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeConferenceName(value) { return __element(__ns0, 'ConferenceName', value); }
export function createCTAuthorTypeCounsel(value) { return __element(__ns0, 'Counsel', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeCountryRegion(value) { return __element(__ns0, 'CountryRegion', value); }
export function createCTSourceTypeCourt(value) { return __element(__ns0, 'Court', value); }
export function createCTSourceTypeDay(value) { return __element(__ns0, 'Day', value); }
export function createCTSourceTypeDayAccessed(value) { return __element(__ns0, 'DayAccessed', value); }
export function createCTSourceTypeDepartment(value) { return __element(__ns0, 'Department', value); }
export function createCTAuthorTypeDirector(value) { return __element(__ns0, 'Director', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeDistributor(value) { return __element(__ns0, 'Distributor', value); }
export function createCTSourceTypeEdition(value) { return __element(__ns0, 'Edition', value); }
export function createCTAuthorTypeEditor(value) { return __element(__ns0, 'Editor', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeGuid(value) { return __element(__ns0, 'Guid', value); }
export function createCTSourceTypeInstitution(value) { return __element(__ns0, 'Institution', value); }
export function createCTSourceTypeInternetSiteTitle(value) { return __element(__ns0, 'InternetSiteTitle', value); }
export function createCTAuthorTypeInterviewee(value) { return __element(__ns0, 'Interviewee', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTAuthorTypeInterviewer(value) { return __element(__ns0, 'Interviewer', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTAuthorTypeInventor(value) { return __element(__ns0, 'Inventor', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeIssue(value) { return __element(__ns0, 'Issue', value); }
export function createCTSourceTypeJournalName(value) { return __element(__ns0, 'JournalName', value); }
export function createCTSourceTypeLCID(value) { return __element(__ns0, 'LCID', value); }
export function createCTSourceTypeMedium(value) { return __element(__ns0, 'Medium', value); }
export function createCTSourceTypeMonth(value) { return __element(__ns0, 'Month', value); }
export function createCTSourceTypeMonthAccessed(value) { return __element(__ns0, 'MonthAccessed', value); }
export function createCTSourceTypeNumberVolumes(value) { return __element(__ns0, 'NumberVolumes', value); }
export function createCTSourceTypePages(value) { return __element(__ns0, 'Pages', value); }
export function createCTSourceTypePatentNumber(value) { return __element(__ns0, 'PatentNumber', value); }
export function createCTAuthorTypePerformer(value) { return __element(__ns0, 'Performer', value, 'org_docx4j_bibliography.CTNameOrCorporateType'); }
export function createCTSourceTypePeriodicalTitle(value) { return __element(__ns0, 'PeriodicalTitle', value); }
export function createCTAuthorTypeProducerName(value) { return __element(__ns0, 'ProducerName', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeProductionCompany(value) { return __element(__ns0, 'ProductionCompany', value); }
export function createCTSourceTypePublicationTitle(value) { return __element(__ns0, 'PublicationTitle', value); }
export function createCTSourceTypePublisher(value) { return __element(__ns0, 'Publisher', value); }
export function createCTSourceTypeRecordingNumber(value) { return __element(__ns0, 'RecordingNumber', value); }
export function createCTSourceTypeRefOrder(value) { return __element(__ns0, 'RefOrder', value); }
export function createCTSourceTypeReporter(value) { return __element(__ns0, 'Reporter', value); }
export function createCTSourceTypeShortTitle(value) { return __element(__ns0, 'ShortTitle', value); }
export function createCTSourceTypeSourceType(value) { return __element(__ns0, 'SourceType', value); }
export function createSourcesElement(value) { return __element(__ns0, 'Sources', value, 'org_docx4j_bibliography.CTSources'); }
export function createCTSourceTypeStandardNumber(value) { return __element(__ns0, 'StandardNumber', value); }
export function createCTSourceTypeStateProvince(value) { return __element(__ns0, 'StateProvince', value); }
export function createCTSourceTypeStation(value) { return __element(__ns0, 'Station', value); }
export function createCTSourceTypeTag(value) { return __element(__ns0, 'Tag', value); }
export function createCTSourceTypeTheater(value) { return __element(__ns0, 'Theater', value); }
export function createCTSourceTypeThesisType(value) { return __element(__ns0, 'ThesisType', value); }
export function createCTSourceTypeTitle(value) { return __element(__ns0, 'Title', value); }
export function createCTAuthorTypeTranslator(value) { return __element(__ns0, 'Translator', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeType(value) { return __element(__ns0, 'Type', value); }
export function createCTSourceTypeURL(value) { return __element(__ns0, 'URL', value); }
export function createCTSourceTypeVersion(value) { return __element(__ns0, 'Version', value); }
export function createCTSourceTypeVolume(value) { return __element(__ns0, 'Volume', value); }
export function createCTAuthorTypeWriter(value) { return __element(__ns0, 'Writer', value, 'org_docx4j_bibliography.CTNameType'); }
export function createCTSourceTypeYear(value) { return __element(__ns0, 'Year', value); }
export function createCTSourceTypeYearAccessed(value) { return __element(__ns0, 'YearAccessed', value); }
