// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main]. Do not edit.
import type * as M from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x201510_main.js';
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml.js';

/** The element {http://schemas.microsoft.com/office/powerpoint/2015/10/main}revInfo. */
export function revInfo(value: M.CTRevisionInfo): M.TypedNamedValue<M.CTRevisionInfo>;
