// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_vml_wordprocessingDrawing]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'urn:schemas-microsoft-com:office:word';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTAnchorLock(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_vml_wordprocessingDrawing.CTAnchorLock' }, init); }
export function createCTBorder(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_vml_wordprocessingDrawing.CTBorder' }, init); }
export function createCTWrap(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_vml_wordprocessingDrawing.CTWrap' }, init); }
export function createAnchorlockElement(value) { return __element(__ns0, 'anchorlock', value, 'org_docx4j_vml_wordprocessingDrawing.CTAnchorLock'); }
export function createBorderbottomElement(value) { return __element(__ns0, 'borderbottom', value, 'org_docx4j_vml_wordprocessingDrawing.CTBorder'); }
export function createBorderleftElement(value) { return __element(__ns0, 'borderleft', value, 'org_docx4j_vml_wordprocessingDrawing.CTBorder'); }
export function createBorderrightElement(value) { return __element(__ns0, 'borderright', value, 'org_docx4j_vml_wordprocessingDrawing.CTBorder'); }
export function createBordertopElement(value) { return __element(__ns0, 'bordertop', value, 'org_docx4j_vml_wordprocessingDrawing.CTBorder'); }
export function createWrapElement(value) { return __element(__ns0, 'wrap', value, 'org_docx4j_vml_wordprocessingDrawing.CTWrap'); }
