// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup.js';

/** The element {http://schemas.microsoft.com/office/word/2010/wordprocessingShape}wsp. */
export function wsp(value: M.CTWordprocessingShape): M.TypedNamedValue<M.CTWordprocessingShape>;
