// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_mce]. Do not edit.
import type * as M from './org_docx4j_mce.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_mce.js';
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml.js';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml.js';
import type * as Dep_org_docx4j_math from './org_docx4j_math.js';
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml.js';

/** The element {http://schemas.openxmlformats.org/markup-compatibility/2006}AlternateContent. */
export function AlternateContent(value: M.AlternateContent): M.TypedNamedValue<M.AlternateContent>;
