// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_x2006_encryption]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/2006/encryption';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTDataIntegrity(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTDataIntegrity' }, init); }
export function createCTEncryption(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTEncryption' }, init); }
export function createCTKeyData(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTKeyData' }, init); }
export function createCTKeyEncryptor(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTKeyEncryptor' }, init); }
export function createCTKeyEncryptors(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTKeyEncryptors' }, init); }
export function createEncryptionElement(value) { return __element(__ns0, 'encryption', value, 'org_docx4j_com_microsoft_schemas_office_x2006_encryption.CTEncryption'); }
