// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_dml_spreadsheetdrawing]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function from(value) { return __element(__ns0, 'from', value, 'org_docx4j_dml_spreadsheetdrawing.CTMarker'); }
export function to(value) { return __element(__ns0, 'to', value, 'org_docx4j_dml_spreadsheetdrawing.CTMarker'); }
export function wsDr(value) { return __element(__ns0, 'wsDr', value, 'org_docx4j_dml_spreadsheetdrawing.CTDrawing'); }
