// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2016_SVG_main]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2016_SVG_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2016_SVG_main.js';

/** docx4j ObjectFactory.createCTSVGBlip(): a org_docx4j_com_microsoft_schemas_office_drawing_x2016_SVG_main.CTSVGBlip with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSVGBlip(init?: Partial<Omit<M.CTSVGBlip, 'TYPE_NAME' | 'PARENT'>>): M.CTSVGBlip;
/** The global element {http://schemas.microsoft.com/office/drawing/2016/SVG/main}svgBlip (docx4j ObjectFactory.createSvgBlip(value)). */
export function createSvgBlipElement(value: M.CTSVGBlip): M.TypedNamedValue<M.CTSVGBlip>;
