// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_xmlPackage]. Do not edit.
import type * as M from './org_docx4j_xmlPackage.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_xmlPackage.js';

/** docx4j ObjectFactory.createPackage(): a org_docx4j_xmlPackage.Package with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createPackage(init?: Partial<Omit<M.Package, 'TYPE_NAME' | 'PARENT'>>): M.Package;
/** docx4j ObjectFactory.createPart(): a org_docx4j_xmlPackage.Part with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createPart(init?: Partial<Omit<M.Part, 'TYPE_NAME' | 'PARENT'>>): M.Part;
/** docx4j ObjectFactory.createXmlData(): a org_docx4j_xmlPackage.XmlData with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createXmlData(init?: Partial<Omit<M.XmlData, 'TYPE_NAME' | 'PARENT'>>): M.XmlData;
/** The global element {http://schemas.microsoft.com/office/2006/xmlPackage}package (docx4j ObjectFactory.createPackage(value)). */
export function createPackageElement(value: M.Package): M.TypedNamedValue<M.Package>;
