// Generated by jsonix-schema-compiler: Jsonix mappings of the module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_ac] as an ES module. Do not edit.
export const org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_ac = {
  name: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_ac',
  defaultElementNamespaceURI: 'http:\/\/schemas.microsoft.com\/office\/spreadsheetml\/2010\/11\/ac',
  typeInfos: [{
      localName: 'CTAbsolutePath',
      typeName: 'CT_AbsolutePath',
      propertyInfos: [{
          name: 'url',
          required: true,
          attributeName: {
            localPart: 'url'
          },
          type: 'attribute'
        }]
    }],
  elementInfos: [{
      typeInfo: '.CTAbsolutePath',
      elementName: 'absPath'
    }]
};
