// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_w16]. Do not edit.
import type * as M from './org_docx4j_w16.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_w16.js';
import type * as Dep_org_docx4j_w16cex from './org_docx4j_w16cex.js';

/** docx4j ObjectFactory.createCTExtension(): a org_docx4j_w16.CTExtension with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTExtension(init?: Partial<Omit<M.CTExtension, 'TYPE_NAME' | 'PARENT'>>): M.CTExtension;
/** docx4j ObjectFactory.createCTExtensionList(): a org_docx4j_w16.CTExtensionList with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTExtensionList(init?: Partial<Omit<M.CTExtensionList, 'TYPE_NAME' | 'PARENT'>>): M.CTExtensionList;
