// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_dml_lockedCanvas]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createLockedCanvasElement(value) { return __element(__ns0, 'lockedCanvas', value, 'org_docx4j_dml.CTGvmlGroupShape'); }
