// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_docProps_variantTypes]. Do not edit.
import type * as M from './org_docx4j_docProps_variantTypes.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_docProps_variantTypes.js';
import type * as Dep_org_docx4j_docProps_custom from './org_docx4j_docProps_custom.js';
import type * as Dep_org_docx4j_docProps_extended from './org_docx4j_docProps_extended.js';

/** docx4j ObjectFactory.createArray(): a org_docx4j_docProps_variantTypes.Array with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createArray(init?: Partial<Omit<M.Array, 'TYPE_NAME' | 'PARENT'>>): M.Array;
/** docx4j ObjectFactory.createCf(): a org_docx4j_docProps_variantTypes.Cf with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCf(init?: Partial<Omit<M.Cf, 'TYPE_NAME' | 'PARENT'>>): M.Cf;
/** docx4j ObjectFactory.createEmpty(): a org_docx4j_docProps_variantTypes.Empty with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createEmpty(init?: Partial<Omit<M.Empty, 'TYPE_NAME' | 'PARENT'>>): M.Empty;
/** docx4j ObjectFactory.createNull(): a org_docx4j_docProps_variantTypes.Null with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createNull(init?: Partial<Omit<M.Null, 'TYPE_NAME' | 'PARENT'>>): M.Null;
/** docx4j ObjectFactory.createVariant(): a org_docx4j_docProps_variantTypes.Variant with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createVariant(init?: Partial<Omit<M.Variant, 'TYPE_NAME' | 'PARENT'>>): M.Variant;
/** docx4j ObjectFactory.createVector(): a org_docx4j_docProps_variantTypes.Vector with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createVector(init?: Partial<Omit<M.Vector, 'TYPE_NAME' | 'PARENT'>>): M.Vector;
/** docx4j ObjectFactory.createVstream(): a org_docx4j_docProps_variantTypes.Vstream with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createVstream(init?: Partial<Omit<M.Vstream, 'TYPE_NAME' | 'PARENT'>>): M.Vstream;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}array (docx4j ObjectFactory.createArray(value)). */
export function createArrayElement(value: M.Array): M.TypedNamedValue<M.Array>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}blob (docx4j ObjectFactory.createBlob(value)). */
export function createBlobElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}bool (docx4j ObjectFactory.createBool(value)). */
export function createBoolElement(value: boolean): M.TypedNamedValue<boolean>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}bstr (docx4j ObjectFactory.createBstr(value)). */
export function createBstrElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}cf (docx4j ObjectFactory.createCf(value)). */
export function createCfElement(value: M.Cf): M.TypedNamedValue<M.Cf>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}clsid (docx4j ObjectFactory.createClsid(value)). */
export function createClsidElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}cy (docx4j ObjectFactory.createCy(value)). */
export function createCyElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}date (docx4j ObjectFactory.createDate(value)). */
export function createDateElement(value: XmlCalendar): M.TypedNamedValue<XmlCalendar>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}decimal (docx4j ObjectFactory.createDecimal(value)). */
export function createDecimalElement(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}empty (docx4j ObjectFactory.createEmpty(value)). */
export function createEmptyElement(value: M.Empty): M.TypedNamedValue<M.Empty>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}error (docx4j ObjectFactory.createError(value)). */
export function createErrorElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}filetime (docx4j ObjectFactory.createFiletime(value)). */
export function createFiletimeElement(value: XmlCalendar): M.TypedNamedValue<XmlCalendar>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}i1 (docx4j ObjectFactory.createI1(value)). */
export function createI1Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}i2 (docx4j ObjectFactory.createI2(value)). */
export function createI2Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}i4 (docx4j ObjectFactory.createI4(value)). */
export function createI4Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}i8 (docx4j ObjectFactory.createI8(value)). */
export function createI8Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}int (docx4j ObjectFactory.createInt(value)). */
export function createIntElement(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}lpstr (docx4j ObjectFactory.createLpstr(value)). */
export function createLpstrElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}lpwstr (docx4j ObjectFactory.createLpwstr(value)). */
export function createLpwstrElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}null (docx4j ObjectFactory.createNull(value)). */
export function createNullElement(value: M.Null): M.TypedNamedValue<M.Null>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}oblob (docx4j ObjectFactory.createOblob(value)). */
export function createOblobElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ostorage (docx4j ObjectFactory.createOstorage(value)). */
export function createOstorageElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ostream (docx4j ObjectFactory.createOstream(value)). */
export function createOstreamElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}r4 (docx4j ObjectFactory.createR4(value)). */
export function createR4Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}r8 (docx4j ObjectFactory.createR8(value)). */
export function createR8Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}storage (docx4j ObjectFactory.createStorage(value)). */
export function createStorageElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}stream (docx4j ObjectFactory.createStream(value)). */
export function createStreamElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ui1 (docx4j ObjectFactory.createUi1(value)). */
export function createUi1Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ui2 (docx4j ObjectFactory.createUi2(value)). */
export function createUi2Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ui4 (docx4j ObjectFactory.createUi4(value)). */
export function createUi4Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}ui8 (docx4j ObjectFactory.createUi8(value)). */
export function createUi8Element(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}uint (docx4j ObjectFactory.createUint(value)). */
export function createUintElement(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}variant (docx4j ObjectFactory.createVariant(value)). */
export function createVariantElement(value: M.Variant): M.TypedNamedValue<M.Variant>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}vector (docx4j ObjectFactory.createVector(value)). */
export function createVectorElement(value: M.Vector): M.TypedNamedValue<M.Vector>;
/** The global element {http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes}vstream (docx4j ObjectFactory.createVstream(value)). */
export function createVstreamElement(value: M.Vstream): M.TypedNamedValue<M.Vstream>;
