// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_sectionzoom]. Do not edit.
import type * as M from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_sectionzoom.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_sectionzoom.js';
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml.js';
import type * as Dep_org_pptx4j_com_microsoft_schemas_office_powerpoint_x201606_main from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x201606_main.js';

/** The element {http://schemas.microsoft.com/office/powerpoint/2016/sectionzoom}sectionZm. */
export function sectionZm(value: M.CTSectionZoom): M.TypedNamedValue<M.CTSectionZoom>;
