// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/powerpoint/2010/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTBrowseMode(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTBrowseMode' }, init); }
export function createCTContentPartNonVisual(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTContentPartNonVisual' }, init); }
export function createCTDefaultImageDpi(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTDefaultImageDpi' }, init); }
export function createCTDiscardImageEditData(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTDiscardImageEditData' }, init); }
export function createCTFlyThroughTransition(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTFlyThroughTransition' }, init); }
export function createCTGlitterTransition(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTGlitterTransition' }, init); }
export function createCTLaserTrace(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLaserTrace' }, init); }
export function createCTLaserTraceList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLaserTraceList' }, init); }
export function createCTLaserTracePoint(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLaserTracePoint' }, init); }
export function createCTLeftRightDirectionTransition(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLeftRightDirectionTransition' }, init); }
export function createCTMedia(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMedia' }, init); }
export function createCTMediaBookmark(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaBookmark' }, init); }
export function createCTMediaBookmarkList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaBookmarkList' }, init); }
export function createCTMediaBookmarkTarget(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaBookmarkTarget' }, init); }
export function createCTMediaFade(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaFade' }, init); }
export function createCTMediaPlaybackEventRecord(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaPlaybackEventRecord' }, init); }
export function createCTMediaSeekEventRecord(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaSeekEventRecord' }, init); }
export function createCTMediaTrim(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaTrim' }, init); }
export function createCTNullEventRecord(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTNullEventRecord' }, init); }
export function createCTPrismTransition(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTPrismTransition' }, init); }
export function createCTRandomId(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTRandomId' }, init); }
export function createCTRevealTransition(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTRevealTransition' }, init); }
export function createCTRippleTransition(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTRippleTransition' }, init); }
export function createCTSection(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTSection' }, init); }
export function createCTSectionList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTSectionList' }, init); }
export function createCTSectionSlideIdList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTSectionSlideIdList' }, init); }
export function createCTSectionSlideIdListEntry(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTSectionSlideIdListEntry' }, init); }
export function createCTShowEventRecordList(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTShowEventRecordList' }, init); }
export function createCTShowMediaControls(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTShowMediaControls' }, init); }
export function createCTShredTransition(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTShredTransition' }, init); }
export function createCTTriggerEventRecord(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTTriggerEventRecord' }, init); }
export function createBmkTgtElement(value) { return __element(__ns0, 'bmkTgt', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaBookmarkTarget'); }
export function createBrowseModeElement(value) { return __element(__ns0, 'browseMode', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTBrowseMode'); }
export function createConveyorElement(value) { return __element(__ns0, 'conveyor', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLeftRightDirectionTransition'); }
export function createCreationIdElement(value) { return __element(__ns0, 'creationId', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTRandomId'); }
export function createDefaultImageDpiElement(value) { return __element(__ns0, 'defaultImageDpi', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTDefaultImageDpi'); }
export function createDiscardImageEditDataElement(value) { return __element(__ns0, 'discardImageEditData', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTDiscardImageEditData'); }
export function createDoorsElement(value) { return __element(__ns0, 'doors', value, 'org_pptx4j_pml.CTOrientationTransition'); }
export function createExtLstElement(value) { return __element(__ns0, 'extLst', value, 'org_pptx4j_pml.CTExtensionListModify'); }
export function createFerrisElement(value) { return __element(__ns0, 'ferris', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLeftRightDirectionTransition'); }
export function createFlashElement(value) { return __element(__ns0, 'flash', value, 'org_pptx4j_pml.CTEmpty'); }
export function createFlipElement(value) { return __element(__ns0, 'flip', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLeftRightDirectionTransition'); }
export function createFlythroughElement(value) { return __element(__ns0, 'flythrough', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTFlyThroughTransition'); }
export function createGalleryElement(value) { return __element(__ns0, 'gallery', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLeftRightDirectionTransition'); }
export function createGlitterElement(value) { return __element(__ns0, 'glitter', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTGlitterTransition'); }
export function createHoneycombElement(value) { return __element(__ns0, 'honeycomb', value, 'org_pptx4j_pml.CTEmpty'); }
export function createLaserClrElement(value) { return __element(__ns0, 'laserClr', value, 'org_docx4j_dml.CTColor'); }
export function createLaserTraceLstElement(value) { return __element(__ns0, 'laserTraceLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLaserTraceList'); }
export function createMediaElement(value) { return __element(__ns0, 'media', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMedia'); }
export function createModIdElement(value) { return __element(__ns0, 'modId', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTRandomId'); }
export function createCTShowEventRecordListNullEvt(value) { return __element(__ns0, 'nullEvt', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTNullEventRecord'); }
export function createNvContentPartPrElement(value) { return __element(__ns0, 'nvContentPartPr', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTContentPartNonVisual'); }
export function createPanElement(value) { return __element(__ns0, 'pan', value, 'org_pptx4j_pml.CTSideDirectionTransition'); }
export function createCTShowEventRecordListPauseEvt(value) { return __element(__ns0, 'pauseEvt', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaPlaybackEventRecord'); }
export function createCTShowEventRecordListPlayEvt(value) { return __element(__ns0, 'playEvt', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaPlaybackEventRecord'); }
export function createPrismElement(value) { return __element(__ns0, 'prism', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTPrismTransition'); }
export function createCTShowEventRecordListResumeEvt(value) { return __element(__ns0, 'resumeEvt', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaPlaybackEventRecord'); }
export function createRevealElement(value) { return __element(__ns0, 'reveal', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTRevealTransition'); }
export function createRippleElement(value) { return __element(__ns0, 'ripple', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTRippleTransition'); }
export function createSectionLstElement(value) { return __element(__ns0, 'sectionLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTSectionList'); }
export function createCTShowEventRecordListSeekEvt(value) { return __element(__ns0, 'seekEvt', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaSeekEventRecord'); }
export function createShowEvtLstElement(value) { return __element(__ns0, 'showEvtLst', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTShowEventRecordList'); }
export function createShowMediaCtrlsElement(value) { return __element(__ns0, 'showMediaCtrls', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTShowMediaControls'); }
export function createShredElement(value) { return __element(__ns0, 'shred', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTShredTransition'); }
export function createCTShowEventRecordListStopEvt(value) { return __element(__ns0, 'stopEvt', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTMediaPlaybackEventRecord'); }
export function createSwitchElement(value) { return __element(__ns0, 'switch', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTLeftRightDirectionTransition'); }
export function createCTShowEventRecordListTriggerEvt(value) { return __element(__ns0, 'triggerEvt', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2010_main.CTTriggerEventRecord'); }
export function createVortexElement(value) { return __element(__ns0, 'vortex', value, 'org_pptx4j_pml.CTSideDirectionTransition'); }
export function createWarpElement(value) { return __element(__ns0, 'warp', value, 'org_pptx4j_pml.CTInOutTransition'); }
export function createWheelReverseElement(value) { return __element(__ns0, 'wheelReverse', value, 'org_pptx4j_pml.CTWheelTransition'); }
export function createWindowElement(value) { return __element(__ns0, 'window', value, 'org_pptx4j_pml.CTOrientationTransition'); }
export function createXfrmElement(value) { return __element(__ns0, 'xfrm', value, 'org_docx4j_dml.CTTransform2D'); }
