var org_docx4j_org_w3_x1998_math_mathML_Module_Factory = function () {
  var org_docx4j_org_w3_x1998_math_mathML = {
    name: 'org_docx4j_org_w3_x1998_math_mathML',
    defaultElementNamespaceURI: 'http:\/\/www.w3.org\/1998\/Math\/MathML',
    typeInfos: [{
        localName: 'ApplyType',
        typeName: 'apply.type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'abs',
            typeInfo: '.OperatorType'
          }, {
            name: 'floor',
            typeInfo: '.OperatorType'
          }, {
            name: 'ceiling',
            typeInfo: '.OperatorType'
          }, {
            name: 'quotient',
            typeInfo: '.OperatorType'
          }, {
            name: 'divide',
            typeInfo: '.OperatorType'
          }, {
            name: 'rem',
            typeInfo: '.OperatorType'
          }, {
            name: 'minus',
            typeInfo: '.OperatorType'
          }, {
            name: 'plus',
            typeInfo: '.OperatorType'
          }, {
            name: 'times',
            typeInfo: '.OperatorType'
          }, {
            name: 'power',
            typeInfo: '.OperatorType'
          }, {
            name: 'root',
            typeInfo: '.OperatorType'
          }, {
            name: 'max',
            typeInfo: '.OperatorType'
          }, {
            name: 'min',
            typeInfo: '.OperatorType'
          }, {
            name: 'and',
            typeInfo: '.OperatorType'
          }, {
            name: 'or',
            typeInfo: '.OperatorType'
          }, {
            name: 'xor',
            typeInfo: '.OperatorType'
          }, {
            name: 'not',
            typeInfo: '.OperatorType'
          }, {
            name: 'exponentiale',
            typeInfo: '.ConstantType'
          }, {
            name: 'pi',
            typeInfo: '.ConstantType'
          }, {
            name: '_true',
            elementName: 'true',
            typeInfo: '.ConstantType'
          }, {
            name: '_false',
            elementName: 'false',
            typeInfo: '.ConstantType'
          }, {
            name: 'eq',
            typeInfo: '.OperatorType'
          }, {
            name: 'neq',
            typeInfo: '.OperatorType'
          }, {
            name: 'leq',
            typeInfo: '.OperatorType'
          }, {
            name: 'lt',
            typeInfo: '.OperatorType'
          }, {
            name: 'geq',
            typeInfo: '.OperatorType'
          }, {
            name: 'gt',
            typeInfo: '.OperatorType'
          }, {
            name: 'exp',
            typeInfo: '.OperatorType'
          }, {
            name: 'ln',
            typeInfo: '.OperatorType'
          }, {
            name: 'log',
            typeInfo: '.OperatorType'
          }, {
            name: 'sin',
            typeInfo: '.OperatorType'
          }, {
            name: 'cos',
            typeInfo: '.OperatorType'
          }, {
            name: 'tan',
            typeInfo: '.OperatorType'
          }, {
            name: 'arcsin',
            typeInfo: '.OperatorType'
          }, {
            name: 'arccos',
            typeInfo: '.OperatorType'
          }, {
            name: 'arctan',
            typeInfo: '.OperatorType'
          }, {
            name: 'expressionContent',
            minOccurs: 0,
            collection: true,
            mixed: false,
            allowDom: false,
            elementTypeInfos: [{
                elementName: 'cn',
                typeInfo: '.CnType'
              }, {
                elementName: 'ci',
                typeInfo: '.CiType'
              }, {
                elementName: 'exponentiale',
                typeInfo: '.ConstantType'
              }, {
                elementName: 'pi',
                typeInfo: '.ConstantType'
              }, {
                elementName: 'true',
                typeInfo: '.ConstantType'
              }, {
                elementName: 'false',
                typeInfo: '.ConstantType'
              }, {
                elementName: 'apply',
                typeInfo: '.ApplyType'
              }, {
                elementName: 'logbase',
                typeInfo: '.QualifierType'
              }, {
                elementName: 'degree',
                typeInfo: '.QualifierType'
              }],
            type: 'elementRefs'
          }]
      }, {
        localName: 'CiType',
        typeName: 'ci.type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'content',
            type: 'value'
          }]
      }, {
        localName: 'CnType',
        typeName: 'cn.type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'content',
            collection: true,
            allowDom: false,
            elementName: 'sep',
            typeInfo: '.SepType',
            type: 'elementRef'
          }, {
            name: 'type',
            values: ['integer', 'rational', 'real'],
            attributeName: {
              localPart: 'type'
            },
            type: 'attribute'
          }]
      }, {
        localName: 'ConstantType',
        typeName: 'constant.type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }]
      }, {
        localName: 'MathType',
        typeName: 'math.type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'cn',
            typeInfo: '.CnType'
          }, {
            name: 'ci',
            typeInfo: '.CiType'
          }, {
            name: 'exponentiale',
            typeInfo: '.ConstantType'
          }, {
            name: 'pi',
            typeInfo: '.ConstantType'
          }, {
            name: '_true',
            elementName: 'true',
            typeInfo: '.ConstantType'
          }, {
            name: '_false',
            elementName: 'false',
            typeInfo: '.ConstantType'
          }, {
            name: 'apply',
            typeInfo: '.ApplyType'
          }, {
            name: 'logbase',
            typeInfo: '.QualifierType'
          }, {
            name: 'degree',
            typeInfo: '.QualifierType'
          }]
      }, {
        localName: 'OperatorType',
        typeName: 'operator.type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }]
      }, {
        localName: 'QualifierType',
        typeName: 'qualifier.type',
        propertyInfos: [{
            name: 'otherAttributes',
            type: 'anyAttribute'
          }, {
            name: 'cn',
            typeInfo: '.CnType'
          }, {
            name: 'ci',
            typeInfo: '.CiType'
          }, {
            name: 'exponentiale',
            typeInfo: '.ConstantType'
          }, {
            name: 'pi',
            typeInfo: '.ConstantType'
          }, {
            name: '_true',
            elementName: 'true',
            typeInfo: '.ConstantType'
          }, {
            name: '_false',
            elementName: 'false',
            typeInfo: '.ConstantType'
          }, {
            name: 'apply',
            typeInfo: '.ApplyType'
          }, {
            name: 'logbase',
            typeInfo: '.QualifierType'
          }, {
            name: 'degree',
            typeInfo: '.QualifierType'
          }]
      }, {
        localName: 'SepType',
        typeName: 'sep.type'
      }],
    elementInfos: [{
        typeInfo: '.OperatorType',
        elementName: 'abs'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'and'
      }, {
        typeInfo: '.ApplyType',
        elementName: 'apply'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'arccos'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'arcsin'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'arctan'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'ceiling'
      }, {
        typeInfo: '.CiType',
        elementName: 'ci'
      }, {
        typeInfo: '.CnType',
        elementName: 'cn'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'cos'
      }, {
        typeInfo: '.QualifierType',
        elementName: 'degree'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'divide'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'eq'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'exp'
      }, {
        typeInfo: '.ConstantType',
        elementName: 'exponentiale'
      }, {
        typeInfo: '.ConstantType',
        elementName: 'false'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'floor'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'geq'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'gt'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'leq'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'ln'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'log'
      }, {
        typeInfo: '.QualifierType',
        elementName: 'logbase'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'lt'
      }, {
        typeInfo: '.MathType',
        elementName: 'math'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'max'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'min'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'minus'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'neq'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'not'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'or'
      }, {
        typeInfo: '.ConstantType',
        elementName: 'pi'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'plus'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'power'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'product'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'quotient'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'rem'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'root'
      }, {
        typeInfo: '.SepType',
        elementName: 'sep'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'sin'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'sum'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'tan'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'times'
      }, {
        typeInfo: '.ConstantType',
        elementName: 'true'
      }, {
        typeInfo: '.OperatorType',
        elementName: 'xor'
      }]
  };
  return {
    org_docx4j_org_w3_x1998_math_mathML: org_docx4j_org_w3_x1998_math_mathML
  };
};
if (typeof define === 'function' && define.amd) {
  define([], org_docx4j_org_w3_x1998_math_mathML_Module_Factory);
}
else {
  var org_docx4j_org_w3_x1998_math_mathML_Module = org_docx4j_org_w3_x1998_math_mathML_Module_Factory();
  if (typeof module !== 'undefined' && module.exports) {
    module.exports.org_docx4j_org_w3_x1998_math_mathML = org_docx4j_org_w3_x1998_math_mathML_Module.org_docx4j_org_w3_x1998_math_mathML;
  }
  else {
    var org_docx4j_org_w3_x1998_math_mathML = org_docx4j_org_w3_x1998_math_mathML_Module.org_docx4j_org_w3_x1998_math_mathML;
  }
}