// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_vml_root]. Do not edit.
import type * as M from './org_docx4j_vml_root.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_vml_root.js';

/** The element xml. */
export function xml(value: M.Xml): M.TypedNamedValue<M.Xml>;
