// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x201710_main]. Do not edit.
import type * as M from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x201710_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_pptx4j_com_microsoft_schemas_office_powerpoint_x201710_main.js';

/** The element {http://schemas.microsoft.com/office/powerpoint/2017/10/main}readonlyRecommended. */
export function readonlyRecommended(value: M.CTReadonlyRecommended): M.TypedNamedValue<M.CTReadonlyRecommended>;
