// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingShape.js';
import type * as Dep_org_docx4j_dml_picture from './org_docx4j_dml_picture.js';
import type * as Dep_org_docx4j_w14 from './org_docx4j_w14.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingGroup.js';

/** docx4j ObjectFactory.createCTWordprocessingCanvas(): a org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingCanvas.CTWordprocessingCanvas with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTWordprocessingCanvas(init?: Partial<Omit<M.CTWordprocessingCanvas, 'TYPE_NAME' | 'PARENT'>>): M.CTWordprocessingCanvas;
/** The global element {http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas}wpc (docx4j ObjectFactory.createWpc(value)). */
export function createWpcElement(value: M.CTWordprocessingCanvas): M.TypedNamedValue<M.CTWordprocessingCanvas>;
