// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2018_animation_model3d]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2018/animation/model3d';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTEmbeddedAnimation(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2018_animation_model3d.CTEmbeddedAnimation' }, init); }
export function createCTPosterFrame(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_com_microsoft_schemas_office_drawing_x2018_animation_model3d.CTPosterFrame' }, init); }
export function createEmbedAnimElement(value) { return __element(__ns0, 'embedAnim', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2018_animation_model3d.CTEmbeddedAnimation'); }
export function createPosterFrameElement(value) { return __element(__ns0, 'posterFrame', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2018_animation_model3d.CTPosterFrame'); }
