// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/spreadsheetml/2014/11/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTCalculatedTimeColumn(init) { return Object.assign({ TYPE_NAME: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTCalculatedTimeColumn' }, init); }
export function createCTModelTimeGrouping(init) { return Object.assign({ TYPE_NAME: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTModelTimeGrouping' }, init); }
export function createCTModelTimeGroupings(init) { return Object.assign({ TYPE_NAME: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTModelTimeGroupings' }, init); }
export function createModelTimeGroupingsElement(value) { return __element(__ns0, 'modelTimeGroupings', value, 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2014_x11_main.CTModelTimeGroupings'); }
