// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_w15]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/word/2012/wordml';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function appearance(value) { return __element(__ns0, 'appearance', value, 'org_docx4j_w15.CTSdtAppearance'); }
export function chartTrackingRefBased(value) { return __element(__ns0, 'chartTrackingRefBased', value, 'org_docx4j_wml.BooleanDefaultTrue'); }
export function collapsed(value) { return __element(__ns0, 'collapsed', value, 'org_docx4j_wml.BooleanDefaultTrue'); }
export function color(value) { return __element(__ns0, 'color', value, 'org_docx4j_wml.CTColor'); }
export function commentsEx(value) { return __element(__ns0, 'commentsEx', value, 'org_docx4j_w15.CTCommentsEx'); }
export function dataBinding(value) { return __element(__ns0, 'dataBinding', value, 'org_docx4j_wml.CTDataBinding'); }
export function docId(value) { return __element(__ns0, 'docId', value, 'org_docx4j_w15.CTGuid'); }
export function footnoteColumns(value) { return __element(__ns0, 'footnoteColumns', value, 'org_docx4j_wml.CTDecimalNumber'); }
export function people(value) { return __element(__ns0, 'people', value, 'org_docx4j_w15.CTPeople'); }
export function repeatingSection(value) { return __element(__ns0, 'repeatingSection', value, 'org_docx4j_w15.CTSdtRepeatedSection'); }
export function repeatingSectionItem(value) { return __element(__ns0, 'repeatingSectionItem', value, 'org_docx4j_wml.CTEmpty'); }
export function webExtensionCreated(value) { return __element(__ns0, 'webExtensionCreated', value, 'org_docx4j_wml.BooleanDefaultTrue'); }
export function webExtensionLinked(value) { return __element(__ns0, 'webExtensionLinked', value, 'org_docx4j_wml.BooleanDefaultTrue'); }
