// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_relationships]. Do not edit.
import type * as M from './org_docx4j_relationships.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_relationships.js';

/** docx4j ObjectFactory.createRelationship(): a org_docx4j_relationships.Relationship with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createRelationship(init?: Partial<Omit<M.Relationship, 'TYPE_NAME' | 'PARENT'>>): M.Relationship;
/** docx4j ObjectFactory.createRelationships(): a org_docx4j_relationships.Relationships with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createRelationships(init?: Partial<Omit<M.Relationships, 'TYPE_NAME' | 'PARENT'>>): M.Relationships;
/** The global element {http://schemas.openxmlformats.org/package/2006/relationships}Relationship (docx4j ObjectFactory.createRelationship(value)). */
export function createRelationshipElement(value: M.Relationship): M.TypedNamedValue<M.Relationship>;
/** The global element {http://schemas.openxmlformats.org/package/2006/relationships}Relationships (docx4j ObjectFactory.createRelationships(value)). */
export function createRelationshipsElement(value: M.Relationships): M.TypedNamedValue<M.Relationships>;
