// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main]. Do not edit.
import type * as M from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.js';
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml.js';
import type * as Dep_org_xlsx4j_schemas_microsoft_com_office_excel_2006_main from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.js';

/** docx4j ObjectFactory.createCTCacheField(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCacheField with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCacheField(init?: Partial<Omit<M.CTCacheField, 'TYPE_NAME' | 'PARENT'>>): M.CTCacheField;
/** docx4j ObjectFactory.createCTCacheHierarchy(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCacheHierarchy with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCacheHierarchy(init?: Partial<Omit<M.CTCacheHierarchy, 'TYPE_NAME' | 'PARENT'>>): M.CTCacheHierarchy;
/** docx4j ObjectFactory.createCTCacheSourceExt(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCacheSourceExt with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCacheSourceExt(init?: Partial<Omit<M.CTCacheSourceExt, 'TYPE_NAME' | 'PARENT'>>): M.CTCacheSourceExt;
/** docx4j ObjectFactory.createCTCalculatedMember(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCalculatedMember with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCalculatedMember(init?: Partial<Omit<M.CTCalculatedMember, 'TYPE_NAME' | 'PARENT'>>): M.CTCalculatedMember;
/** docx4j ObjectFactory.createCTCfIcon(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCfIcon with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCfIcon(init?: Partial<Omit<M.CTCfIcon, 'TYPE_NAME' | 'PARENT'>>): M.CTCfIcon;
/** docx4j ObjectFactory.createCTCfRule(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCfRule with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCfRule(init?: Partial<Omit<M.CTCfRule, 'TYPE_NAME' | 'PARENT'>>): M.CTCfRule;
/** docx4j ObjectFactory.createCTCfvo(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCfvo with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCfvo(init?: Partial<Omit<M.CTCfvo, 'TYPE_NAME' | 'PARENT'>>): M.CTCfvo;
/** docx4j ObjectFactory.createCTColorScale(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTColorScale with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTColorScale(init?: Partial<Omit<M.CTColorScale, 'TYPE_NAME' | 'PARENT'>>): M.CTColorScale;
/** docx4j ObjectFactory.createCTConditionalFormat(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTConditionalFormat with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTConditionalFormat(init?: Partial<Omit<M.CTConditionalFormat, 'TYPE_NAME' | 'PARENT'>>): M.CTConditionalFormat;
/** docx4j ObjectFactory.createCTConditionalFormats(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTConditionalFormats with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTConditionalFormats(init?: Partial<Omit<M.CTConditionalFormats, 'TYPE_NAME' | 'PARENT'>>): M.CTConditionalFormats;
/** docx4j ObjectFactory.createCTConditionalFormatting(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTConditionalFormatting with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTConditionalFormatting(init?: Partial<Omit<M.CTConditionalFormatting, 'TYPE_NAME' | 'PARENT'>>): M.CTConditionalFormatting;
/** docx4j ObjectFactory.createCTConditionalFormattings(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTConditionalFormattings with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTConditionalFormattings(init?: Partial<Omit<M.CTConditionalFormattings, 'TYPE_NAME' | 'PARENT'>>): M.CTConditionalFormattings;
/** docx4j ObjectFactory.createCTConnection(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTConnection with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTConnection(init?: Partial<Omit<M.CTConnection, 'TYPE_NAME' | 'PARENT'>>): M.CTConnection;
/** docx4j ObjectFactory.createCTCustomFilter(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCustomFilter with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCustomFilter(init?: Partial<Omit<M.CTCustomFilter, 'TYPE_NAME' | 'PARENT'>>): M.CTCustomFilter;
/** docx4j ObjectFactory.createCTCustomFilters(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTCustomFilters with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCustomFilters(init?: Partial<Omit<M.CTCustomFilters, 'TYPE_NAME' | 'PARENT'>>): M.CTCustomFilters;
/** docx4j ObjectFactory.createCTDataBar(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDataBar with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDataBar(init?: Partial<Omit<M.CTDataBar, 'TYPE_NAME' | 'PARENT'>>): M.CTDataBar;
/** docx4j ObjectFactory.createCTDataField(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDataField with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDataField(init?: Partial<Omit<M.CTDataField, 'TYPE_NAME' | 'PARENT'>>): M.CTDataField;
/** docx4j ObjectFactory.createCTDataValidation(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDataValidation with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDataValidation(init?: Partial<Omit<M.CTDataValidation, 'TYPE_NAME' | 'PARENT'>>): M.CTDataValidation;
/** docx4j ObjectFactory.createCTDataValidationFormula(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDataValidationFormula with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDataValidationFormula(init?: Partial<Omit<M.CTDataValidationFormula, 'TYPE_NAME' | 'PARENT'>>): M.CTDataValidationFormula;
/** docx4j ObjectFactory.createCTDataValidations(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDataValidations with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDataValidations(init?: Partial<Omit<M.CTDataValidations, 'TYPE_NAME' | 'PARENT'>>): M.CTDataValidations;
/** docx4j ObjectFactory.createCTDatastoreItem(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTDatastoreItem with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDatastoreItem(init?: Partial<Omit<M.CTDatastoreItem, 'TYPE_NAME' | 'PARENT'>>): M.CTDatastoreItem;
/** docx4j ObjectFactory.createCTFilter(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTFilter with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilter(init?: Partial<Omit<M.CTFilter, 'TYPE_NAME' | 'PARENT'>>): M.CTFilter;
/** docx4j ObjectFactory.createCTFormControlPr(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTFormControlPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFormControlPr(init?: Partial<Omit<M.CTFormControlPr, 'TYPE_NAME' | 'PARENT'>>): M.CTFormControlPr;
/** docx4j ObjectFactory.createCTIconFilter(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTIconFilter with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTIconFilter(init?: Partial<Omit<M.CTIconFilter, 'TYPE_NAME' | 'PARENT'>>): M.CTIconFilter;
/** docx4j ObjectFactory.createCTIconSet(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTIconSet with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTIconSet(init?: Partial<Omit<M.CTIconSet, 'TYPE_NAME' | 'PARENT'>>): M.CTIconSet;
/** docx4j ObjectFactory.createCTIgnoredError(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTIgnoredError with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTIgnoredError(init?: Partial<Omit<M.CTIgnoredError, 'TYPE_NAME' | 'PARENT'>>): M.CTIgnoredError;
/** docx4j ObjectFactory.createCTIgnoredErrors(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTIgnoredErrors with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTIgnoredErrors(init?: Partial<Omit<M.CTIgnoredErrors, 'TYPE_NAME' | 'PARENT'>>): M.CTIgnoredErrors;
/** docx4j ObjectFactory.createCTListItem(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTListItem with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTListItem(init?: Partial<Omit<M.CTListItem, 'TYPE_NAME' | 'PARENT'>>): M.CTListItem;
/** docx4j ObjectFactory.createCTListItems(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTListItems with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTListItems(init?: Partial<Omit<M.CTListItems, 'TYPE_NAME' | 'PARENT'>>): M.CTListItems;
/** docx4j ObjectFactory.createCTOlapSlicerCache(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCache with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCache(init?: Partial<Omit<M.CTOlapSlicerCache, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCache;
/** docx4j ObjectFactory.createCTOlapSlicerCacheItem(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCacheItem with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCacheItem(init?: Partial<Omit<M.CTOlapSlicerCacheItem, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCacheItem;
/** docx4j ObjectFactory.createCTOlapSlicerCacheItemParent(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCacheItemParent with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCacheItemParent(init?: Partial<Omit<M.CTOlapSlicerCacheItemParent, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCacheItemParent;
/** docx4j ObjectFactory.createCTOlapSlicerCacheLevelData(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCacheLevelData with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCacheLevelData(init?: Partial<Omit<M.CTOlapSlicerCacheLevelData, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCacheLevelData;
/** docx4j ObjectFactory.createCTOlapSlicerCacheLevelsData(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCacheLevelsData with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCacheLevelsData(init?: Partial<Omit<M.CTOlapSlicerCacheLevelsData, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCacheLevelsData;
/** docx4j ObjectFactory.createCTOlapSlicerCacheRange(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCacheRange with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCacheRange(init?: Partial<Omit<M.CTOlapSlicerCacheRange, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCacheRange;
/** docx4j ObjectFactory.createCTOlapSlicerCacheRanges(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCacheRanges with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCacheRanges(init?: Partial<Omit<M.CTOlapSlicerCacheRanges, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCacheRanges;
/** docx4j ObjectFactory.createCTOlapSlicerCacheSelection(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCacheSelection with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCacheSelection(init?: Partial<Omit<M.CTOlapSlicerCacheSelection, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCacheSelection;
/** docx4j ObjectFactory.createCTOlapSlicerCacheSelections(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOlapSlicerCacheSelections with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOlapSlicerCacheSelections(init?: Partial<Omit<M.CTOlapSlicerCacheSelections, 'TYPE_NAME' | 'PARENT'>>): M.CTOlapSlicerCacheSelections;
/** docx4j ObjectFactory.createCTOleItem(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTOleItem with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTOleItem(init?: Partial<Omit<M.CTOleItem, 'TYPE_NAME' | 'PARENT'>>): M.CTOleItem;
/** docx4j ObjectFactory.createCTPivotCacheDefinition(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotCacheDefinition with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotCacheDefinition(init?: Partial<Omit<M.CTPivotCacheDefinition, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotCacheDefinition;
/** docx4j ObjectFactory.createCTPivotChange(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotChange with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotChange(init?: Partial<Omit<M.CTPivotChange, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotChange;
/** docx4j ObjectFactory.createCTPivotChanges(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotChanges with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotChanges(init?: Partial<Omit<M.CTPivotChanges, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotChanges;
/** docx4j ObjectFactory.createCTPivotEdit(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotEdit with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotEdit(init?: Partial<Omit<M.CTPivotEdit, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotEdit;
/** docx4j ObjectFactory.createCTPivotEditValue(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotEditValue with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotEditValue(init?: Partial<Omit<M.CTPivotEditValue, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotEditValue;
/** docx4j ObjectFactory.createCTPivotEdits(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotEdits with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotEdits(init?: Partial<Omit<M.CTPivotEdits, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotEdits;
/** docx4j ObjectFactory.createCTPivotField(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotField with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotField(init?: Partial<Omit<M.CTPivotField, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotField;
/** docx4j ObjectFactory.createCTPivotHierarchy(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotHierarchy with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotHierarchy(init?: Partial<Omit<M.CTPivotHierarchy, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotHierarchy;
/** docx4j ObjectFactory.createCTPivotTableDefinition(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotTableDefinition with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotTableDefinition(init?: Partial<Omit<M.CTPivotTableDefinition, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotTableDefinition;
/** docx4j ObjectFactory.createCTPivotUserEdit(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTPivotUserEdit with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPivotUserEdit(init?: Partial<Omit<M.CTPivotUserEdit, 'TYPE_NAME' | 'PARENT'>>): M.CTPivotUserEdit;
/** docx4j ObjectFactory.createCTProtectedRange(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTProtectedRange with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTProtectedRange(init?: Partial<Omit<M.CTProtectedRange, 'TYPE_NAME' | 'PARENT'>>): M.CTProtectedRange;
/** docx4j ObjectFactory.createCTProtectedRanges(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTProtectedRanges with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTProtectedRanges(init?: Partial<Omit<M.CTProtectedRanges, 'TYPE_NAME' | 'PARENT'>>): M.CTProtectedRanges;
/** docx4j ObjectFactory.createCTSetLevel(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSetLevel with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSetLevel(init?: Partial<Omit<M.CTSetLevel, 'TYPE_NAME' | 'PARENT'>>): M.CTSetLevel;
/** docx4j ObjectFactory.createCTSetLevels(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSetLevels with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSetLevels(init?: Partial<Omit<M.CTSetLevels, 'TYPE_NAME' | 'PARENT'>>): M.CTSetLevels;
/** docx4j ObjectFactory.createCTSlicer(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicer(init?: Partial<Omit<M.CTSlicer, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicer;
/** docx4j ObjectFactory.createCTSlicerCache(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCache with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerCache(init?: Partial<Omit<M.CTSlicerCache, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerCache;
/** docx4j ObjectFactory.createCTSlicerCacheData(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCacheData with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerCacheData(init?: Partial<Omit<M.CTSlicerCacheData, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerCacheData;
/** docx4j ObjectFactory.createCTSlicerCacheDefinition(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCacheDefinition with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerCacheDefinition(init?: Partial<Omit<M.CTSlicerCacheDefinition, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerCacheDefinition;
/** docx4j ObjectFactory.createCTSlicerCachePivotTable(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCachePivotTable with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerCachePivotTable(init?: Partial<Omit<M.CTSlicerCachePivotTable, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerCachePivotTable;
/** docx4j ObjectFactory.createCTSlicerCachePivotTables(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCachePivotTables with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerCachePivotTables(init?: Partial<Omit<M.CTSlicerCachePivotTables, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerCachePivotTables;
/** docx4j ObjectFactory.createCTSlicerCaches(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCaches with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerCaches(init?: Partial<Omit<M.CTSlicerCaches, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerCaches;
/** docx4j ObjectFactory.createCTSlicerRef(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerRef with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerRef(init?: Partial<Omit<M.CTSlicerRef, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerRef;
/** docx4j ObjectFactory.createCTSlicerRefs(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerRefs with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerRefs(init?: Partial<Omit<M.CTSlicerRefs, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerRefs;
/** docx4j ObjectFactory.createCTSlicerStyle(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerStyle with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerStyle(init?: Partial<Omit<M.CTSlicerStyle, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerStyle;
/** docx4j ObjectFactory.createCTSlicerStyleElement(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerStyleElement with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerStyleElement(init?: Partial<Omit<M.CTSlicerStyleElement, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerStyleElement;
/** docx4j ObjectFactory.createCTSlicerStyleElements(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerStyleElements with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerStyleElements(init?: Partial<Omit<M.CTSlicerStyleElements, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerStyleElements;
/** docx4j ObjectFactory.createCTSlicerStyles(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerStyles with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicerStyles(init?: Partial<Omit<M.CTSlicerStyles, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicerStyles;
/** docx4j ObjectFactory.createCTSlicers(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicers with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSlicers(init?: Partial<Omit<M.CTSlicers, 'TYPE_NAME' | 'PARENT'>>): M.CTSlicers;
/** docx4j ObjectFactory.createCTSortCondition(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSortCondition with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSortCondition(init?: Partial<Omit<M.CTSortCondition, 'TYPE_NAME' | 'PARENT'>>): M.CTSortCondition;
/** docx4j ObjectFactory.createCTSourceConnection(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSourceConnection with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSourceConnection(init?: Partial<Omit<M.CTSourceConnection, 'TYPE_NAME' | 'PARENT'>>): M.CTSourceConnection;
/** docx4j ObjectFactory.createCTSparkline(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSparkline with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSparkline(init?: Partial<Omit<M.CTSparkline, 'TYPE_NAME' | 'PARENT'>>): M.CTSparkline;
/** docx4j ObjectFactory.createCTSparklineGroup(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSparklineGroup with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSparklineGroup(init?: Partial<Omit<M.CTSparklineGroup, 'TYPE_NAME' | 'PARENT'>>): M.CTSparklineGroup;
/** docx4j ObjectFactory.createCTSparklineGroups(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSparklineGroups with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSparklineGroups(init?: Partial<Omit<M.CTSparklineGroups, 'TYPE_NAME' | 'PARENT'>>): M.CTSparklineGroups;
/** docx4j ObjectFactory.createCTSparklines(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSparklines with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSparklines(init?: Partial<Omit<M.CTSparklines, 'TYPE_NAME' | 'PARENT'>>): M.CTSparklines;
/** docx4j ObjectFactory.createCTTable(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTable with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTable(init?: Partial<Omit<M.CTTable, 'TYPE_NAME' | 'PARENT'>>): M.CTTable;
/** docx4j ObjectFactory.createCTTabularSlicerCache(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTabularSlicerCache with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTabularSlicerCache(init?: Partial<Omit<M.CTTabularSlicerCache, 'TYPE_NAME' | 'PARENT'>>): M.CTTabularSlicerCache;
/** docx4j ObjectFactory.createCTTabularSlicerCacheItem(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTabularSlicerCacheItem with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTabularSlicerCacheItem(init?: Partial<Omit<M.CTTabularSlicerCacheItem, 'TYPE_NAME' | 'PARENT'>>): M.CTTabularSlicerCacheItem;
/** docx4j ObjectFactory.createCTTabularSlicerCacheItems(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTabularSlicerCacheItems with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTabularSlicerCacheItems(init?: Partial<Omit<M.CTTabularSlicerCacheItems, 'TYPE_NAME' | 'PARENT'>>): M.CTTabularSlicerCacheItems;
/** docx4j ObjectFactory.createCTTupleItems(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTupleItems with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTupleItems(init?: Partial<Omit<M.CTTupleItems, 'TYPE_NAME' | 'PARENT'>>): M.CTTupleItems;
/** docx4j ObjectFactory.createCTTupleSet(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTupleSet with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTupleSet(init?: Partial<Omit<M.CTTupleSet, 'TYPE_NAME' | 'PARENT'>>): M.CTTupleSet;
/** docx4j ObjectFactory.createCTTupleSetHeader(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTupleSetHeader with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTupleSetHeader(init?: Partial<Omit<M.CTTupleSetHeader, 'TYPE_NAME' | 'PARENT'>>): M.CTTupleSetHeader;
/** docx4j ObjectFactory.createCTTupleSetHeaders(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTupleSetHeaders with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTupleSetHeaders(init?: Partial<Omit<M.CTTupleSetHeaders, 'TYPE_NAME' | 'PARENT'>>): M.CTTupleSetHeaders;
/** docx4j ObjectFactory.createCTTupleSetRow(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTupleSetRow with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTupleSetRow(init?: Partial<Omit<M.CTTupleSetRow, 'TYPE_NAME' | 'PARENT'>>): M.CTTupleSetRow;
/** docx4j ObjectFactory.createCTTupleSetRowItem(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTupleSetRowItem with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTupleSetRowItem(init?: Partial<Omit<M.CTTupleSetRowItem, 'TYPE_NAME' | 'PARENT'>>): M.CTTupleSetRowItem;
/** docx4j ObjectFactory.createCTTupleSetRows(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTTupleSetRows with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTTupleSetRows(init?: Partial<Omit<M.CTTupleSetRows, 'TYPE_NAME' | 'PARENT'>>): M.CTTupleSetRows;
/** docx4j ObjectFactory.createCTWorkbookPr(): a org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTWorkbookPr with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTWorkbookPr(init?: Partial<Omit<M.CTWorkbookPr, 'TYPE_NAME' | 'PARENT'>>): M.CTWorkbookPr;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}cacheField (docx4j ObjectFactory.createCacheField(value)). */
export function createCacheFieldElement(value: M.CTCacheField): M.TypedNamedValue<M.CTCacheField>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}cacheHierarchy (docx4j ObjectFactory.createCacheHierarchy(value)). */
export function createCacheHierarchyElement(value: M.CTCacheHierarchy): M.TypedNamedValue<M.CTCacheHierarchy>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}calculatedMember (docx4j ObjectFactory.createCalculatedMember(value)). */
export function createCalculatedMemberElement(value: M.CTCalculatedMember): M.TypedNamedValue<M.CTCalculatedMember>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}conditionalFormattings (docx4j ObjectFactory.createConditionalFormattings(value)). */
export function createConditionalFormattingsElement(value: M.CTConditionalFormattings): M.TypedNamedValue<M.CTConditionalFormattings>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}connection (docx4j ObjectFactory.createConnection(value)). */
export function createConnectionElement(value: M.CTConnection): M.TypedNamedValue<M.CTConnection>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}customFilters (docx4j ObjectFactory.createCustomFilters(value)). */
export function createCustomFiltersElement(value: M.CTCustomFilters): M.TypedNamedValue<M.CTCustomFilters>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}dataField (docx4j ObjectFactory.createDataField(value)). */
export function createDataFieldElement(value: M.CTDataField): M.TypedNamedValue<M.CTDataField>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}dataValidations (docx4j ObjectFactory.createDataValidations(value)). */
export function createDataValidationsElement(value: M.CTDataValidations): M.TypedNamedValue<M.CTDataValidations>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}datastoreItem (docx4j ObjectFactory.createDatastoreItem(value)). */
export function createDatastoreItemElement(value: M.CTDatastoreItem): M.TypedNamedValue<M.CTDatastoreItem>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}dxfs (docx4j ObjectFactory.createDxfs(value)). */
export function createDxfsElement(value: Dep_org_xlsx4j_sml.CTDxfs): M.TypedNamedValue<Dep_org_xlsx4j_sml.CTDxfs>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}filter (docx4j ObjectFactory.createFilter(value)). */
export function createFilterElement(value: M.CTFilter): M.TypedNamedValue<M.CTFilter>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}formControlPr (docx4j ObjectFactory.createFormControlPr(value)). */
export function createFormControlPrElement(value: M.CTFormControlPr): M.TypedNamedValue<M.CTFormControlPr>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}iconFilter (docx4j ObjectFactory.createIconFilter(value)). */
export function createIconFilterElement(value: M.CTIconFilter): M.TypedNamedValue<M.CTIconFilter>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}id (docx4j ObjectFactory.createId(value)). */
export function createIdElement(value: string): M.TypedNamedValue<string>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}ignoredErrors (docx4j ObjectFactory.createIgnoredErrors(value)). */
export function createIgnoredErrorsElement(value: M.CTIgnoredErrors): M.TypedNamedValue<M.CTIgnoredErrors>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}oleItem (docx4j ObjectFactory.createOleItem(value)). */
export function createOleItemElement(value: M.CTOleItem): M.TypedNamedValue<M.CTOleItem>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}pivotCacheDefinition (docx4j ObjectFactory.createPivotCacheDefinition(value)). */
export function createPivotCacheDefinitionElement(value: M.CTPivotCacheDefinition): M.TypedNamedValue<M.CTPivotCacheDefinition>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}pivotCaches (docx4j ObjectFactory.createPivotCaches(value)). */
export function createPivotCachesElement(value: Dep_org_xlsx4j_sml.CTPivotCaches): M.TypedNamedValue<Dep_org_xlsx4j_sml.CTPivotCaches>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}pivotField (docx4j ObjectFactory.createPivotField(value)). */
export function createPivotFieldElement(value: M.CTPivotField): M.TypedNamedValue<M.CTPivotField>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}pivotHierarchy (docx4j ObjectFactory.createPivotHierarchy(value)). */
export function createPivotHierarchyElement(value: M.CTPivotHierarchy): M.TypedNamedValue<M.CTPivotHierarchy>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}pivotTableDefinition (docx4j ObjectFactory.createPivotTableDefinition(value)). */
export function createPivotTableDefinitionElement(value: M.CTPivotTableDefinition): M.TypedNamedValue<M.CTPivotTableDefinition>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}protectedRanges (docx4j ObjectFactory.createProtectedRanges(value)). */
export function createProtectedRangesElement(value: M.CTProtectedRanges): M.TypedNamedValue<M.CTProtectedRanges>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}slicerCacheDefinition (docx4j ObjectFactory.createSlicerCacheDefinition(value)). */
export function createSlicerCacheDefinitionElement(value: M.CTSlicerCacheDefinition): M.TypedNamedValue<M.CTSlicerCacheDefinition>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}slicerCaches (docx4j ObjectFactory.createSlicerCaches(value)). */
export function createSlicerCachesElement(value: M.CTSlicerCaches): M.TypedNamedValue<M.CTSlicerCaches>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}slicerList (docx4j ObjectFactory.createSlicerList(value)). */
export function createSlicerListElement(value: M.CTSlicerRefs): M.TypedNamedValue<M.CTSlicerRefs>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}slicerStyles (docx4j ObjectFactory.createSlicerStyles(value)). */
export function createSlicerStylesElement(value: M.CTSlicerStyles): M.TypedNamedValue<M.CTSlicerStyles>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}slicers (docx4j ObjectFactory.createSlicers(value)). */
export function createSlicersElement(value: M.CTSlicers): M.TypedNamedValue<M.CTSlicers>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}sortCondition (docx4j ObjectFactory.createSortCondition(value)). */
export function createSortConditionElement(value: M.CTSortCondition): M.TypedNamedValue<M.CTSortCondition>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}sourceConnection (docx4j ObjectFactory.createSourceConnection(value)). */
export function createSourceConnectionElement(value: M.CTSourceConnection): M.TypedNamedValue<M.CTSourceConnection>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}sparklineGroups (docx4j ObjectFactory.createSparklineGroups(value)). */
export function createSparklineGroupsElement(value: M.CTSparklineGroups): M.TypedNamedValue<M.CTSparklineGroups>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}table (docx4j ObjectFactory.createTable(value)). */
export function createTableElement(value: M.CTTable): M.TypedNamedValue<M.CTTable>;
/** The global element {http://schemas.microsoft.com/office/spreadsheetml/2009/9/main}workbookPr (docx4j ObjectFactory.createWorkbookPr(value)). */
export function createWorkbookPrElement(value: M.CTWorkbookPr): M.TypedNamedValue<M.CTWorkbookPr>;
