// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_password]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_password.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_password.js';
import type * as Dep_org_docx4j_com_microsoft_schemas_office_x2006_encryption from './org_docx4j_com_microsoft_schemas_office_x2006_encryption.js';

/** docx4j ObjectFactory.createCTPasswordKeyEncryptor(): a org_docx4j_com_microsoft_schemas_office_x2006_keyEncryptor_password.CTPasswordKeyEncryptor with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTPasswordKeyEncryptor(init?: Partial<Omit<M.CTPasswordKeyEncryptor, 'TYPE_NAME' | 'PARENT'>>): M.CTPasswordKeyEncryptor;
/** The global element {http://schemas.microsoft.com/office/2006/keyEncryptor/password}encryptedKey (docx4j ObjectFactory.createEncryptedKey(value)). */
export function createEncryptedKeyElement(value: M.CTPasswordKeyEncryptor): M.TypedNamedValue<M.CTPasswordKeyEncryptor>;
