// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_xlsx4j_schemas_microsoft_com_office_excel_2006_main]. Do not edit.
import type * as M from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_xlsx4j_schemas_microsoft_com_office_excel_2006_main.js';
import type * as Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.js';
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml.js';

/** The element {http://schemas.microsoft.com/office/excel/2006/main}f. */
export function f(value: string): M.TypedNamedValue<string>;
/** The element {http://schemas.microsoft.com/office/excel/2006/main}macrosheet. */
export function macrosheet(value: M.CTWorksheet): M.TypedNamedValue<M.CTWorksheet>;
/** The element {http://schemas.microsoft.com/office/excel/2006/main}ref. */
export function ref(value: M.CTRef): M.TypedNamedValue<M.CTRef>;
/** The element {http://schemas.microsoft.com/office/excel/2006/main}sqref. */
export function sqref(value: M.CTSqref): M.TypedNamedValue<M.CTSqref>;
