// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_docx4j_dml_chart from './org_docx4j_dml_chart.js';

/** docx4j ObjectFactory.createCTCategoryFilterException(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTCategoryFilterException with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCategoryFilterException(init?: Partial<Omit<M.CTCategoryFilterException, 'TYPE_NAME' | 'PARENT'>>): M.CTCategoryFilterException;
/** docx4j ObjectFactory.createCTCategoryFilterExceptions(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTCategoryFilterExceptions with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTCategoryFilterExceptions(init?: Partial<Omit<M.CTCategoryFilterExceptions, 'TYPE_NAME' | 'PARENT'>>): M.CTCategoryFilterExceptions;
/** docx4j ObjectFactory.createCTDataLabelFieldTable(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTDataLabelFieldTable with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDataLabelFieldTable(init?: Partial<Omit<M.CTDataLabelFieldTable, 'TYPE_NAME' | 'PARENT'>>): M.CTDataLabelFieldTable;
/** docx4j ObjectFactory.createCTDataLabelFieldTableEntry(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTDataLabelFieldTableEntry with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTDataLabelFieldTableEntry(init?: Partial<Omit<M.CTDataLabelFieldTableEntry, 'TYPE_NAME' | 'PARENT'>>): M.CTDataLabelFieldTableEntry;
/** docx4j ObjectFactory.createCTFilteredAreaSer(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredAreaSer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredAreaSer(init?: Partial<Omit<M.CTFilteredAreaSer, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredAreaSer;
/** docx4j ObjectFactory.createCTFilteredBarSer(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredBarSer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredBarSer(init?: Partial<Omit<M.CTFilteredBarSer, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredBarSer;
/** docx4j ObjectFactory.createCTFilteredBubbleSer(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredBubbleSer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredBubbleSer(init?: Partial<Omit<M.CTFilteredBubbleSer, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredBubbleSer;
/** docx4j ObjectFactory.createCTFilteredCategoryTitle(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredCategoryTitle with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredCategoryTitle(init?: Partial<Omit<M.CTFilteredCategoryTitle, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredCategoryTitle;
/** docx4j ObjectFactory.createCTFilteredLineSer(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredLineSer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredLineSer(init?: Partial<Omit<M.CTFilteredLineSer, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredLineSer;
/** docx4j ObjectFactory.createCTFilteredPieSer(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredPieSer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredPieSer(init?: Partial<Omit<M.CTFilteredPieSer, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredPieSer;
/** docx4j ObjectFactory.createCTFilteredRadarSer(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredRadarSer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredRadarSer(init?: Partial<Omit<M.CTFilteredRadarSer, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredRadarSer;
/** docx4j ObjectFactory.createCTFilteredScatterSer(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredScatterSer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredScatterSer(init?: Partial<Omit<M.CTFilteredScatterSer, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredScatterSer;
/** docx4j ObjectFactory.createCTFilteredSeriesTitle(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredSeriesTitle with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredSeriesTitle(init?: Partial<Omit<M.CTFilteredSeriesTitle, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredSeriesTitle;
/** docx4j ObjectFactory.createCTFilteredSurfaceSer(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFilteredSurfaceSer with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFilteredSurfaceSer(init?: Partial<Omit<M.CTFilteredSurfaceSer, 'TYPE_NAME' | 'PARENT'>>): M.CTFilteredSurfaceSer;
/** docx4j ObjectFactory.createCTFormulaRef(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFormulaRef with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFormulaRef(init?: Partial<Omit<M.CTFormulaRef, 'TYPE_NAME' | 'PARENT'>>): M.CTFormulaRef;
/** docx4j ObjectFactory.createCTFullRef(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTFullRef with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTFullRef(init?: Partial<Omit<M.CTFullRef, 'TYPE_NAME' | 'PARENT'>>): M.CTFullRef;
/** docx4j ObjectFactory.createCTLevelRef(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTLevelRef with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTLevelRef(init?: Partial<Omit<M.CTLevelRef, 'TYPE_NAME' | 'PARENT'>>): M.CTLevelRef;
/** docx4j ObjectFactory.createCTSeriesDataLabelsRange(): a org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.CTSeriesDataLabelsRange with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSeriesDataLabelsRange(init?: Partial<Omit<M.CTSeriesDataLabelsRange, 'TYPE_NAME' | 'PARENT'>>): M.CTSeriesDataLabelsRange;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}autoCat (docx4j ObjectFactory.createAutoCat(value)). */
export function createAutoCatElement(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}categoryFilterExceptions (docx4j ObjectFactory.createCategoryFilterExceptions(value)). */
export function createCategoryFilterExceptionsElement(value: M.CTCategoryFilterExceptions): M.TypedNamedValue<M.CTCategoryFilterExceptions>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}datalabelsRange (docx4j ObjectFactory.createDatalabelsRange(value)). */
export function createDatalabelsRangeElement(value: M.CTSeriesDataLabelsRange): M.TypedNamedValue<M.CTSeriesDataLabelsRange>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}dlblFieldTable (docx4j ObjectFactory.createDlblFieldTable(value)). */
export function createDlblFieldTableElement(value: M.CTDataLabelFieldTable): M.TypedNamedValue<M.CTDataLabelFieldTable>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredAreaSeries (docx4j ObjectFactory.createFilteredAreaSeries(value)). */
export function createFilteredAreaSeriesElement(value: M.CTFilteredAreaSer): M.TypedNamedValue<M.CTFilteredAreaSer>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredBarSeries (docx4j ObjectFactory.createFilteredBarSeries(value)). */
export function createFilteredBarSeriesElement(value: M.CTFilteredBarSer): M.TypedNamedValue<M.CTFilteredBarSer>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredBubbleSeries (docx4j ObjectFactory.createFilteredBubbleSeries(value)). */
export function createFilteredBubbleSeriesElement(value: M.CTFilteredBubbleSer): M.TypedNamedValue<M.CTFilteredBubbleSer>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredCategoryTitle (docx4j ObjectFactory.createFilteredCategoryTitle(value)). */
export function createFilteredCategoryTitleElement(value: M.CTFilteredCategoryTitle): M.TypedNamedValue<M.CTFilteredCategoryTitle>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredLineSeries (docx4j ObjectFactory.createFilteredLineSeries(value)). */
export function createFilteredLineSeriesElement(value: M.CTFilteredLineSer): M.TypedNamedValue<M.CTFilteredLineSer>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredPieSeries (docx4j ObjectFactory.createFilteredPieSeries(value)). */
export function createFilteredPieSeriesElement(value: M.CTFilteredPieSer): M.TypedNamedValue<M.CTFilteredPieSer>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredRadarSeries (docx4j ObjectFactory.createFilteredRadarSeries(value)). */
export function createFilteredRadarSeriesElement(value: M.CTFilteredRadarSer): M.TypedNamedValue<M.CTFilteredRadarSer>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredScatterSeries (docx4j ObjectFactory.createFilteredScatterSeries(value)). */
export function createFilteredScatterSeriesElement(value: M.CTFilteredScatterSer): M.TypedNamedValue<M.CTFilteredScatterSer>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredSeriesTitle (docx4j ObjectFactory.createFilteredSeriesTitle(value)). */
export function createFilteredSeriesTitleElement(value: M.CTFilteredSeriesTitle): M.TypedNamedValue<M.CTFilteredSeriesTitle>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredSurfaceSeries (docx4j ObjectFactory.createFilteredSurfaceSeries(value)). */
export function createFilteredSurfaceSeriesElement(value: M.CTFilteredSurfaceSer): M.TypedNamedValue<M.CTFilteredSurfaceSer>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}formulaRef (docx4j ObjectFactory.createFormulaRef(value)). */
export function createFormulaRefElement(value: M.CTFormulaRef): M.TypedNamedValue<M.CTFormulaRef>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}fullRef (docx4j ObjectFactory.createFullRef(value)). */
export function createFullRefElement(value: M.CTFullRef): M.TypedNamedValue<M.CTFullRef>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}layout (docx4j ObjectFactory.createLayout(value)). */
export function createLayoutElement(value: Dep_org_docx4j_dml_chart.CTLayout): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTLayout>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}leaderLines (docx4j ObjectFactory.createLeaderLines(value)). */
export function createLeaderLinesElement(value: Dep_org_docx4j_dml_chart.CTChartLines): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTChartLines>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}levelRef (docx4j ObjectFactory.createLevelRef(value)). */
export function createLevelRefElement(value: M.CTLevelRef): M.TypedNamedValue<M.CTLevelRef>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}numFmt (docx4j ObjectFactory.createNumFmt(value)). */
export function createNumFmtElement(value: Dep_org_docx4j_dml_chart.CTNumFmt): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTNumFmt>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}pivotSource (docx4j ObjectFactory.createPivotSource(value)). */
export function createPivotSourceElement(value: Dep_org_docx4j_dml_chart.CTPivotSource): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTPivotSource>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}showDataLabelsRange (docx4j ObjectFactory.createShowDataLabelsRange(value)). */
export function createShowDataLabelsRangeElement(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}showLeaderLines (docx4j ObjectFactory.createShowLeaderLines(value)). */
export function createShowLeaderLinesElement(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}spPr (docx4j ObjectFactory.createSpPr(value)). */
export function createSpPrElement(value: Dep_org_docx4j_dml.CTShapeProperties): M.TypedNamedValue<Dep_org_docx4j_dml.CTShapeProperties>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}tx (docx4j ObjectFactory.createTx(value)). */
export function createTxElement(value: Dep_org_docx4j_dml_chart.CTTx): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTTx>;
/** The global element {http://schemas.microsoft.com/office/drawing/2012/chart}xForSave (docx4j ObjectFactory.createXForSave(value)). */
export function createXForSaveElement(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
