// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2010_picture]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2010/picture';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function extLst(value) { return __element(__ns0, 'extLst', value, 'org_docx4j_dml.CTOfficeArtExtensionList'); }
export function style(value) { return __element(__ns0, 'style', value, 'org_docx4j_dml.CTShapeStyle'); }
