// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing.js';
import type * as Dep_org_docx4j_dml_wordprocessingDrawing from './org_docx4j_dml_wordprocessingDrawing.js';

/** docx4j ObjectFactory.createCTSizeRelH(): a org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing.CTSizeRelH with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSizeRelH(init?: Partial<Omit<M.CTSizeRelH, 'TYPE_NAME' | 'PARENT'>>): M.CTSizeRelH;
/** docx4j ObjectFactory.createCTSizeRelV(): a org_docx4j_com_microsoft_schemas_office_word_x2010_wordprocessingDrawing.CTSizeRelV with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTSizeRelV(init?: Partial<Omit<M.CTSizeRelV, 'TYPE_NAME' | 'PARENT'>>): M.CTSizeRelV;
/** The global element {http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}pctPosHOffset (docx4j ObjectFactory.createPctPosHOffset(value)). */
export function createPctPosHOffsetElement(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}pctPosVOffset (docx4j ObjectFactory.createPctPosVOffset(value)). */
export function createPctPosVOffsetElement(value: number): M.TypedNamedValue<number>;
/** The global element {http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}sizeRelH (docx4j ObjectFactory.createSizeRelH(value)). */
export function createSizeRelHElement(value: M.CTSizeRelH): M.TypedNamedValue<M.CTSizeRelH>;
/** The global element {http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing}sizeRelV (docx4j ObjectFactory.createSizeRelV(value)). */
export function createSizeRelVElement(value: M.CTSizeRelV): M.TypedNamedValue<M.CTSizeRelV>;
