// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_docProps_coverPageProps]. Do not edit.
import type * as M from './org_docx4j_docProps_coverPageProps.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_docProps_coverPageProps.js';

/** docx4j ObjectFactory.createCoverPageProperties(): a org_docx4j_docProps_coverPageProps.CoverPageProperties with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCoverPageProperties(init?: Partial<Omit<M.CoverPageProperties, 'TYPE_NAME' | 'PARENT'>>): M.CoverPageProperties;
/** The global element {http://schemas.microsoft.com/office/2006/coverPageProps}CoverPageProperties (docx4j ObjectFactory.createCoverPageProperties(value)). */
export function createCoverPagePropertiesElement(value: M.CoverPageProperties): M.TypedNamedValue<M.CoverPageProperties>;
