// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_dml_wordprocessingDrawing]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function anchor(value) { return __element(__ns0, 'anchor', value, 'org_docx4j_dml_wordprocessingDrawing.Anchor'); }
export function inline(value) { return __element(__ns0, 'inline', value, 'org_docx4j_dml_wordprocessingDrawing.Inline'); }
