// Generated by jsonix-schema-compiler: TypeScript declarations for the Jsonix module [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main]. Do not edit.
// Describes the objects Jsonix produces when unmarshalling with this module's mappings.
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml';
import type * as Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main from './org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main';

/** Jsonix.XML.QName */
export interface XmlQName { namespaceURI: string; localPart: string; prefix?: string; key?: string; string?: string; }
/** Jsonix.XML.Calendar: the representation of date, time and dateTime values; unset fields are NaN. */
export interface XmlCalendar { year?: number; month?: number; day?: number; hour?: number; minute?: number; second?: number; fractionalSecond?: number; timezone?: number; }
/** The representation of xs:duration values. */
export interface XmlDuration { sign?: number; years?: number; months?: number; days?: number; hours?: number; minutes?: number; seconds?: number; }
/** An element as returned by an unmarshaller or held by an elementRef property. */
export interface TypedNamedValue<T> { name: XmlQName; value: T; }
/** A DOM node, allowed where the mapping permits DOM content (allowDom). */
export type XmlDomNode = any;
/** The value of an anyElement property: a typed element, a DOM node or (if mixed) text. */
export type XmlAnyElement = any;
/** The value of an anyAttribute property. */
export interface XmlAnyAttributes { [attributeName: string]: string; }
/** A Jsonix mapping object as consumed by new Jsonix.Context([...]); R is the union of its global element types. */
export interface JsonixMapping<R = unknown> { readonly __rootElement?: R; readonly [key: string]: unknown; }

export interface CTCacheHierarchy {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTCacheHierarchy';
  aggregatedColumn: number;
}

export interface CTCachedUniqueName {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTCachedUniqueName';
  readonly PARENT?: CTCachedUniqueNames;
  index: number;
  name: string;
}

export interface CTCachedUniqueNames {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTCachedUniqueNames';
  cachedUniqueName: CTCachedUniqueName[];
}

export interface CTCalculatedMember {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTCalculatedMember';
  readonly PARENT?: CTCalculatedMemberExt;
  measure?: boolean;
  measureGroup?: string;
  numberFormat?: STCalcMemNumberFormat;
}

export interface CTCalculatedMemberExt {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTCalculatedMemberExt';
  calculatedMember: CTCalculatedMember;
}

export interface CTConnection {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTConnection';
  textPr?: Dep_org_xlsx4j_sml.CTTextPr;
  modelTextPr?: CTModelTextPr;
  rangePr?: CTRangePr;
  oledbPr?: CTOledbPr;
  dataFeedPr?: CTDataFeedPr;
  autoDelete?: boolean;
  excludeFromRefreshAll?: boolean;
  id: string;
  model?: boolean;
  usedByAddin?: boolean;
}

export interface CTDataFeedPr {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTDataFeedPr';
  readonly PARENT?: CTConnection;
  dbTables: CTDbTables;
  connection: string;
}

export interface CTDataField {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTDataField';
  isCountDistinct?: boolean;
}

export interface CTDataModel {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTDataModel';
  modelTables?: CTModelTables;
  modelRelationships?: CTModelRelationships;
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  minVersionLoad?: number;
}

export interface CTDbCommand {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTDbCommand';
  readonly PARENT?: CTOledbPr;
  text: string;
}

export interface CTDbTable {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTDbTable';
  readonly PARENT?: CTDbTables;
  name: string;
}

export interface CTDbTables {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTDbTables';
  readonly PARENT?: CTDataFeedPr | CTOledbPr;
  dbTable: CTDbTable[];
}

export interface CTFieldListActiveTabTopLevelEntity {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTFieldListActiveTabTopLevelEntity';
  readonly PARENT?: CTPivotTableUISettings;
  name: string;
  type?: number;
}

export interface CTModelRelationship {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTModelRelationship';
  readonly PARENT?: CTModelRelationships;
  fromColumn: string;
  fromTable: string;
  toColumn: string;
  toTable: string;
}

export interface CTModelRelationships {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTModelRelationships';
  readonly PARENT?: CTDataModel;
  modelRelationship: CTModelRelationship[];
}

export interface CTModelTable {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTModelTable';
  readonly PARENT?: CTModelTables;
  connection: string;
  id: string;
  name: string;
}

export interface CTModelTables {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTModelTables';
  readonly PARENT?: CTDataModel;
  modelTable: CTModelTable[];
}

export interface CTModelTextPr {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTModelTextPr';
  readonly PARENT?: CTConnection;
  headers?: boolean;
}

export interface CTOledbPr {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTOledbPr';
  readonly PARENT?: CTConnection;
  dbTables?: CTDbTables;
  dbCommand?: CTDbCommand;
  connection?: string;
}

export interface CTPivotCacheIdVersion {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotCacheIdVersion';
  cacheIdCreatedVersion: number;
  cacheIdSupportedVersion: number;
}

export interface CTPivotFilter {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotFilter';
  useWholeDay: boolean;
}

export interface CTPivotRow {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotRow';
  readonly PARENT?: CTPivotTableData;
  c: CTPivotValueCell[];
  count: number;
  r?: number;
}

export interface CTPivotTableData {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotTableData';
  pivotRow: CTPivotRow[];
  cacheId: number;
  columnCount: number;
  rowCount: number;
}

export interface CTPivotTableReference {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotTableReference';
  readonly PARENT?: CTPivotTableReferences;
  id: string;
}

export interface CTPivotTableReferences {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotTableReferences';
  pivotTableReference: CTPivotTableReference[];
}

export interface CTPivotTableServerFormats {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotTableServerFormats';
  serverFormat: Dep_org_xlsx4j_sml.CTServerFormat[];
  count: number;
}

export interface CTPivotTableUISettings {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotTableUISettings';
  activeTabTopLevelEntity?: CTFieldListActiveTabTopLevelEntity[];
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  relNeededHidden?: boolean;
  sourceDataName?: string;
}

export interface CTPivotValueCell {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotValueCell';
  readonly PARENT?: CTPivotRow;
  v: string;
  x?: CTPivotValueCellExtra;
  i?: number;
  t?: STSXVCellType;
}

export interface CTPivotValueCellExtra {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTPivotValueCellExtra';
  readonly PARENT?: CTPivotValueCell;
  b?: boolean;
  bc?: string;
  fc?: string;
  i?: boolean;
  in?: number;
  st?: boolean;
  un?: boolean;
}

export interface CTQueryTable {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTQueryTable';
  clipped?: boolean;
  drillThrough?: boolean;
  sourceDataName?: string;
}

export interface CTRangePr {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTRangePr';
  readonly PARENT?: CTConnection;
  sourceName: string;
}

export interface CTSlicerCacheHideNoData {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTSlicerCacheHideNoData';
  slicerCacheOlapLevelName?: CTSlicerCacheOlapLevelName[];
  count?: number;
}

export interface CTSlicerCacheOlapLevelName {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTSlicerCacheOlapLevelName';
  readonly PARENT?: CTSlicerCacheHideNoData;
  count: number;
  uniqueName: string;
}

export interface CTSurvey {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTSurvey';
  surveyPr?: CTSurveyElementPr;
  titlePr?: CTSurveyElementPr;
  descriptionPr?: CTSurveyElementPr;
  questions: CTSurveyQuestions;
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  description?: string;
  guid: string;
  id: number;
  title?: string;
}

export interface CTSurveyElementPr {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTSurveyElementPr';
  readonly PARENT?: CTSurvey | CTSurveyQuestion | CTSurveyQuestions;
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  bottom?: number;
  cssClass?: string;
  height?: number;
  left?: number;
  position?: STSurveyPosition;
  right?: number;
  top?: number;
  width?: number;
}

export interface CTSurveyQuestion {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTSurveyQuestion';
  readonly PARENT?: CTSurveyQuestions;
  questionPr?: CTSurveyElementPr;
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  binding: number;
  decimalPlaces?: number;
  defaultValue?: string;
  format?: STQuestionFormat;
  helpText?: string;
  required?: boolean;
  rowSource?: string;
  text?: string;
  type?: STQuestionType;
}

export interface CTSurveyQuestions {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTSurveyQuestions';
  readonly PARENT?: CTSurvey;
  questionsPr?: CTSurveyElementPr;
  question: CTSurveyQuestion[];
}

export interface CTTableSlicerCache {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTableSlicerCache';
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  column: number;
  crossFilter?: Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.STSlicerCacheCrossFilter;
  customListSort?: boolean;
  sortOrder?: Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.STTabularSlicerCacheSortOrder;
  tableId: number;
}

export interface CTTimeline {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimeline';
  readonly PARENT?: CTTimelines;
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  cache: string;
  caption?: string;
  level: number;
  name: string;
  scrollPosition?: XmlCalendar;
  selectionLevel: number;
  showHeader?: boolean;
  showHorizontalScrollbar?: boolean;
  showSelectionLabel?: boolean;
  showTimeLevel?: boolean;
  style?: string;
  uid?: string;
}

export interface CTTimelineCacheDefinition {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineCacheDefinition';
  pivotTables?: CTTimelineCachePivotTables;
  state: CTTimelineState;
  timelinePivotFilter?: CTTimelinePivotFilter;
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  name: string;
  sourceName: string;
  uid?: string;
  ignorable?: string;
}

export interface CTTimelineCachePivotTable {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineCachePivotTable';
  readonly PARENT?: CTTimelineCachePivotTables;
  name: string;
  tabId: number;
}

export interface CTTimelineCachePivotTables {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineCachePivotTables';
  readonly PARENT?: CTTimelineCacheDefinition;
  pivotTable: CTTimelineCachePivotTable[];
}

export interface CTTimelineCacheRef {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineCacheRef';
  readonly PARENT?: CTTimelineCacheRefs;
  id: string;
}

export interface CTTimelineCacheRefs {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineCacheRefs';
  timelineCacheRef: CTTimelineCacheRef[];
}

export interface CTTimelinePivotCacheDefinition {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelinePivotCacheDefinition';
  timelineData?: boolean;
}

export interface CTTimelinePivotFilter {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelinePivotFilter';
  readonly PARENT?: CTTimelineCacheDefinition;
  autoFilter?: Dep_org_xlsx4j_sml.CTAutoFilter;
  description?: string;
  fld: number;
  id: number;
  name?: string;
  useWholeDay?: boolean;
}

export interface CTTimelineRange {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineRange';
  readonly PARENT?: CTTimelineState;
  endDate: XmlCalendar;
  startDate: XmlCalendar;
}

export interface CTTimelineRef {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineRef';
  readonly PARENT?: CTTimelineRefs;
  id: string;
}

export interface CTTimelineRefs {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineRefs';
  timelineRef: CTTimelineRef[];
}

export interface CTTimelineState {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineState';
  readonly PARENT?: CTTimelineCacheDefinition;
  selection?: CTTimelineRange;
  bounds: CTTimelineRange;
  extLst?: Dep_org_xlsx4j_sml.CTExtensionList;
  filterType: Dep_org_xlsx4j_sml.STPivotFilterType;
  lastRefreshVersion: number;
  minimalRefreshVersion: number;
  pivotCacheId: number;
  singleRangeFilterState?: boolean;
}

export interface CTTimelineStyle {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineStyle';
  readonly PARENT?: CTTimelineStyles;
  timelineStyleElements?: CTTimelineStyleElements;
  name: string;
}

export interface CTTimelineStyleElement {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineStyleElement';
  readonly PARENT?: CTTimelineStyleElements;
  dxfId?: number;
  type: STTimelineStyleType;
}

export interface CTTimelineStyleElements {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineStyleElements';
  readonly PARENT?: CTTimelineStyle;
  timelineStyleElement: CTTimelineStyleElement[];
}

export interface CTTimelineStyles {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelineStyles';
  timelineStyle?: CTTimelineStyle[];
  defaultTimelineStyle: string;
}

export interface CTTimelines {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTTimelines';
  timeline: CTTimeline[];
  ignorable?: string;
}

export interface CTWebExtension {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTWebExtension';
  readonly PARENT?: CTWebExtensions;
  f: string;
  appRef: string;
}

export interface CTWebExtensions {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTWebExtensions';
  webExtension: CTWebExtension[];
}

export interface CTWorkbookPr {
  TYPE_NAME?: 'org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main.CTWorkbookPr';
  chartTrackingRefBase?: boolean;
}

export type STCalcMemNumberFormat = 'default' | 'number' | 'percent';

export type STQuestionFormat = 'generalDate' | 'longDate' | 'shortDate' | 'longTime' | 'shortTime' | 'generalNumber' | 'standard' | 'fixed' | 'percent' | 'currency';

export type STQuestionType = 'checkBox' | 'choice' | 'date' | 'time' | 'multipleLinesOfText' | 'number' | 'singleLineOfText';

export type STSXVCellType = 'b' | 'n' | 'e' | 'str' | 'd' | 'bl';

export type STSurveyPosition = 'absolute' | 'fixed' | 'relative' | 'static' | 'inherit';

export type STTimelineStyleType = 'selectionLabel' | 'timeLevel' | 'periodLabel1' | 'periodLabel2' | 'selectedTimeBlock' | 'unselectedTimeBlock' | 'selectedTimeBlockSpace';

export type CacheHierarchyElement = TypedNamedValue<CTCacheHierarchy>;

export type CachedUniqueNamesElement = TypedNamedValue<CTCachedUniqueNames>;

export type CalculatedMemberElement = TypedNamedValue<CTCalculatedMember>;

export type ConnectionElement = TypedNamedValue<CTConnection>;

export type DataFieldElement = TypedNamedValue<CTDataField>;

export type DataModelElement = TypedNamedValue<CTDataModel>;

export type DxfsElement = TypedNamedValue<Dep_org_xlsx4j_sml.CTDxfs>;

export type PivotCacheIdVersionElement = TypedNamedValue<CTPivotCacheIdVersion>;

export type PivotCachesElement = TypedNamedValue<Dep_org_xlsx4j_sml.CTPivotCaches>;

export type PivotFilterElement = TypedNamedValue<CTPivotFilter>;

export type PivotTableDataElement = TypedNamedValue<CTPivotTableData>;

export type PivotTableReferencesElement = TypedNamedValue<CTPivotTableReferences>;

export type PivotTableUISettingsElement = TypedNamedValue<CTPivotTableUISettings>;

export type QueryTableElement = TypedNamedValue<CTQueryTable>;

export type SlicerCacheHideItemsWithNoDataElement = TypedNamedValue<CTSlicerCacheHideNoData>;

export type SlicerCachePivotTablesElement = TypedNamedValue<Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCachePivotTables>;

export type SlicerCachesElement = TypedNamedValue<Dep_org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2009_x9_main.CTSlicerCaches>;

export type SurveyElement = TypedNamedValue<CTSurvey>;

export type TableSlicerCacheElement = TypedNamedValue<CTTableSlicerCache>;

export type TimelineCacheDefinitionElement = TypedNamedValue<CTTimelineCacheDefinition>;

export type TimelineCachePivotCachesElement = TypedNamedValue<Dep_org_xlsx4j_sml.CTPivotCaches>;

export type TimelineCacheRefsElement = TypedNamedValue<CTTimelineCacheRefs>;

export type TimelinePivotCacheDefinitionElement = TypedNamedValue<CTTimelinePivotCacheDefinition>;

export type TimelineRefsElement = TypedNamedValue<CTTimelineRefs>;

export type TimelineStylesElement = TypedNamedValue<CTTimelineStyles>;

export type TimelinesElement = TypedNamedValue<CTTimelines>;

export type WebExtensionsElement = TypedNamedValue<CTWebExtensions>;

export type WorkbookPrElement = TypedNamedValue<CTWorkbookPr>;

/** Any global element of this mapping, i.e. what an unmarshaller returns. */
export type RootElement = CacheHierarchyElement | CachedUniqueNamesElement | CalculatedMemberElement | ConnectionElement | DataFieldElement | DataModelElement | DxfsElement | PivotCacheIdVersionElement | PivotCachesElement | PivotFilterElement | PivotTableDataElement | PivotTableReferencesElement | PivotTableUISettingsElement | QueryTableElement | SlicerCacheHideItemsWithNoDataElement | SlicerCachePivotTablesElement | SlicerCachesElement | SurveyElement | TableSlicerCacheElement | TimelineCacheDefinitionElement | TimelineCachePivotCachesElement | TimelineCacheRefsElement | TimelinePivotCacheDefinitionElement | TimelineRefsElement | TimelineStylesElement | TimelinesElement | WebExtensionsElement | WorkbookPrElement;

/** The Jsonix mapping [org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main] exported by the module's JavaScript file. */
export declare const org_xlsx4j_com_microsoft_schemas_office_spreadsheetml_x2010_x11_main: JsonixMapping<RootElement>;
