// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_slidezoom]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/powerpoint/2016/slidezoom';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createCTSlideZoom(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_slidezoom.CTSlideZoom' }, init); }
export function createCTSlideZoomObject(init) { return Object.assign({ TYPE_NAME: 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_slidezoom.CTSlideZoomObject' }, init); }
export function createSldZmElement(value) { return __element(__ns0, 'sldZm', value, 'org_pptx4j_com_microsoft_schemas_office_powerpoint_x2016_slidezoom.CTSlideZoom'); }
