// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_vml_spreadsheetDrawing]. Do not edit.
import type * as M from './org_docx4j_vml_spreadsheetDrawing.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_vml_spreadsheetDrawing.js';
import type * as Dep_org_docx4j_vml from './org_docx4j_vml.js';

/** docx4j ObjectFactory.createCTClientData(): a org_docx4j_vml_spreadsheetDrawing.CTClientData with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCTClientData(init?: Partial<Omit<M.CTClientData, 'TYPE_NAME' | 'PARENT'>>): M.CTClientData;
/** The element {urn:schemas-microsoft-com:office:excel}Accel in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataAccel(value)). */
export function createCTClientDataAccel(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}Accel2 in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataAccel2(value)). */
export function createCTClientDataAccel2(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}Anchor in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataAnchor(value)). */
export function createCTClientDataAnchor(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}AutoFill in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataAutoFill(value)). */
export function createCTClientDataAutoFill(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}AutoLine in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataAutoLine(value)). */
export function createCTClientDataAutoLine(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}AutoPict in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataAutoPict(value)). */
export function createCTClientDataAutoPict(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}AutoScale in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataAutoScale(value)). */
export function createCTClientDataAutoScale(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}CF in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataCF(value)). */
export function createCTClientDataCF(value: M.STCF): M.TypedNamedValue<M.STCF>;
/** The element {urn:schemas-microsoft-com:office:excel}Camera in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataCamera(value)). */
export function createCTClientDataCamera(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Cancel in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataCancel(value)). */
export function createCTClientDataCancel(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Checked in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataChecked(value)). */
export function createCTClientDataChecked(value: number): M.TypedNamedValue<number>;
/** The global element {urn:schemas-microsoft-com:office:excel}ClientData (docx4j ObjectFactory.createClientData(value)). */
export function createClientDataElement(value: M.CTClientData): M.TypedNamedValue<M.CTClientData>;
/** The element {urn:schemas-microsoft-com:office:excel}ColHidden in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataColHidden(value)). */
export function createCTClientDataColHidden(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Colored in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataColored(value)). */
export function createCTClientDataColored(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Column in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataColumn(value)). */
export function createCTClientDataColumn(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}DDE in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataDDE(value)). */
export function createCTClientDataDDE(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Default in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataDefault(value)). */
export function createCTClientDataDefault(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}DefaultSize in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataDefaultSize(value)). */
export function createCTClientDataDefaultSize(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Disabled in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataDisabled(value)). */
export function createCTClientDataDisabled(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Dismiss in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataDismiss(value)). */
export function createCTClientDataDismiss(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}DropLines in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataDropLines(value)). */
export function createCTClientDataDropLines(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}DropStyle in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataDropStyle(value)). */
export function createCTClientDataDropStyle(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Dx in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataDx(value)). */
export function createCTClientDataDx(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}FirstButton in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataFirstButton(value)). */
export function createCTClientDataFirstButton(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}FmlaGroup in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataFmlaGroup(value)). */
export function createCTClientDataFmlaGroup(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}FmlaLink in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataFmlaLink(value)). */
export function createCTClientDataFmlaLink(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}FmlaMacro in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataFmlaMacro(value)). */
export function createCTClientDataFmlaMacro(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}FmlaPict in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataFmlaPict(value)). */
export function createCTClientDataFmlaPict(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}FmlaRange in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataFmlaRange(value)). */
export function createCTClientDataFmlaRange(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}FmlaTxbx in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataFmlaTxbx(value)). */
export function createCTClientDataFmlaTxbx(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Help in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataHelp(value)). */
export function createCTClientDataHelp(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Horiz in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataHoriz(value)). */
export function createCTClientDataHoriz(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Inc in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataInc(value)). */
export function createCTClientDataInc(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}JustLastX in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataJustLastX(value)). */
export function createCTClientDataJustLastX(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}LCT in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataLCT(value)). */
export function createCTClientDataLCT(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}ListItem in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataListItem(value)). */
export function createCTClientDataListItem(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}LockText in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataLockText(value)). */
export function createCTClientDataLockText(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Locked in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataLocked(value)). */
export function createCTClientDataLocked(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}MapOCX in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataMapOCX(value)). */
export function createCTClientDataMapOCX(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Max in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataMax(value)). */
export function createCTClientDataMax(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}Min in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataMin(value)). */
export function createCTClientDataMin(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}MoveWithCells in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataMoveWithCells(value)). */
export function createCTClientDataMoveWithCells(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}MultiLine in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataMultiLine(value)). */
export function createCTClientDataMultiLine(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}MultiSel in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataMultiSel(value)). */
export function createCTClientDataMultiSel(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}NoThreeD in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataNoThreeD(value)). */
export function createCTClientDataNoThreeD(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}NoThreeD2 in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataNoThreeD2(value)). */
export function createCTClientDataNoThreeD2(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Page in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataPage(value)). */
export function createCTClientDataPage(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}PrintObject in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataPrintObject(value)). */
export function createCTClientDataPrintObject(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}RecalcAlways in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataRecalcAlways(value)). */
export function createCTClientDataRecalcAlways(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Row in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataRow(value)). */
export function createCTClientDataRow(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}RowHidden in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataRowHidden(value)). */
export function createCTClientDataRowHidden(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}ScriptExtended in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataScriptExtended(value)). */
export function createCTClientDataScriptExtended(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}ScriptLanguage in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataScriptLanguage(value)). */
export function createCTClientDataScriptLanguage(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}ScriptLocation in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataScriptLocation(value)). */
export function createCTClientDataScriptLocation(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}ScriptText in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataScriptText(value)). */
export function createCTClientDataScriptText(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}SecretEdit in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataSecretEdit(value)). */
export function createCTClientDataSecretEdit(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Sel in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataSel(value)). */
export function createCTClientDataSel(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}SelType in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataSelType(value)). */
export function createCTClientDataSelType(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}SizeWithCells in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataSizeWithCells(value)). */
export function createCTClientDataSizeWithCells(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}TextHAlign in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataTextHAlign(value)). */
export function createCTClientDataTextHAlign(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}TextVAlign in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataTextVAlign(value)). */
export function createCTClientDataTextVAlign(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}UIObj in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataUIObj(value)). */
export function createCTClientDataUIObj(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}VScroll in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataVScroll(value)). */
export function createCTClientDataVScroll(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}VTEdit in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataVTEdit(value)). */
export function createCTClientDataVTEdit(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}Val in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataVal(value)). */
export function createCTClientDataVal(value: number): M.TypedNamedValue<number>;
/** The element {urn:schemas-microsoft-com:office:excel}ValidIds in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataValidIds(value)). */
export function createCTClientDataValidIds(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}Visible in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataVisible(value)). */
export function createCTClientDataVisible(value: string): M.TypedNamedValue<string>;
/** The element {urn:schemas-microsoft-com:office:excel}WidthMin in the scope of org_docx4j_vml_spreadsheetDrawing.CTClientData (docx4j ObjectFactory.createCTClientDataWidthMin(value)). */
export function createCTClientDataWidthMin(value: number): M.TypedNamedValue<number>;
