// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_org_w3_x1998_math_mathML]. Do not edit.
import type * as M from './org_docx4j_org_w3_x1998_math_mathML.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_org_w3_x1998_math_mathML.js';
import type * as Dep_org_docx4j_org_w3_x2003_inkML from './org_docx4j_org_w3_x2003_inkML.js';

/** docx4j ObjectFactory.createApplyType(): a org_docx4j_org_w3_x1998_math_mathML.ApplyType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createApplyType(init?: Partial<Omit<M.ApplyType, 'TYPE_NAME' | 'PARENT'>>): M.ApplyType;
/** docx4j ObjectFactory.createCiType(): a org_docx4j_org_w3_x1998_math_mathML.CiType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCiType(init?: Partial<Omit<M.CiType, 'TYPE_NAME' | 'PARENT'>>): M.CiType;
/** docx4j ObjectFactory.createCnType(): a org_docx4j_org_w3_x1998_math_mathML.CnType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createCnType(init?: Partial<Omit<M.CnType, 'TYPE_NAME' | 'PARENT'>>): M.CnType;
/** docx4j ObjectFactory.createConstantType(): a org_docx4j_org_w3_x1998_math_mathML.ConstantType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createConstantType(init?: Partial<Omit<M.ConstantType, 'TYPE_NAME' | 'PARENT'>>): M.ConstantType;
/** docx4j ObjectFactory.createMathType(): a org_docx4j_org_w3_x1998_math_mathML.MathType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createMathType(init?: Partial<Omit<M.MathType, 'TYPE_NAME' | 'PARENT'>>): M.MathType;
/** docx4j ObjectFactory.createOperatorType(): a org_docx4j_org_w3_x1998_math_mathML.OperatorType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createOperatorType(init?: Partial<Omit<M.OperatorType, 'TYPE_NAME' | 'PARENT'>>): M.OperatorType;
/** docx4j ObjectFactory.createQualifierType(): a org_docx4j_org_w3_x1998_math_mathML.QualifierType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createQualifierType(init?: Partial<Omit<M.QualifierType, 'TYPE_NAME' | 'PARENT'>>): M.QualifierType;
/** docx4j ObjectFactory.createSepType(): a org_docx4j_org_w3_x1998_math_mathML.SepType with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createSepType(init?: Partial<Omit<M.SepType, 'TYPE_NAME' | 'PARENT'>>): M.SepType;
/** The global element {http://www.w3.org/1998/Math/MathML}abs (docx4j ObjectFactory.createAbs(value)). */
export function createAbsElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}and (docx4j ObjectFactory.createAnd(value)). */
export function createAndElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}apply (docx4j ObjectFactory.createApply(value)). */
export function createApplyElement(value: M.ApplyType): M.TypedNamedValue<M.ApplyType>;
/** The global element {http://www.w3.org/1998/Math/MathML}arccos (docx4j ObjectFactory.createArccos(value)). */
export function createArccosElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}arcsin (docx4j ObjectFactory.createArcsin(value)). */
export function createArcsinElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}arctan (docx4j ObjectFactory.createArctan(value)). */
export function createArctanElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}ceiling (docx4j ObjectFactory.createCeiling(value)). */
export function createCeilingElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}ci (docx4j ObjectFactory.createCi(value)). */
export function createCiElement(value: M.CiType): M.TypedNamedValue<M.CiType>;
/** The global element {http://www.w3.org/1998/Math/MathML}cn (docx4j ObjectFactory.createCn(value)). */
export function createCnElement(value: M.CnType): M.TypedNamedValue<M.CnType>;
/** The global element {http://www.w3.org/1998/Math/MathML}cos (docx4j ObjectFactory.createCos(value)). */
export function createCosElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}degree (docx4j ObjectFactory.createDegree(value)). */
export function createDegreeElement(value: M.QualifierType): M.TypedNamedValue<M.QualifierType>;
/** The global element {http://www.w3.org/1998/Math/MathML}divide (docx4j ObjectFactory.createDivide(value)). */
export function createDivideElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}eq (docx4j ObjectFactory.createEq(value)). */
export function createEqElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}exp (docx4j ObjectFactory.createExp(value)). */
export function createExpElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}exponentiale (docx4j ObjectFactory.createExponentiale(value)). */
export function createExponentialeElement(value: M.ConstantType): M.TypedNamedValue<M.ConstantType>;
/** The global element {http://www.w3.org/1998/Math/MathML}false (docx4j ObjectFactory.createFalse(value)). */
export function createFalseElement(value: M.ConstantType): M.TypedNamedValue<M.ConstantType>;
/** The global element {http://www.w3.org/1998/Math/MathML}floor (docx4j ObjectFactory.createFloor(value)). */
export function createFloorElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}geq (docx4j ObjectFactory.createGeq(value)). */
export function createGeqElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}gt (docx4j ObjectFactory.createGt(value)). */
export function createGtElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}leq (docx4j ObjectFactory.createLeq(value)). */
export function createLeqElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}ln (docx4j ObjectFactory.createLn(value)). */
export function createLnElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}log (docx4j ObjectFactory.createLog(value)). */
export function createLogElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}logbase (docx4j ObjectFactory.createLogbase(value)). */
export function createLogbaseElement(value: M.QualifierType): M.TypedNamedValue<M.QualifierType>;
/** The global element {http://www.w3.org/1998/Math/MathML}lt (docx4j ObjectFactory.createLt(value)). */
export function createLtElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}math (docx4j ObjectFactory.createMath(value)). */
export function createMathElement(value: M.MathType): M.TypedNamedValue<M.MathType>;
/** The global element {http://www.w3.org/1998/Math/MathML}max (docx4j ObjectFactory.createMax(value)). */
export function createMaxElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}min (docx4j ObjectFactory.createMin(value)). */
export function createMinElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}minus (docx4j ObjectFactory.createMinus(value)). */
export function createMinusElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}neq (docx4j ObjectFactory.createNeq(value)). */
export function createNeqElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}not (docx4j ObjectFactory.createNot(value)). */
export function createNotElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}or (docx4j ObjectFactory.createOr(value)). */
export function createOrElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}pi (docx4j ObjectFactory.createPi(value)). */
export function createPiElement(value: M.ConstantType): M.TypedNamedValue<M.ConstantType>;
/** The global element {http://www.w3.org/1998/Math/MathML}plus (docx4j ObjectFactory.createPlus(value)). */
export function createPlusElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}power (docx4j ObjectFactory.createPower(value)). */
export function createPowerElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}product (docx4j ObjectFactory.createProduct(value)). */
export function createProductElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}quotient (docx4j ObjectFactory.createQuotient(value)). */
export function createQuotientElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}rem (docx4j ObjectFactory.createRem(value)). */
export function createRemElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}root (docx4j ObjectFactory.createRoot(value)). */
export function createRootElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}sep (docx4j ObjectFactory.createSep(value)). */
export function createSepElement(value: M.SepType): M.TypedNamedValue<M.SepType>;
/** The global element {http://www.w3.org/1998/Math/MathML}sin (docx4j ObjectFactory.createSin(value)). */
export function createSinElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}sum (docx4j ObjectFactory.createSum(value)). */
export function createSumElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}tan (docx4j ObjectFactory.createTan(value)). */
export function createTanElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}times (docx4j ObjectFactory.createTimes(value)). */
export function createTimesElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
/** The global element {http://www.w3.org/1998/Math/MathML}true (docx4j ObjectFactory.createTrue(value)). */
export function createTrueElement(value: M.ConstantType): M.TypedNamedValue<M.ConstantType>;
/** The global element {http://www.w3.org/1998/Math/MathML}xor (docx4j ObjectFactory.createXor(value)). */
export function createXorElement(value: M.OperatorType): M.TypedNamedValue<M.OperatorType>;
