// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2014_chartex.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';

/** The element {http://schemas.microsoft.com/office/drawing/2014/chartex}chart. */
export function chart(value: M.CTRelId): M.TypedNamedValue<M.CTRelId>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chartex}chartSpace. */
export function chartSpace(value: M.CTChartSpace): M.TypedNamedValue<M.CTChartSpace>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chartex}f. */
export function f(value: M.CTFormula): M.TypedNamedValue<M.CTFormula>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chartex}lvl (2 types by scope: TYPE_NAME is left to the caller; see the scoped create* wrappers). */
export function lvl(value: M.CTNumericLevel | M.CTStringLevel): M.TypedNamedValue<M.CTNumericLevel | M.CTStringLevel>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chartex}nf. */
export function nf(value: M.CTFormula): M.TypedNamedValue<M.CTFormula>;
/** The element {http://schemas.microsoft.com/office/drawing/2014/chartex}v. */
export function v(value: string): M.TypedNamedValue<string>;
