// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_docProps_core]. Do not edit.
import type * as M from './org_docx4j_docProps_core.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_docProps_core.js';
import type * as Dep_org_docx4j_docProps_core_dc_elements from './org_docx4j_docProps_core_dc_elements.js';

/** The element {http://schemas.openxmlformats.org/package/2006/metadata/core-properties}coreProperties. */
export function coreProperties(value: M.CoreProperties): M.TypedNamedValue<M.CoreProperties>;
