// Generated by jsonix-schema-compiler: element factories (creators and element wrappers) for the Jsonix module [org_docx4j_docProps_core_dc_elements]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://purl.org/dc/elements/1.1/';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function createElementContainer(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_docProps_core_dc_elements.ElementContainer' }, init); }
export function createSimpleLiteral(init) { return Object.assign({ TYPE_NAME: 'org_docx4j_docProps_core_dc_elements.SimpleLiteral' }, init); }
export function createAnyElement(value) { return __element(__ns0, 'any', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createContributorElement(value) { return __element(__ns0, 'contributor', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createCoverageElement(value) { return __element(__ns0, 'coverage', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createCreatorElement(value) { return __element(__ns0, 'creator', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createDateElement(value) { return __element(__ns0, 'date', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createDescriptionElement(value) { return __element(__ns0, 'description', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createFormatElement(value) { return __element(__ns0, 'format', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createIdentifierElement(value) { return __element(__ns0, 'identifier', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createLanguageElement(value) { return __element(__ns0, 'language', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createPublisherElement(value) { return __element(__ns0, 'publisher', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createRelationElement(value) { return __element(__ns0, 'relation', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createRightsElement(value) { return __element(__ns0, 'rights', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createSourceElement(value) { return __element(__ns0, 'source', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createSubjectElement(value) { return __element(__ns0, 'subject', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createTitleElement(value) { return __element(__ns0, 'title', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
export function createTypeElement(value) { return __element(__ns0, 'type', value, 'org_docx4j_docProps_core_dc_elements.SimpleLiteral'); }
