// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_powerpoint_x2014_inkAction.js';
import type * as Dep_org_docx4j_org_w3_x2003_inkML from './org_docx4j_org_w3_x2003_inkML.js';

/** The element {http://schemas.microsoft.com/office/powerpoint/2014/inkAction}actions. */
export function actions(value: M.CTActions): M.TypedNamedValue<M.CTActions>;
