// Generated by jsonix-schema-compiler: per-name element wrappers for the namespace of the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2010_main]. Do not edit.
// Every export is a pure function; a bundler keeps only the ones a program uses.
const __ns0 = 'http://schemas.microsoft.com/office/drawing/2010/main';
function __element(namespaceURI, localPart, value, typeName) {
  if (typeName !== undefined && value !== null && typeof value === 'object' && value.TYPE_NAME === undefined) { value.TYPE_NAME = typeName; }
  return { name: { namespaceURI, localPart }, value };
}
export function cameraTool(value) { return __element(__ns0, 'cameraTool', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTCameraTool'); }
export function compatExt(value) { return __element(__ns0, 'compatExt', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTCompatExt'); }
export function contentPart(value) { return __element(__ns0, 'contentPart', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTGvmlContentPart'); }
export function hiddenEffects(value) { return __element(__ns0, 'hiddenEffects', value, 'org_docx4j_dml.CTEffectProperties'); }
export function hiddenFill(value) { return __element(__ns0, 'hiddenFill', value, 'org_docx4j_dml.CTFillProperties'); }
export function hiddenLine(value) { return __element(__ns0, 'hiddenLine', value, 'org_docx4j_dml.CTLineProperties'); }
export function hiddenScene3d(value) { return __element(__ns0, 'hiddenScene3d', value, 'org_docx4j_dml.CTScene3D'); }
export function hiddenSp3d(value) { return __element(__ns0, 'hiddenSp3d', value, 'org_docx4j_dml.CTShape3D'); }
export function imgProps(value) { return __element(__ns0, 'imgProps', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTPhoto'); }
export function isCanvas(value) { return __element(__ns0, 'isCanvas', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTIsGvmlCanvas'); }
export function m(value) { return __element(__ns0, 'm', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTTextMath'); }
export function shadowObscured(value) { return __element(__ns0, 'shadowObscured', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTShadowObscured'); }
export function useLocalDpi(value) { return __element(__ns0, 'useLocalDpi', value, 'org_docx4j_com_microsoft_schemas_office_drawing_x2010_main.CTUseLocalDpi'); }
