// Generated by jsonix-schema-compiler: declarations of the per-name element wrappers for the Jsonix module [org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart]. Do not edit.
import type * as M from './org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_com_microsoft_schemas_office_drawing_x2012_chart.js';
import type * as Dep_org_docx4j_dml from './org_docx4j_dml.js';
import type * as Dep_org_docx4j_dml_chart from './org_docx4j_dml_chart.js';

/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}autoCat. */
export function autoCat(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}categoryFilterExceptions. */
export function categoryFilterExceptions(value: M.CTCategoryFilterExceptions): M.TypedNamedValue<M.CTCategoryFilterExceptions>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}datalabelsRange. */
export function datalabelsRange(value: M.CTSeriesDataLabelsRange): M.TypedNamedValue<M.CTSeriesDataLabelsRange>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}dlblFieldTable. */
export function dlblFieldTable(value: M.CTDataLabelFieldTable): M.TypedNamedValue<M.CTDataLabelFieldTable>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredAreaSeries. */
export function filteredAreaSeries(value: M.CTFilteredAreaSer): M.TypedNamedValue<M.CTFilteredAreaSer>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredBarSeries. */
export function filteredBarSeries(value: M.CTFilteredBarSer): M.TypedNamedValue<M.CTFilteredBarSer>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredBubbleSeries. */
export function filteredBubbleSeries(value: M.CTFilteredBubbleSer): M.TypedNamedValue<M.CTFilteredBubbleSer>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredCategoryTitle. */
export function filteredCategoryTitle(value: M.CTFilteredCategoryTitle): M.TypedNamedValue<M.CTFilteredCategoryTitle>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredLineSeries. */
export function filteredLineSeries(value: M.CTFilteredLineSer): M.TypedNamedValue<M.CTFilteredLineSer>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredPieSeries. */
export function filteredPieSeries(value: M.CTFilteredPieSer): M.TypedNamedValue<M.CTFilteredPieSer>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredRadarSeries. */
export function filteredRadarSeries(value: M.CTFilteredRadarSer): M.TypedNamedValue<M.CTFilteredRadarSer>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredScatterSeries. */
export function filteredScatterSeries(value: M.CTFilteredScatterSer): M.TypedNamedValue<M.CTFilteredScatterSer>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredSeriesTitle. */
export function filteredSeriesTitle(value: M.CTFilteredSeriesTitle): M.TypedNamedValue<M.CTFilteredSeriesTitle>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}filteredSurfaceSeries. */
export function filteredSurfaceSeries(value: M.CTFilteredSurfaceSer): M.TypedNamedValue<M.CTFilteredSurfaceSer>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}formulaRef. */
export function formulaRef(value: M.CTFormulaRef): M.TypedNamedValue<M.CTFormulaRef>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}fullRef. */
export function fullRef(value: M.CTFullRef): M.TypedNamedValue<M.CTFullRef>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}layout. */
export function layout(value: Dep_org_docx4j_dml_chart.CTLayout): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTLayout>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}leaderLines. */
export function leaderLines(value: Dep_org_docx4j_dml_chart.CTChartLines): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTChartLines>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}levelRef. */
export function levelRef(value: M.CTLevelRef): M.TypedNamedValue<M.CTLevelRef>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}numFmt. */
export function numFmt(value: Dep_org_docx4j_dml_chart.CTNumFmt): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTNumFmt>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}pivotSource. */
export function pivotSource(value: Dep_org_docx4j_dml_chart.CTPivotSource): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTPivotSource>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}showDataLabelsRange. */
export function showDataLabelsRange(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}showLeaderLines. */
export function showLeaderLines(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}spPr. */
export function spPr(value: Dep_org_docx4j_dml.CTShapeProperties): M.TypedNamedValue<Dep_org_docx4j_dml.CTShapeProperties>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}tx. */
export function tx(value: Dep_org_docx4j_dml_chart.CTTx): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTTx>;
/** The element {http://schemas.microsoft.com/office/drawing/2012/chart}xForSave. */
export function xForSave(value: Dep_org_docx4j_dml_chart.CTBoolean): M.TypedNamedValue<Dep_org_docx4j_dml_chart.CTBoolean>;
