// Generated by jsonix-schema-compiler: declarations of the element factories for the Jsonix module [org_docx4j_mce]. Do not edit.
import type * as M from './org_docx4j_mce.js';
import type { XmlQName, XmlCalendar, XmlDuration, XmlDomNode, XmlAnyElement, XmlAnyAttributes } from './org_docx4j_mce.js';
import type * as Dep_org_pptx4j_pml from './org_pptx4j_pml.js';
import type * as Dep_org_docx4j_dml_chart from './org_docx4j_dml_chart.js';
import type * as Dep_org_docx4j_dml_spreadsheetdrawing from './org_docx4j_dml_spreadsheetdrawing.js';
import type * as Dep_org_docx4j_wml from './org_docx4j_wml.js';
import type * as Dep_org_docx4j_math from './org_docx4j_math.js';
import type * as Dep_org_xlsx4j_sml from './org_xlsx4j_sml.js';

/** docx4j ObjectFactory.createAlternateContent(): a org_docx4j_mce.AlternateContent with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createAlternateContent(init?: Partial<Omit<M.AlternateContent, 'TYPE_NAME' | 'PARENT'>>): M.AlternateContent;
/** docx4j ObjectFactory.createAlternateContentChoice(): a org_docx4j_mce.AlternateContent.Choice with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createAlternateContentChoice(init?: Partial<Omit<M.AlternateContent.Choice, 'TYPE_NAME' | 'PARENT'>>): M.AlternateContent.Choice;
/** docx4j ObjectFactory.createAlternateContentFallback(): a org_docx4j_mce.AlternateContent.Fallback with TYPE_NAME set; a literal remains the stricter form (init is partial). */
export function createAlternateContentFallback(init?: Partial<Omit<M.AlternateContent.Fallback, 'TYPE_NAME' | 'PARENT'>>): M.AlternateContent.Fallback;
/** The global element {http://schemas.openxmlformats.org/markup-compatibility/2006}AlternateContent (docx4j ObjectFactory.createAlternateContent(value)). */
export function createAlternateContentElement(value: M.AlternateContent): M.TypedNamedValue<M.AlternateContent>;
