// The namespaces a reader is assumed to understand when a fixture's mc:Choice is resolved
// (CR-004 section 10.1).
//
// COPIED, with its provenance, from @docx4j/core-ts src/opc/mce/understood.mts as of its dd9e5b1
// (which took this package's 0.3.0). Copied rather than imported, deliberately: the set encodes a
// CONSUMER's judgement about what its own load-and-save preserves, and this package should be able
// to see when the two diverge rather than silently inherit a change. That session maintains it,
// asserts module by module in its own tests that it stays complete, and has undertaken to say when
// it changes.
//
// It matters here because `mc:Choice/@Requires` names PREFIXES, and a prefix means nothing without
// the declarations in scope where it is written - so the resolver looks each one up on the Choice
// element itself and asks whether the NAMESPACE is in this set. An earlier version of the resolver
// compared prefix strings against a hand-written list, which happened to work on three parts and
// would not have survived a document that spelled a prefix differently.
//
// Note what being in this set does not mean: the last three entries bind nothing at all. Excel's
// slicer namespaces are understood because the Choice they gate holds the slicer as DOM, which
// round-trips, where the Fallback is a placeholder box that loses it - so taking the Choice is
// the better outcome even with nothing bound. Understanding is about what survives, not about
// what is typed (docx4j CR-021 section 8.9).
export const UNDERSTOOD_NAMESPACES = new Set([
  'http://schemas.openxmlformats.org/wordprocessingml/2006/main',
  'http://schemas.openxmlformats.org/package/2006/relationships',
  'http://schemas.openxmlformats.org/markup-compatibility/2006',
  'http://schemas.openxmlformats.org/officeDocument/2006/math',
  'http://schemas.openxmlformats.org/officeDocument/2006/bibliography',
  'http://schemas.openxmlformats.org/officeDocument/2006/customXml',
  'http://schemas.openxmlformats.org/schemaLibrary/2006/main',
  'http://schemas.openxmlformats.org/officeDocument/2006/extended-properties',
  'http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes',
  'http://schemas.openxmlformats.org/package/2006/metadata/core-properties',
  'http://purl.org/dc/elements/1.1/',
  'http://purl.org/dc/terms/',
  'http://schemas.microsoft.com/office/2006/coverPageProps',
  'http://schemas.microsoft.com/office/2006/xmlPackage',
  'http://schemas.openxmlformats.org/drawingml/2006/main',
  'http://schemas.openxmlformats.org/drawingml/2006/picture',
  'http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing',
  'http://schemas.openxmlformats.org/drawingml/2006/chart',
  'http://schemas.openxmlformats.org/drawingml/2006/chartDrawing',
  'http://schemas.openxmlformats.org/drawingml/2006/diagram',
  'http://schemas.openxmlformats.org/drawingml/2006/compatibility',
  'http://schemas.openxmlformats.org/drawingml/2006/lockedCanvas',
  'http://schemas.openxmlformats.org/drawingml/2006/spreadsheetDrawing',
  'http://schemas.microsoft.com/office/drawing/2007/8/2/chart',
  'http://schemas.microsoft.com/office/drawing/2008/diagram',
  'http://schemas.microsoft.com/office/drawing/2010/main',
  'http://schemas.microsoft.com/office/drawing/2010/picture',
  'http://schemas.microsoft.com/office/drawing/2010/chartDrawing',
  'http://schemas.microsoft.com/office/drawing/2010/diagram',
  'http://schemas.microsoft.com/office/drawing/2012/main',
  'http://schemas.microsoft.com/office/drawing/2012/chart',
  'http://schemas.microsoft.com/office/drawing/2013/main/command',
  'http://schemas.microsoft.com/office/drawing/2014/main',
  'http://schemas.microsoft.com/office/drawing/2014/chart',
  'http://schemas.microsoft.com/office/drawing/2014/chart/ac',
  'http://schemas.microsoft.com/office/drawing/2014/chartex',
  'http://schemas.microsoft.com/office/drawing/2016/11/main',
  'http://schemas.microsoft.com/office/drawing/2016/12/diagram',
  'http://schemas.microsoft.com/office/drawing/2016/SVG/main',
  'http://schemas.microsoft.com/office/drawing/2017/03/chart',
  'http://schemas.microsoft.com/office/drawing/2017/decorative',
  'http://schemas.microsoft.com/office/drawing/2017/model3d',
  'http://schemas.microsoft.com/office/drawing/2018/animation',
  'http://schemas.microsoft.com/office/drawing/2018/animation/model3d',
  'http://schemas.microsoft.com/office/drawing/2018/hyperlinkcolor',
  'http://schemas.microsoft.com/office/thememl/2012/main',
  'urn:schemas-microsoft-com:vml',
  'urn:schemas-microsoft-com:office:office',
  'urn:schemas-microsoft-com:office:word',
  'urn:schemas-microsoft-com:office:excel',
  'urn:schemas-microsoft-com:office:powerpoint',
  'http://schemas.microsoft.com/office/word/2006/wordml',
  'http://schemas.microsoft.com/office/word/2010/wordml',
  'http://schemas.microsoft.com/office/word/2010/wordprocessingCanvas',
  'http://schemas.microsoft.com/office/word/2010/wordprocessingDrawing',
  'http://schemas.microsoft.com/office/word/2010/wordprocessingGroup',
  'http://schemas.microsoft.com/office/word/2010/wordprocessingShape',
  'http://schemas.microsoft.com/office/word/2012/wordml',
  'http://schemas.microsoft.com/office/word/2012/wordprocessingDrawing',
  'http://schemas.microsoft.com/office/word/2015/wordml/symex',
  'http://schemas.microsoft.com/office/word/2016/wordml/cid',
  'http://schemas.microsoft.com/office/word/2018/wordml',
  'http://schemas.microsoft.com/office/word/2018/wordml/cex',
  'http://schemas.microsoft.com/office/word/2026/wordml/cei',
  'http://schemas.microsoft.com/office/webextensions/taskpanes/2010/11',
  'http://schemas.microsoft.com/office/webextensions/webextension/2010/11',
  'http://schemas.microsoft.com/office/powerpoint/2010/main',
  'http://schemas.microsoft.com/office/powerpoint/2012/main',
  'http://schemas.microsoft.com/office/powerpoint/2013/main/command',
  'http://schemas.microsoft.com/office/powerpoint/2014/inkAction',
  'http://schemas.microsoft.com/office/powerpoint/2015/main',
  'http://schemas.microsoft.com/office/powerpoint/2015/09/main',
  'http://schemas.microsoft.com/office/powerpoint/2015/10/main',
  'http://schemas.microsoft.com/office/powerpoint/2016/6/main',
  'http://schemas.microsoft.com/office/powerpoint/2016/sectionzoom',
  'http://schemas.microsoft.com/office/powerpoint/2016/slidezoom',
  'http://schemas.microsoft.com/office/powerpoint/2016/summaryzoom',
  'http://schemas.microsoft.com/office/powerpoint/2017/3/main',
  'http://schemas.microsoft.com/office/powerpoint/2017/10/main',
  'http://schemas.microsoft.com/office/powerpoint/2018/4/main',
  'http://schemas.openxmlformats.org/presentationml/2006/main',
  'http://schemas.openxmlformats.org/spreadsheetml/2006/main',
  'http://schemas.microsoft.com/office/excel/2006/main',
  'http://schemas.microsoft.com/office/excel/2008/2/main',
  'http://schemas.microsoft.com/office/excel/2010/spreadsheetDrawing',
  'http://schemas.microsoft.com/office/spreadsheetml/2009/9/main',
  'http://schemas.microsoft.com/office/spreadsheetml/2010/11/main',
  'http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac',
  'http://schemas.microsoft.com/office/spreadsheetml/2011/1/ac',
  'http://schemas.microsoft.com/office/spreadsheetml/2014/11/main',
  'http://schemas.microsoft.com/office/spreadsheetml/2014/revision',
  'http://schemas.microsoft.com/office/spreadsheetml/2018/calcfeatures',
  'http://schemas.microsoft.com/ink/2010/main',
  'http://www.w3.org/1998/Math/MathML',
  'http://www.w3.org/2003/InkML',
  'http://schemas.microsoft.com/office/2006/encryption',
  'http://schemas.microsoft.com/office/2006/keyEncryptor/certificate',
  'http://schemas.microsoft.com/office/2006/keyEncryptor/password',
  'http://schemas.openxmlformats.org/officeDocument/2006/relationships',
  'http://schemas.openxmlformats.org/officeDocument/2006/custom-properties',
  'http://schemas.microsoft.com/office/drawing/2012/chartStyle',
  'http://schemas.microsoft.com/office/drawing/2016/ink',
  'http://schemas.microsoft.com/office/drawing/2010/slicer',
  'http://schemas.microsoft.com/office/drawing/2012/slicer',
  'http://schemas.microsoft.com/office/drawing/2012/timeslicer',
]);
